### DISCUSSION TITLE
[Bug]: 400 Bad Request: {'tagged_vlans': ['Expected a list of items but got type "int".']}\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

### DISCUSSION THREAD

**Discussion by leijonatm** [netbox-community/ansible_modules#1039] [Q&A] [answered]
### Ansible NetBox Collection version

v3.13.0

### Ansible version

```bash
ansible [core 2.14.6]
  config file = None
  configured module search path = ['/Users/pkapos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pkapos/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/pkapos/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/pkapos/Library/Python/3.9/bin/ansible
  python version = 3.9.6 (default, May  7 2023, 23:32:44) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Library/Developer/CommandLineTools/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.5.4

### Python version

3.9

### Steps to Reproduce

I have this data structure in vars file 
```yaml
devices:
  test-device1:
    name: Test Device 1
    device_type: test-device-type1
    device_role: router1
    site: UoP
    position: 12
    rack: Lande
    face: Front
    serial: "864kjfhi3y74"
    # primary_ip4: ""
    # description: ""
    # commments: ""
    interfaces:
      - name: GigabitEthernet22
        enabled: true
        mgmt_only: false
        type: 1000Base-t (1GE)
        mode: Access
        untagged_vlan: vlan401
      - name: GigabitEthernet23
        enabled: false
        mgmt_only: false
        type: 1000Base-t (1GE)
        mode: Tagged
        untagged_vlan: vlan401
        tagged_vlans: 
          - vlan1000
          - vlan1015
        lag:
          name: port-channel1
```

and using the following task am trying to add interfaces with tagged vlans
```yaml
- name: Create interfaces
  netbox.netbox.netbox_device_interface:
    data:
      device: "{{ item.value.name }}"
      name: "{{ item.value.interfaces.0.name }}"
      enabled: "{{ item.value.interfaces.0.enabled }}"
      type: "{{ item.value.interfaces.0.type|default(omit) }}"
      untagged_vlan:
        name: "{{ item.value.interfaces.0.untagged_vlan|default(omit) }}"
      tagged_vlans:
        name: "{{ item.value.interfaces.0.tagged_vlans.0|default(omit) }}"
        site: "{{ item.value.site }}"
      mgmt_only: "{{ item.value.interfaces.0.mgmt_only|default(omit) }}"
      mode: "{{ item.value.interfaces.0.mode|default(omit) }}"
    state: present
  loop: "{{ devices | dict2items }}"
```

### Expected Behavior

I would expect the module to take the list I am passing and make the changes to the netbox deployment.

### Observed Behavior

the error I am getting is 
`"module_stderr": "Traceback (most recent call last):\n  File \"/Users/pkapos/.ansible/tmp/ansible-tmp-1689773931.465058-10875-153879832037377/AnsiballZ_netbox_device_interface.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/pkapos/.ansible/tmp/ansible-tmp-1689773931.465058-10875-153879832037377/AnsiballZ_netbox_device_interface.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/pkapos/.ansible/tmp/ansible-tmp-1689773931.465058-10875-153879832037377/AnsiballZ_netbox_device_interface.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_device_interface', init_globals=dict(_module_fqn='ansible_collections.netbox.netbox.plugins.modules.netbox_device_interface', _modlib_path=modlib_path),\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/xk/xm2s_16j25l3byynb4h40rmh0000gn/T/ansible_netbox.netbox.netbox_device_interface_payload_net7ghvo/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device_interface.py\", line 362, in <module>\n  File \"/var/folders/xk/xm2s_16j25l3byynb4h40rmh0000gn/T/ansible_netbox.netbox.netbox_device_interface_payload_net7ghvo/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_device_interface.py\", line 358, in main\n  File \"/var/folders/xk/xm2s_16j25l3byynb4h40rmh0000gn/T/ansible_netbox.netbox.netbox_device_interface_payload_net7ghvo/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_dcim.py\", line 229, in run\n  File \"/var/folders/xk/xm2s_16j25l3byynb4h40rmh0000gn/T/ansible_netbox.netbox.netbox_device_interface_payload_net7ghvo/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1419, in _ensure_object_exists\n  File \"/var/folders/xk/xm2s_16j25l3byynb4h40rmh0000gn/T/ansible_netbox.netbox.netbox_device_interface_payload_net7ghvo/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1398, in _update_netbox_object\n  File \"/Users/pkapos/Library/Python/3.9/lib/python/site-packages/pynetbox/core/response.py\", line 595, in update\n    return self.save()\n  File \"/Users/pkapos/Library/Python/3.9/lib/python/site-packages/pynetbox/core/response.py\", line 568, in save\n    if req.patch(updates):\n  File \"/Users/pkapos/Library/Python/3.9/lib/python/site-packages/pynetbox/core/query.py\", line 385, in patch\n    return self._make_call(verb=\"patch\", data=data)\n  File \"/Users/pkapos/Library/Python/3.9/lib/python/site-packages/pynetbox/core/query.py\", line 247, in _make_call\n    raise RequestError(req)\npynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'tagged_vlans': ['Expected a list of items but got type \"int\".']}\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

which seems like a module issue.

What can be fixed here to add the interface with the tagged vlans? If I comment out the tagged vlan from the task it completes fine
