### DISCUSSION TITLE
ansible netbox module

### DISCUSSION THREAD

**Discussion by lasag-2511** [netbox-community/ansible_modules#1116] [General]
hi i am using netbox v3.6.1 and when i try to create device with ansible i have the following issue, has anyone found a solution?

```
  tasks:
    - name: Create device within NetBox with only required information
      netbox.netbox.netbox_device:
        netbox_url: http://netbox.local
        netbox_token: thisIsMyToken
        data:
          name: Test Device
          device_type: C9410R
          role: Core Switch
          site: Main
        state: present
```
"Unsupported parameters for (netbox.netbox.netbox_device) module: data.role.

**Comment by MrDiba** [comment]
According to the documentation and examples at <https://docs.ansible.com/ansible/latest/collections/netbox/netbox/netbox_device_module.html> you should use `device_role` instead of `role`.

Example from the above link:

```yaml
tasks:
    - name: Create device within NetBox with only required information
      netbox.netbox.netbox_device:
        netbox_url: http://netbox.local
        netbox_token: thisIsMyToken
        data:
          name: Test Device
          device_type: C9410R
          device_role: Core Switch
          site: Main
        state: present
```
