### DISCUSSION TITLE
Add a ip addres to a virtual machine by machine id

### DISCUSSION THREAD

**Discussion by MrDiba** [netbox-community/ansible_modules#1117] [Q&A]
I want to create a new virtual machine, add an interface to the machine and add an IP address to the newly created interface. The thing is that the virtual machine name already exist on an other site so I have to use the virtual machine id to reference the virtual machine. I have recently learned that it is possible to do this by using 
```yaml
virtual_machine:
  id: <vm_id>
```
Which is awesome! And works for creating the interface on the virtual machine. But creating an IP address and attaching it to the interface is giving me problems.

I have the following playbook that is giving me errors:

```yaml
- name: "Reserve virtual machine name"
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ vm_name }}"
      cluster: "cluster1"
      memory: "{{ vm_ram }}"
      site: "moon"
      vcpus: "{{ vm_cores }}"
      platform: "ubuntu"
      virtual_machine_role: "vm"
    state: present
  register: vm

- name: "Add VM backend interface to {{ vm_name }}"
  netbox.netbox.netbox_vm_interface: 
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      virtual_machine:
        id: "{{ vm.virtual_machine.id }}"
      name: "backend"
      description: "backend interface"
  register: device

- name: "Add backend IP address for {{ vm_name }}"
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      prefix: "10.1.1.0/24"
      assigned_object:
        virtual_machine: 
          id: "{{ vm.virtual_machine.id }}"
        name: "backend"
      dns_name: "{{ vm_name }}.example.com"
    state: new
  register: backend_vm_ip
```

This is throwing me an error: on the last step:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "{\"virtual_machine_id\":[\"“name” is not a valid value.\"]}"}
```

So I tried an different approach by accessing the object by device_id instead (received from the "add interface" step):

```yaml
- name: "Add backend IP address for {{ vm_name }}"
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      prefix: "10.1.1.0/24"
      assigned_object:
        device: 
          id: "{{ device.interface.id }}"
      dns_name: "{{ vm_name }}.example.com"
    state: new
  register: backend_vm_ip
```
But that is giving me the following error:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "{\"device_id\":[\"Enter a whole number.\"]}"}
```
Which I do not understand, as the number is "403".

So right now I have no clue how to add the IP address to the interface using device/interface.
