### DISCUSSION TITLE
How to associate interfaces to LAGs using Ansible facts

### DISCUSSION THREAD

**Discussion by gpipito** [netbox-community/ansible_modules#1134] [Q&A] [answered]
Hi,
I'm trying to populate netbox from facts gathered by ansible. I'm currently stuck trying to associate a device network interface to the associated LAG/Bond.
This is my sample:
```
    "ansible_facts": {
        ...
        "bond0": {          -> this should be my netbox lag_name (see below)
            "active": true,
            "device": "bond0",
            "features": {
                 ...
            },
            "slaves": [
                "eno1",     -> this should be my netbox interface_name (see below)
                "eno2"
            ],
            "speed": 10000,
            "timestamping": [
                "rx_software",
                "software"
            ],
            "type": "bonding"
        },
        "eno1": {          -> physical interfaces have same data structure as bonds without the "slaves" list
            ...
        },
        ...
    }
```
And this is the netbox task to configure the interface:
```
    - name: Netbox - Add interface to LAG
      netbox.netbox.netbox_device_interface:
        netbox_url: https://netbox/
        netbox_token: "{{ vault_netbox_token }}"
        validate_certs: false
        data:
          device: "{{ inventory_hostname }}"
          name: <interface_name>
          lag:
            name: <lag_name>
      loop/with_items: ???
```
I admit I am not good with handling nested dicts/list in ansible. Any help? (edited)

**Comment by gpipito** [comment, marked as answer]
I found a workaround:

1. I create a list of physical interfaces
2. then a list of bonds/lags
3. I combine interfaces and bonds in a new dict when interface name is contained in the bond slaves field
4. I update interfaces in netbox associating the bond
```
      - name: Create List - Interfaces
        set_fact:
          nb_interfaces: "{{ nb_interfaces|default([]) + [item] }}"
        with_items: "{{ ansible_facts.interfaces }}"
        when: >
          ansible_facts[item].module is defined and 
          ansible_facts[item].slaves is not defined

      - name: Create List - Bonds
        set_fact:
          nb_bonds: "{{ nb_bonds|default([]) + [item] }}"
        with_items: "{{ ansible_facts.interfaces }}"
        when: >
          ansible_facts[item].type is defined and 
          ansible_facts[item].type == 'bonding'

      - name: Map interfaces to bonds
        set_fact:
          lag_map: "{{ lag_map|default([]) + [{'name': item.0, 'bond': item.1}] }}" 
        loop: "{{ nb_interfaces | product(nb_bonds) | list }}"
        when: item.0 in ansible_facts[item.1].slaves

      - name: Netbox - Update interfaces LAG
        netbox.netbox.netbox_device_interface:
          netbox_url: https://cmdb.skl.one/
          netbox_token: "{{ vault_netbox_token }}"
          validate_certs: false
          data:
            device: "{{ inventory_hostname }}"
            name: "{{ item.name }}"
            lag:
              name: "{{ item.bond }}"
        with_items: "{{ lag_map }}"
        delegate_to: localhost
```
