### DISCUSSION TITLE
How to group `keyed_groups` having a `bool` as value?

### DISCUSSION THREAD

**Discussion by xenion1987** [netbox-community/ansible_modules#1342] [Q&A]
Hello 👋 

I would like to group my hosts based on a custom field of type `bool`, but I get this error:

```
Invalid group name format, expected a string or a list of them or dictionary, got: <class 'bool'>
```

I expected something like this:

```yaml
all:
  children:
    managed:
      children:
        managed_true:
          hosts:
            abc123: {}
        managed_false:
          hosts:
            xyz789: {}
```

How can I group them based on the custom field?

<details><summary>Here is my inventory config</summary>

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: https://my.domain
token: 123abc
group_by:
  - is_virtual
  - platforms
  - status
keyed_groups:
  - key: custom_fields.managed
    prefix: managed
```

</details>

Thanks in advance
