### DISCUSSION TITLE
How to create groups for device_role * site in the inventory plugin?

### DISCUSSION THREAD

**Discussion by ccope** [netbox-community/ansible_modules#1361] [Q&A]
I'm trying to fetch all of the machines matching a set of roles and sites, and then make site-specific groups. Ex:
```
query_filters:
  - role: role1
  - role: role2
  - role: role3
  - site: site1
  - site: site2
group_by:
 - ???
```
such that I get the following groups:
- site1_role1
- site2_role1
- site1_role2
- site2_role2
- site1_role3
- site2_role3

Is this possible?
