### DISCUSSION TITLE
[Feature Request]: Add "New" as state for netbox_mac_address

### DISCUSSION THREAD

**Discussion by David-Kahn-CA** [netbox-community/ansible_modules#1403] [Ideas]
# Proposed Functionality

Create a new mac_address object vs updating an existing object when state is set to new. This should function similar to how the new state works in the netbox_ip_address module for anycast addresses.

# Use Case

In our EVPN VXLAN fabric we utilize anycast interfaces for L3 traffic routing. All leaf switches which share the same anycast address share the same mac address for the anycast interfaces. As such we create a mac_address object in Netbox per anycast interface per leaf switch. This results in many records that we currently have to create manually, we are looking to automate this task.

Currently the module will update the mac_address object to the last defined item in the loop when given a state of present.

With the following variable:

```
    vlan_anycast_interface:
    - device: device1
      vlanid: 10
      mac_address: "0A:FE:00:00:00:10"
    - device: device2
      vlanid: 10
      mac_address: "0A:FE:00:00:00:10"
    - device: device3
      vlanid: 10
      mac_address: "0A:FE:00:00:00:10"
    - device: device4
      vlanid: 10
      mac_address: "0A:FE:00:00:00:10"
--- 
```

And the following task:

```
- name: Create and assign mac_address object for the anycast IPs.
  netbox.netbox.netbox_mac_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      mac_address: "{{ item.mac_address }}"
      assigned_object:
        device: "{{ item.device }}"
        name: "irb.{{ item.vlanid }}"
      description: "Anycast MAC {{item.device}} irb.{{item.vlanid}}"
    state: present
  loop: "{{ vlan_anycast_interface }}"
  tags: interfaces
```
