### DISCUSSION TITLE
Using custom fields in group by

### DISCUSSION THREAD

**Discussion by fatman00** [netbox-community/ansible_modules#1410] [Q&A]
Hi everyone,

Is it possible to use a custom field to group the devices in netbox_inventory.yml?

We have a custom text field called site_short that is a 3 letter abbreviation for all out sites.
Is there anyway I can add this to the group_by function in the inventory file to I will be able to limit my ansible playbooks only to devices in those sites?

```
---
plugin: netbox.netbox.nb_inventory
validate_certs: false
config_context: false
compose:
  ansible_network_os: '"ios"'

group_by:
  - device_roles
  - sites
query_filters:
  - status: active
  - tag: ansible
device_query_filters:
  - has_primary_ip: 'true'
```
