### DISCUSSION TITLE
Can not create virtual machine with primary_ip4 parameter

### DISCUSSION THREAD

**Discussion by futurearchitec** [netbox-community/ansible_modules#607] [Q&A] [answered]
Hello Everyone. I try to create a new virtual machine specifing the IP4-address via the parameter primary_ip4. I created the ip adress via the netbox.netbox.netbox_ip_address module successfully. I use the adress value (e. g. 10.0.2.4/24) here for the parameter value. ID of the IP-address is not being recognized, only IP-address itself is working. But then, the creation fails with the error

**The specified IP address (10.0.2.4/24) is not assigned to this VM.**

But this is the correct IP address as detected by Ansible via the ansible_default_ipv4.address fact. Quick help is needed, as relating VM and IP is very helpful.

**Comment by rodvand** [comment, marked as answer]
So this is an example playbook which works (just tested it):
```
---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Creating Virtual Machine
      netbox.netbox.netbox_virtual_machine:
        netbox_url: http://localhost:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          name: Test Virtual Machine
          cluster: Test

    - name: Create VM Interface
      netbox.netbox.netbox_vm_interface:
        netbox_url: http://localhost:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          name: eth0
          virtual_machine: Test Virtual Machine

    - name: Create IP address
      netbox.netbox.netbox_ip_address:
        netbox_url: http://localhost:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 192.168.9.1/24
          assigned_object:
            virtual_machine: Test Virtual Machine
            name: eth0

    - name: Set IP as primary
      netbox.netbox.netbox_virtual_machine:
        netbox_url: http://localhost:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          name: Test Virtual Machine
          primary_ip4: 192.168.9.1/24
```

So as the error message implies you have to assign the IP address to the VM, and it is done through adding it to a VM interface.
