### DISCUSSION TITLE
Failed to establish connection to NetBox API with v3.3.0

### DISCUSSION THREAD

**Discussion by smutel** [netbox-community/ansible_modules#639] [General]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible-playbook [core 2.11.6]
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2

###### NetBox:

v2.11.12

###### Collection:

v3.3.0 and v3.2.0

##### SUMMARY

If I use the version v3.2.0 my playbook is working correctly.
If I use the version v3.3.0, I have the message below:
```
fatal: [localhost]: FAILED! => changed=false 
  msg: Failed to establish connection to NetBox API
```

##### STEPS TO REPRODUCE

```yaml
- name: Ensure the VM is registered in netbox                                                   
    netbox.netbox.netbox_virtual_machine:                                                         
      netbox_url: "{{ netbox_url }}"                                                              
      netbox_token: "{{ netbox_token }}"                                                          
      validate_certs: "{{ netbox_validate_certs }}"                                               
      state: "{{ netbox_instance_state }}"                                                        
      data:                                                                                       
        cluster: "{{ __netbox_instance_cluster }}"                                                
        custom_fields: "{{ netbox_cf }}"                                                          
        name: "{{ netbox_instance_name }}"                                                        
        platform: "{{ netbox_instance_netbox_platform }}"                                         
        vcpus: "{{ netbox_instance_vcpus | default(omit) }}"                                      
        memory: "{{ netbox_instance_memory | default(omit) }}"                                    
        disk: "{{ netbox_instance_disk | default(omit) }}"                                        
    register: output
```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

Error
