### DISCUSSION TITLE
It is possible to make a groups tree?

### DISCUSSION THREAD

**Discussion by k0ste** [netbox-community/ansible_modules#668] [Q&A] [answered]
Hi, in ini inventory we can make a parent-children relations like this:

```ini
[main:children]
tag1
tag2

[tag1]
host1
host2

[tag2]
host3
host4
```

The tree will be:

```yaml
---
main:
  tag1:
    - host1
    - host2
  tag2:
    - host3
    - host4
```

This is possible to make a children of groups by `nb_inventory`? For example by tags of device or virtual machine object

Thanks!

**Comment by sc68cal** [comment]
You probably will have to look into [add_host](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/add_host_module.html) or [group_by](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_by_module.html#ansible-collections-ansible-builtin-group-by-module), or you will need to use a combination of `nb_inventory` and an INI file to create these hierarchies.

Ansible supports multiple `-i` parameters, so you can pass in both a dynamic inventory configuration as well as an INI file and as long as the hostnames all match it should work, but I have only used `add_host` to dynamically set groups in my playbooks.

**Reply by tobiicerb** [reply]
I have a problem with this as well, but with child groups. Is it possible to define child groups with the netbox inventory somehow? It does work with an additional file, but then I have to control my group definitions in two places, while I have to define the groups in netbox and then use another inventory to define the "relationship". The main reason for this is that variable precedence depends on the inventory source, if I understood this thread correctly: [Child group variable do not override parent group variable](https://github.com/ansible/ansible/issues/76700)

Example:
netbox_inventory:
```
plugin: netbox.netbox.nb_inventory
validate_certs: true
ansible_host_dns_name: yes
dns_name: yes
fetch_all: yes
config_context: true
interfaces: yes
vm_query_filters:
  - tag: production
  - status: active
device_query_filters:
  - id: -1

keyed_groups:
  - prefix: platform
    key: platform
  - prefix: tag
    key: tags
groups:
  linux: "'ubuntu' in platform"
  linuxwebserver: "'linuxwebserver' in tags"

```
Hosts file:
```
all:
  children:
    linux:
      hosts:
      children:
        linuxwebserver:
```

**Comment by k0ste** [comment, marked as answer]
Resolved via:
```yaml
---
plugin: 'netbox.netbox.nb_inventory'
api_endpoint: '<endpoint>'
token: '<token>'
config_context: 'no'
site_data: 'yes'
interfaces: 'yes'
group_names_raw: 'yes'
use_extra_vars: 'yes'
fetch_all: 'no'
group_by:
  - 'device_roles'
keyed_groups:
  - key: 'device_role'
    parent_group: 'my_root_group_name'
    trailing_separator: false
    separator: ''
query_filters:
  - status: 'active'
  - cluster_id: 3
device_query_filters:
  - has_primary_ip: 'true'
vm_query_filters:
  - name__empty: 'true'
```
