### DISCUSSION TITLE
Not reading variable value inside nb_lookup query

### DISCUSSION THREAD

**Discussion by MercifulCamel** [netbox-community/ansible_modules#676] [Q&A] [answered]
So I have a question in regards to passing a variable inside the nb_lookup module.

It currently looks like this 
```
- name: "Grabing facts from NetBox for {{ vm_name }}"
  set_fact:
    netbox_vm_memory: "{{ item.value.memory }}"
    netbox_vm_disk: "{{ item.value.disk }}"
    netbox_vm_vcpus: "{{ item.value.vcpus }}"
    netbox_tenant_id: "{{ item.value.tenant.id }}"
    netbox_vm_ip4: "{{ item.value.primary_ip4.address }}"
  loop: "{{ query('netbox.netbox.nb_lookup', 'virtual-machines', api_filter='name={{ vm_name }}', api_endpoint=netbox_url, token=netbox_token) }}"
```
the vm_name variable is set to ti332-ci332, but when I run it it looks for a virtual machine named vm_name instead of ti332-ci332.
Is there anyway to make it look for the variable value instead or is that impossible atm?
