### DISCUSSION TITLE
[Bug]: netbox.nb_lookup fails with self-signed certificates.

### DISCUSSION THREAD

**Discussion by joubbi** [netbox-community/ansible_modules#712] [Q&A]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible [core 2.12.1]
  python version 3.9.9 [GCC 11.2.0]
  jinja version = 2.11.3
  libyaml = True
###### NetBox:

v3.1.5
###### Collection:

3.5.1
##### SUMMARY
I have a server running Netbox with self-signed certificates.
Using netbox.nb_lookup against it fails with `SSL: CERTIFICATE_VERIFY_FAILED` even though I have specified `validate_certs='no'`.

The plugin netbox.nb_inventory works fine against the same Netbox server as long as I specify `validate_certs: False`.
The same playbook (with modified token and api_endpoint) works against another install of Netbox with a properly signed certificate.

##### STEPS TO REPRODUCE

```yaml

- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Obtain list of devices from Netbox
      debug:
        msg: >
          "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
           manufactured by {{ item.value.device_type.manufacturer.name }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
                      validate_certs='no',
                      api_endpoint='https://10.0.0.1/',
                      token='123') }}"
```

##### EXPECTED RESULTS

A list of devices should be printed out.
##### ACTUAL RESULTS

```
TASK [Obtain list of devices from Netbox] **********************************************************************************************************************************

fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'requests.exceptions.SSLError'>, original message: HTTPSConnectionPool(host='10.0.0.1', port=443): Max retries exceeded with url: /api/dcim/devices/?limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)'))). HTTPSConnectionPool(host='10.0.0.1', port=443): Max retries exceeded with url: /api/dcim/devices/?limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))"}
```
