### DISCUSSION TITLE
Getting a list of VMs with the owner tag results in a wildcard?

### DISCUSSION THREAD

**Discussion by Beinish** [netbox-community/ansible_modules#714] [Q&A]
Hello everyone,
I have a role in one of my playbooks that is supposed to get a list of VMs owned by a user. I query the `owner` tag by the username to get this list:

```yaml
# ROLE: INSTANCE_GET_OWNER
---
- name: Variables validation
  assert:
    that:
      - username is defined
    fail_msg: "[ERROR] Missing required variable"

- name: Get VM properties from CMDB via API
  uri:
    url: "https://netbox.domain/api/virtualization/virtual-machines/?cf_owner={{ username }}"
    headers:
      Accept: "application/json"
      Authorization: "Token aaaaaaaaaaaa"
    method: "GET"
    body_format: "json"
  register: vm

- name: _FACTS_
  set_fact:
    user_vm_list: "{{ vm.json | json_query('results[*].display') }}"

- name: Printing vm owner details
  ansible.builtin.debug:
    msg: "{{ user_vm_list }}"
```

The issue is that the text which is entered under `{{ username }}` seems to act like a wildcard, which is true to the web interface itself.

For example, I can query for `jon` which would return anything with `jon` in it: `ajona`, `jonb`, etc. It's as if I wrote `*jon*`. How can I make sure to return exactly what I need?

Thanks :)

Edit: after googling a bit more, I found the `ie` attribute which should be is exactly. Sorry for opening the thread.
