### DISCUSSION TITLE
custom fields in query_params

### DISCUSSION THREAD

**Discussion by fabricat** [netbox-community/ansible_modules#739] [Q&A]
I have a custom field named `uid` to keep the UUIDs assigned to VMs across several virtualization platforms.

Now, I'd prefer to rely on that field, rather than the VM name (that could change over time).
Unfortunately, when if I try to run the following task...
```
- name: "update VM on Netbox"
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ NETBOX_URL }}"
    netbox_token: "{{ NETBOX_TOKEN }}"
    state: present
    query_params:
      - cf_uid
      - cluster
    data:
      name:    "{{ vm_name }}"
      cluster: "{{ vm_cluster }}"
      custom_fields:
        uid: "{{ vm_id }}"
```
... I get this error
> More than one result returned for {my-vm-name}

I see the following request on the server:
> GET /api/virtualization/virtual-machines/?cluster_id=11&limit=0

It seems that the `cf_uid` param is stripped by Ansible or Python module.
How can I get my "unique ID" custom field to act as a real _unique_ ID?
