### DISCUSSION TITLE
[Feature]: Set IP as primary in netbox.netbox.netbox_ip_address

### DISCUSSION THREAD

**Discussion by jchmielniak** [netbox-community/ansible_modules#802] [Ideas]
### NetBox version

v3.2.4

### Feature type

Change to existing Module

### Proposed functionality

Module: netbox.netbox.netbox_ip_address
It should be possible to set IP as primary for VM/Device as it is in GUI. At the moment, you can assign IP address to VM/Device and interface, but you cannot set it as primary IP for this device.

### Use case

Creating IP with prefix and state:new allows to dynamically select IP address. There must be primary IP defined for use with netbox inventory. With this function, one can use netbox inventory imidiatelly.

**Comment by ThomasADavis** [comment]
It's a two step process - you create the IP, then you can assign that IP to the virtual device.

You cannot create the IP and set the primary_ip4/primary_ip6 at the same time.

We do this all the time -

```
    - name: and set as primary for that name.
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ vm.name }}"
          primary_ip4: "{{ interface.address }}"
          primary_ip6: "{{ interface.ipv6 | default(omit) }}"
      when:
        - interface.address is defined
        - interface.tags is defined
        - "'primary' in interface.tags"
      loop: "{{ vm.interfaces }}"
      loop_control:
        label: "{{ vm['name'] }} - {{ interface['address'] | default('unknown') }}"
        loop_var: interface
```

**Comment by sc68cal** [comment]
I am moving this to a discussion. My workflow is similar to @ThomasADavis 's but I'm willing to hear from other points of view

**Comment by jchmielniak** [comment]
We are using similar workflow to create VM and its interfaces from VM description in yaml. In the next step, we start pristine installation of this VM using data from netbox.
My idea was, to enable 'primary_ip' flag in API to be "consistent" with GUI options, where you can set this flag while creating and assigning interface.

This would make things easier in following workflow:
* we create dynamic ip using prefix:
```
- name: assign dynamic ip address
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox.url }}"
    validate_certs: false
    netbox_token: "{{ netbox.token }}"
    data:
      prefix: "{{ if.prefix }}"
      assigned_object:
        virtual_machine: "{{ vm.name }}"
        name: "{{ if.name }}"
      status: active
    state: new
  when: if.prefix is defined
  register: res
```
* then we get the assigned ip 
```
- name: show assigned ip
  ansible.builtin.debug:
    msg: "assigned ip: {{ res.ip_address.address }}"
  when: res.ip_address is defined
```
* and then we set it as primary with `netbox.netbox.netbox_virtual_machine`

It would be simple, if we could use something like:
```
- name: assign dynamic ip address and set it primary
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox.url }}"
    validate_certs: false
    netbox_token: "{{ netbox.token }}"
    data:
      prefix: "{{ if.prefix }}"
      assigned_object:
        virtual_machine: "{{ vm.name }}"
        name: "{{ if.name }}"
        primary: true
      status: active
    state: new
  when: if.prefix is defined
```
