### DISCUSSION TITLE
More than one result returned for bridge

### DISCUSSION THREAD

**Discussion by kemeris2000** [netbox-community/ansible_modules#863] [Q&A] [answered]
### Ansible NetBox Collection version

v3.8.1

### Ansible version

ansible [core 2.12.8]

### NetBox version

v3.3.5

### Python version

3.9

### Steps to Reproduce

Can not specify bridge by name for new interface.

This example does not work:
```
- name: Add bridge ports
      netbox.netbox.netbox_device_interface:
      netbox_url: "{{ netbox_api_endpoint }}"
      netbox_token: "{{ netbox_api_token_ansible_sync }}"
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.ifname }}"
          bridge:
            name: "vmbr0"
```

This example does work: 
```
- name: Add bridge ports
      netbox.netbox.netbox_device_interface:
      netbox_url: "{{ netbox_api_endpoint }}"
      netbox_token: "{{ netbox_api_token_ansible_sync }}"
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.ifname }}"
          bridge: 9
```

Actual failing example

```
       - name: Linux | Bridge | Add bridge ports
          netbox.netbox.netbox_device_interface:
            netbox_url: "{{ netbox_api_endpoint }}"
            netbox_token: "{{ netbox_api_token_ansible_sync }}"
            data:
              device: "{{ inventory_hostname }}"
              name: "{{ item.ifname }}"
              type: '1000BASE-T (1GE)'
              bridge:
                name: "vmbr0"
              mac_address: "{{ item.address | lower }}"
              mtu: "{{ item.mtu }}"
              enabled: "{{ (item.operstate == 'UP') | ternary(true, false) }}"
              custom_fields:
                is_ovs: false
            state: present
          delegate_to: localhost
          with_items: "{{ linux_ifacesall_map }}"
          when:
            - item.ifname in linux_bridge_ports_list
```

### Expected Behavior

Specify bridge interface by its name

### Observed Behavior

```
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_device_interface_payload_5onri8u4/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 700, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/usr/local/lib/python3.9/dist-packages/pynetbox/core/endpoint.py", line 153, in get
    raise ValueError(
failed: [s1.xxx.com -> localhost] (item={'ifindex': 8, 'ifname': 'eno6_50G', 'flags': ['BROADCAST', 'MULTICAST', 'UP', 'LOWER_UP'], 'mtu': 1500, 'qdisc': 'mq', 'master': 'vmbr0', 'operstate': 'UP', 'linkmode': 'DEFAULT', 'group': 'default', 'txqlen': 1000, 'link_type': 'ether', 'address': 'ec:0d:9a:7e:15:f6', 'broadcast': 'ff:ff:ff:ff:ff:ff', 'promiscuity': 1, 'min_mtu': 68, 'max_mtu': 9978, 'linkinfo': {'info_slave_kind': 'bridge', 'info_slave_data': {'state': 'forwarding', 'priority': 32, 'cost': 100, 'hairpin': False, 'guard': False, 'root_block': False, 'fastleave': False, 'learning': True, 'flood': True, 'id': '0x8003', 'no': '0x3', 'designated_port': 32771, 'designated_cost': 0, 'bridge_id': '8000.4a:ee:38:11:1a:6b', 'root_id': '8000.4a:ee:38:11:1a:6b', 'hold_timer': 0.0, 'message_age_timer': 0.0, 'forward_delay_timer': 0.0, 'topology_change_ack': 0, 'config_pending': 0, 'proxy_arp': False, 'proxy_arp_wifi': False, 'multicast_router': 1, 'mcast_flood': True, 'mcast_to_unicast': False, 'neigh_suppress': False, 'group_fwd_mask': '0', 'group_fwd_mask_str': '0x0', 'vlan_tunnel': False, 'isolated': False}}, 'inet6_addr_gen_mode': 'eui64', 'num_tx_queues': 128, 'num_rx_queues': 32, 'gso_max_size': 65536, 'gso_max_segs': 65535, 'phys_port_name': 'p0', 'phys_switch_id': 'f6157e00039a0dec', 'vfinfo_list': [], 'altnames': ['enp3s0np0']}) => changed=false 
  ansible_loop_var: item
  invocation:
    module_args:
      cert: null
      data:
        bridge:
          name: vmbr0
        custom_fields:
          is_ovs: false
        description: null
        device: s1.xxx.com
        duplex: null
        enabled: true
        form_factor: null
        label: null
        lag: null
        mac_address: ec:0d:9a:7e:15:f6
        mark_connected: null
        mgmt_only: null
        mode: null
        mtu: 1500
        name: eno6_50G
        parent_interface: null
        poe_mode: null
        poe_type: null
        speed: null
        tagged_vlans: null
        tags: null
        type: 1000BASE-T (1GE)
        untagged_vlan: null
        vrf: null
      netbox_token: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      netbox_url: https://netbox.xxx.com
      query_params: null
      state: present
      update_vc_child: false
      validate_certs: true
  item:
    address: ec:0d:9a:7e:15:f6
    altnames:
    - enp3s0np0
    broadcast: ff:ff:ff:ff:ff:ff
    flags:
    - BROADCAST
    - MULTICAST
    - UP
    - LOWER_UP
    group: default
    gso_max_segs: 65535
    gso_max_size: 65536
    ifindex: 8
    ifname: eno6_50G
    inet6_addr_gen_mode: eui64
    link_type: ether
    linkinfo:
      info_slave_data:
        bridge_id: 8000.4a:ee:38:11:1a:6b
        config_pending: 0
        cost: 100
        designated_cost: 0
        designated_port: 32771
        fastleave: false
        flood: true
        forward_delay_timer: 0.0
        group_fwd_mask: '0'
        group_fwd_mask_str: '0x0'
        guard: false
        hairpin: false
        hold_timer: 0.0
        id: '0x8003'
        isolated: false
        learning: true
        mcast_flood: true
        mcast_to_unicast: false
        message_age_timer: 0.0
        multicast_router: 1
        neigh_suppress: false
        'no': '0x3'
        priority: 32
        proxy_arp: false
        proxy_arp_wifi: false
        root_block: false
        root_id: 8000.4a:ee:38:11:1a:6b
        state: forwarding
        topology_change_ack: 0
        vlan_tunnel: false
      info_slave_kind: bridge
    linkmode: DEFAULT
    master: vmbr0
    max_mtu: 9978
    min_mtu: 68
    mtu: 1500
    num_rx_queues: 32
    num_tx_queues: 128
    operstate: UP
    phys_port_name: p0
    phys_switch_id: f6157e00039a0dec
    promiscuity: 1
    qdisc: mq
    txqlen: 1000
    vfinfo_list: []
  msg: More than one result returned for bridge
```

**Comment by rodvand** [comment, marked as answer]
Try this:
```
- name: Add bridge ports
      netbox.netbox.netbox_device_interface:
      netbox_url: "{{ netbox_api_endpoint }}"
      netbox_token: "{{ netbox_api_token_ansible_sync }}"
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.ifname }}"
          bridge:
            name: "vmbr0"
            device: "{{ inventory_hostname }}"
```
