### DISCUSSION TITLE
netbox_utils: Failed to establish connection to Netbox API

### DISCUSSION THREAD

**Discussion by vanoha** [netbox-community/ansible_modules#889] [Q&A] [answered]
**DESC**

netbox_utils module stopped working with the error message: "Failed to establish connection to Netbox API"

**ANSIBLE VERSION**
```
ansible 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
```

**NETBOX VERSION**
I installed netbox-docker and use it instead of setup manually. So this is `docker-compose.override.yml`

```
version: '3.4'
services:
  netbox:
    ports:
      - 8001:8080
```

**OS / ENVIRONMENT**

Ubuntu 20

**PYNETBOX VERSION**

```
Name: pynetbox
Version: 6.6.2
Summary: NetBox API client library
Home-page: https://github.com/digitalocean/pynetbox
Author: Zach Moody
Author-email: zmoody@do.co
License: Apache2
Location: /usr/local/lib/python3.10/dist-packages
Requires: requests, six
Required-by:
```

**STEPS**

I wrote the ansible playbook where I want to put new device to NetBox
```
  name: put information to netbox
  hosts: localhost
  connection: local
  tasks:
    - name: get list of devices from NetBox
      netbox.netbox.netbox_device:
        netbox_url: http://localhost
        netbox_token: c38e5ac63178e85bfc0743a58a4f5f31cb60d025
        validate_certs: False
        data:
          name: test device
          device_type: RouterOS 7
          device_role: router
          site: localnet
        state: present
```

I expected to see device "test device" in NetBox

**ACTUAL RESULTS**

```
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_device_payload_yl6ic2bv/ansible_netbox.netbox.netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 505, in _connect_netbox_api
    self.version = nb.version
  File "/usr/local/lib/python3.10/dist-packages/pynetbox/core/api.py", line 137, in version
    ).get_version()
  File "/usr/local/lib/python3.10/dist-packages/pynetbox/core/query.py", line 193, in get_version
    req = self.http_session.get(
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "custom_fields": null,
                "device_role": "router",
                "device_type": "RouterOS 7",
                "face": null,
                "local_context_data": null,
                "name": "test device",
                "platform": null,
                "position": null,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": null,
                "serial": null,
                "site": "localnet",
                "status": null,
                "tags": null,
                "tenant": null,
                "vc_position": null,
                "vc_priority": null,
                "virtual_chassis": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://localhost",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "Failed to establish connection to Netbox API"
}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
