### DISCUSSION TITLE
netbox_cable: Must define A and B terminations when creating a new cable

### DISCUSSION THREAD

**Discussion by alexhoopes** [netbox-community/ansible_modules#904] [Q&A] [answered]
I'm trying to create a cable from the SFP+1 interface of a device to a switch port but am getting the error "Must define A and B terminations when creating a new cable"
```
- name: "NetBox Automation"
  hosts: "{{ target_hosts }}"
  gather_facts: False

  tasks:
    - name: Connect cables on Netbox
      netbox.netbox.netbox_cable:
        netbox_url: https://netbox.domain.com/
        netbox_token: "{{ netbox_api_key }}"
        validate_certs: no
        data:
          termination_a_type: dcim.interface
          termination_a:
            device: "{{ inventory_hostname }}"
            name: SFP+1
          termination_b_type: dcim.interface
          termination_b:
            device: "{{ inventory_switch_name }}" 
            name: "{{ inventory_port_name }}"
          status: connected
        state: present
      delegate_to: localhost
      tags:
      - cable
```

Full traceback:
```
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_cable_payload_woyjs6dp/ansible_netbox.netbox.netbox_cable_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 1233, in _create_netbox_object
    nb_obj = nb_endpoint.create(data)
  File "/home/dev/.venv/ansible/lib/python3.8/site-packages/pynetbox/core/endpoint.py", line 313, in create
    req = Request(
  File "/home/dev/.venv/ansible/lib/python3.8/site-packages/pynetbox/core/query.py", line 399, in post
    return self._make_call(verb="post", data=data)
  File "/home/dev/.venv/ansible/lib/python3.8/site-packages/pynetbox/core/query.py", line 287, in _make_call
    raise RequestError(req)
fatal: [ansible-test-host -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "color": null,
                "custom_fields": null,
                "label": null,
                "length": null,
                "length_unit": null,
                "status": "connected",
                "tags": null,
                "termination_a": {
                    "device": "ansible-test-host",
                    "name": "SFP+1"
                },
                "termination_a_type": "dcim.interface",
                "termination_b": {
                    "device": "fm74l-las54vn2",
                    "name": "SwitchB-Port2"
                },
                "termination_b_type": "dcim.interface",
                "type": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.domain.com/",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "{\"__all__\":[\"Must define A and B terminations when creating a new cable.\"]}"
}
```

When I manually add the cable on Netbox with the same information it's working. What am I missing here?
