### DISCUSSION TITLE
Prefix module doesn't discern between identically named vlans from different vlan groups and/or sites

### DISCUSSION THREAD

**Discussion by artiomello** [netbox-community/ansible_modules#913] [Q&A]
### Ansible NetBox Collection version

v3.9.0

### Ansible version

Running in AWX. Version is irrelevant to the case.

### NetBox version

v3.3.7

### Python version

3.8

### Steps to Reproduce

netbox.netbox.netbox_prefix module doesn't have a way to specify vlans from specific vlan groups and/or sites, which in turn means that when you have identical vlan names in different vlan groups and/or sitesthe module will give the following error:
_"msg": "More than one result returned for vlan"_

1. Create two different VLAN Groups or Sites
2. Create an identically named VLAN in each group/site
3. Run the module with the vlan name defined
4. Make a sad face

### Expected Behavior

There should be a way to specify exact the vlan from a specific vlan groups and/or sites. 
If Netbox functionality and logic, allows this, the module should reflect it.

### Observed Behavior

Got a "failed" status with the following message:

"msg": "More than one result returned for vlan"

**Comment by sc68cal** [comment]
Can you share the relevant sections of your playbook and traceback? I have multiple sites at work with vlan and vlan groups, and multiple prefixes, and have not encountered this error, however our playbooks may differ in how we reference things.

**Comment by artiomello** [comment]
I create them using a loop like so:
![image](https://user-images.githubusercontent.com/102314521/209686464-c24ba722-f054-461c-b98d-9e9962711759.png)

And the prefix definition is:
![image](https://user-images.githubusercontent.com/102314521/209686438-06fa9f32-730a-4762-b20b-ab8231cb1ce5.png)

Don't mind the vlan being commented. As you can see, both the site and vlan is defined, but when I run it I get this:
![image](https://user-images.githubusercontent.com/102314521/209688304-86b7d057-dc4a-4a7a-a92e-dd18a356d209.png)

And I have this vlan name defined in two different vlan groups within the same site.

**Comment by sc68cal** [comment]
Looking at my playbooks, I was setting the following for a `prefix`:

```yaml
    - name: Create netbox prefixes for each CCP function
      netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          site: "{{ netbox_site_slug }}"
          prefix: "{{ item.prefix }}"
          description: "{{ item.description }}"
          vlan:
            name: "{{ item.vlan_name | default(omit) }}"
            vlan_group: "{{ item.vlan_group | default(omit) }}"
          tags:
            - "{{ az_tag }}"
          prefix_role: "{{ item.role }}"
        state: present
      loop: "{{ ccp_vlans_subnets }}"
      # some vlans don't have prefixes, so only create a prefix
      # if one is defined
      when: "'prefix' in item"
```

I believe you need to set the `vlan` key to have both the `vlan_group` and `name` attribute so that you select the correct VLAN.
