### DISCUSSION TITLE
Failed to create a custom link with obj.device_type in jinja2

### DISCUSSION THREAD

**Discussion by NTNTP** [netbox-community/ansible_modules#923] [General]
Hello, 

I'm trying to create a custom link with device.type value, but this is not working. 
This is how i wrote the link text :
{% if obj.device_type.name == 'ecs-8000' and obj.name == 'revs1000' %}{{ obj.name }}{% endif %}

And with the same writing with the device_role it's working : 
"{% if obj.device_role.name == 'Switch' and obj.name == 'ftsxo0' %}{{ obj.name }}{% endif %}"

I tried differents types of writing : 
{% if obj.device_type == 'ecs-ex500' and obj.name == 'revs1000' %}{{ obj.name }}{% endif %}
{% if obj.devicetype.name == 'ecs-ex500' and obj.name == 'revs1000' %}{{ obj.name }}{% endif %}

Did someone succed to create a custom link with the device type ? 

Thanks :smile:

**Comment by rodvand** [comment]
Are you doing this with an Ansible playbook since you're asking in the ansible repo? If so you should show your code. If it's a general NetBox question you'll get better answers in the main NetBox repo.

**Reply by NTNTP** [reply]
I tried the both way, i tried with the manual way with the same jinja's code as Ansible. It is also a general NetBox question but i use it first with Ansible. 
Here is my code : 

```
- name: "Create/ Delete Link"
      netbox.netbox.netbox_custom_link:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          content_type: "{{ item.content_type }}"
          name: "{{ item.name }}"
          link_text: "{{ item.link_text | default (omit) }}"
          link_url: "{{ item.link_url | default (omit) }}"
          group_name: "{{ item.group_name | default (omit) }}"
          button_class:  "{{ item.button_class | default (omit) }}"
          new_window: "{{ item.new_window | default (omit) }}"
        state: "{{ item.state | default ('present', true) }}"
      loop: "{{ netbox_data }}"
```
Ans then i call the vars : 

This one is not working

```
   - content_type: "dcim.device"
     name: "test"
     group_name: "test"
     link_text: !unsafe "{% if obj.device_type.name == 'ecs-8000' and obj.name == 'test' %}{{ obj.name }}{% endif %}"
     link_url: "https://0.0.0.0/login"
     new_window: true
```
But this one works

```
   - content_type: "dcim.device"
     name: "test"
     group_name: "test"
     link_text: !unsafe "{% if obj.device_role.name == 'Switch Core' and obj.name == 'test' %}{{ obj.name }}{% endif %}"
     link_url: "https://0.0.0.0/login"
     button_class: "red"
     new_window: true
```
I use unsafe before the vars because without, the code do not read jinja2. Maybe you do have another way to wrtite it ! 

Thanks for your help !
