### DISCUSSION TITLE
How to get VLAN / VLAN Group with netbox.netbox.nb_inventory?

### DISCUSSION THREAD

**Discussion by patrickpreuss** [netbox-community/ansible_modules#950] [General]
Hi 

How i do get the VLANs for a device via netbox.netbox.nb_inventory? 

Currently the VLAN Groups has the Scope of Site.

What would be the preferred Way? 

thanks in advance

**Comment by sc68cal** [comment]
Usually I use the `nb_lookup` plugin for things like this.

It'll be something like:

```yaml
  - name: Obtain list of vlans from NetBox
    debug:
      msg: >
        "{{ item }}"
    loop: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                    api_endpoint='http://localhost/',
                    api_filter='device=My-Device',
                    token='<redacted>') }}"
```

You can add site, vlan group, and other filters to the `api_filter` - check the docs for more info
