### DISCUSSION TITLE
nb_inventory: virtual_chassis all interfaces

### DISCUSSION THREAD

**Discussion by flohoff** [netbox-community/ansible_modules#996] [General]
Hi,
i am trying to configure interfaces and i am using nb_inventory. Now i have virtual_chassis aka Switch Stacks where only the master has a primary_ip. 

So i cant configure the secondarys on themselves. I'd like to get all interfaces in this stack as i do when configuring in the WebGUI of Netbox on the Master.

Using this inventory - then knows about the stacks virtual chassis name in the inventory, but returns only the interfaces of the stack master.

I am bit puzzled nobody had this issue before.

```
virtual_chassis_name: true

query_filters:
  - role: access-switch
  - role: routing-switch
  - tag: autoconf
  - status: active

interfaces: yes
fetch_all: no
device_query_filters:
  - has_primary_ip: 'true'

group_by:
 - device_roles
 - tags
```
