### ISSUE TITLE
Allow IP Assignment to FHRP group [Feature]: 

### ISSUE THREAD

**Issue by sinontaylor** [netbox-community/ansible_modules#1029]
### NetBox version

v3.4.0

### Feature type

Change to existing Module

### Proposed functionality

this ability doesnt exist as far as I can see in the documentation or code

### Use case

For devices in some kind of cluster you need FHRP group to store the IP. This already is available from netbox web ui just not via ansible.

### External dependencies

n/a

**Comment by nicolas-janzen** [comment]
Would love to see this, but i believe netbox has to extend their API for that.
[See this issue](https://github.com/netbox-community/netbox/issues/12275)

**Comment by nicolas-janzen** [comment]
In case anyone would like to implement FHRP group assignments in a hacky way right now here you go:

 `- name: Get device information
  uri:
    url: "{{ netbox_url '}}/api/virtualization/virtual-machines/?name={{ inventory_hostname }}"
    headers:
      Accept: "application/json"
      Authorization: "Token {{ netbox_token }}"
  register: devices_information

- name: Get fhrp information
  uri:
    url: "{{ netbox_url }}/api/ipam/fhrp-group-assignments/?virtual_machine_id={{ devices_information.json.results | json_query('[0].id') }}"
    headers:
      Accept: "application/json"
      Authorization: "Token {{ netbox_token }}"
  register: fhrp_information

- name: Display fhrp information
  debug:
    var: fhrp_information
`
My solution only works with virtual machines, change that if necessary.

**Comment by nicolas-janzen** [comment]
In case anyone would like to implement FHRP group assignments in a hacky way right now here you go:

 ```yaml
- name: Get device information
  uri:
    url: "{{ netbox_url '}}/api/virtualization/virtual-machines/?name={{ inventory_hostname }}"
    headers:
      Accept: "application/json"
      Authorization: "Token {{ netbox_token }}"
  register: devices_information

- name: Get fhrp information
  uri:
    url: "{{ netbox_url }}/api/ipam/fhrp-group-assignments/?virtual_machine_id={{ devices_information.json.results | json_query('[0].id') }}"
    headers:
      Accept: "application/json"
      Authorization: "Token {{ netbox_token }}"
  register: fhrp_information

- name: Display fhrp information
  debug:
    var: fhrp_information
```
My solution only works with virtual machines, change that if necessary.
