### ISSUE TITLE
[Bug]: Breaking changes in 3.6.0, device_role -> role

### ISSUE THREAD

**Issue by shaul75** [netbox-community/ansible_modules#1061]
PR: https://github.com/netbox-community/ansible_modules/pull/1062

### Ansible NetBox Collection version

v3.14.0

### Ansible version

https://github.com/netbox-community/netbox/releases/tag/v3.6.0

> The device_role field on the Device model has been renamed to role. The device_role field has been temporarily retained on the REST API serializer for devices for backward compatibility, but is read-only.

### NetBox version

v3.6.0

### Python version

3.10

### Steps to Reproduce

```
      netbox.netbox.netbox_device:
        data:
          name: "{{ ansible_facts['product_name'] }}"
          device_type: "{{ ansible_facts['product_name'] }}"
          device_role: 1
          site: 1
        state: present

```

### Expected Behavior

Device is created/updated

### Observed Behavior

```
{"role":["This field is required."]}
fatal: [10.0.20.10 -> localhost]: FAILED! => {
    "changed": false
}
```
