### ISSUE TITLE
[Bug]: Updating cluster in virtual machine results in an additional virtual machine with the exact same name

### ISSUE THREAD

**Issue by Sedl** [netbox-community/ansible_modules#1073]
### Ansible NetBox Collection version

v3.14.0

### Ansible version

```bash
ansible [core 2.15.4]
  config file = /Users/sedlmeier/ansible/venv/lib/python3.9/site-packages/ansible_collections/netbox/netbox/ansible.cfg
  configured module search path = ['/Users/sedlmeier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sedlmeier/ansible/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/sedlmeier/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/sedlmeier/ansible/venv/bin/ansible
  python version = 3.9.16 (main, Dec  7 2022, 10:06:04) [Clang 14.0.0 (clang-1400.0.29.202)] (/Users/sedlmeier/ansible/venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.5.1

### Python version

3.9

### Steps to Reproduce

We wanted to move an existing virtual machines to a different cluster. The task looks like this:

```yaml
    - name: Updating NetBox
      delegate_to: localhost
      become: false
      netbox.netbox.netbox_virtual_machine:
        netbox_url: '{{ hostvars["localhost"].netbox_url }}'
        netbox_token: '{{ hostvars["localhost"].netbox_token }}'
        data:
          name: '{{ inventory_hostname }}'
          vcpus: 8
          memory: 1024
          disk: 128
          cluster: cluster1.example.name
        state: present
```

### Expected Behavior

Move the existing VM to a different cluster.

### Observed Behavior

A new VM with the exact same name and the given data is created on the given cluster.

**Comment by sc68cal** [comment]
I will have to look at the code but my guess is that `name` and `cluster` is the way that a specific VM is looked up when `state: present` - because you are changing the `cluster` parameter it is not matching the VM that exists on the old cluster and that is why it is creating a new one.

**Comment by Sedl** [comment]
Thank you for your answer, this was the hint i needed. I've added `query_params` to restrict the lookup to `name` and now it works as i intended:

```yaml
    - name: Updating NetBox
      delegate_to: localhost
      become: false
      netbox.netbox.netbox_virtual_machine:
        netbox_url: '{{ hostvars["localhost"].netbox_url }}'
        netbox_token: '{{ hostvars["localhost"].netbox_token }}'
        query_params:
          - name
        data:
          name: '{{ inventory_hostname }}'
          vcpus: '{{ vcpus | int }}'
          memory: '{{ mem_mib | int }}'
          disk: '{{ disk_gib | int }}'
          cluster: '{{ _kvm_host }}'
        state: present
```
The question is if this is the intended default behaviour and if it makes sense to change that. This behaviour is probably not very obvious to most of the users. I think we should at least mention such things somewhere in the documentation.
