### ISSUE TITLE
Can't create device with empty name

### ISSUE THREAD

**Issue by TawR1024** [netbox-community/ansible_modules#108]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

##### SUMMARY

Can't create device with empty name.
In Netbox API field name is not required. It's useful when needs to create object such as organizer.  
You don't need to create organizers with different name, just once create object type organizer, then use it. 
Unfortunately Reservations not enough   informative as devices. 
##### STEPS TO REPRODUCE

```yaml
- name: "create new device"
  connection: local
  hosts: localhost
  collections:
    - netbox_community.ansible_modules
  gather_facts: False
  vars:
    name:
    role: plug
    type: organizer
    unit: 4
    rack: 6.6.6
    serial:
    site: test-1
    tenant: VPC

  tasks:
    - name: Create device with several specified options
      netbox_device:
        netbox_url: 
        netbox_token: 
        data:
          name: "{{ name }}"
          device_type: "{{ type }}" #url friendly
          device_role: "{{ role }}"
          site: "{{ site }}"
          rack: "{{ rack }}"
          position: "{{ unit }}"
          serial: "{{ serial }}"
          face: Front
          tenant: "{{ tenant }}"
          status: Planned
        state: present
```

##### ACTUAL RESULTS

```
msg": "More than one result returned for None"
```

As I can see, it's problem when module try to check if device exist.
`netbox_dcim.py`
```python
self.nb_object = self._nb_endpoint_get(nb_endpoint, object_query_params, name)

        if self.state == "present":
            self._ensure_object_exists(nb_endpoint, endpoint_name, name, data)

        elif self.state == "absent":
            self._ensure_object_absent(endpoint_name, name)

        try:
            serialized_object = self.nb_object.serialize()
        except AttributeError:
            serialized_object = self.nb_object
```

I have no idea how to fix it correctly.
