### ISSUE TITLE
[Bug]: netbox_ip_address does not assign ip to vm interface when using "prefix"

### ISSUE THREAD

**Issue by cmammoli** [netbox-community/ansible_modules#1086]
### Ansible NetBox Collection version

v3.14.0

### Ansible version

```bash
ansible [core 2.12.10]
  config file = /home/c.mammoli/.ansible.cfg
  configured module search path = ['/home/c.mammoli/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/c.mammoli/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/c.mammoli/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/c.mammoli/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True
```

### NetBox version

v3.6.3

### Python version

3.9

### Steps to Reproduce

I'm using the following simplified playbook to reproduce:
```yaml
---
- hosts: "localhost"
  gather_facts: true
  collections:
  - netbox.netbox

  tasks:
    - name: create and associate ip to vm interface
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "192.168.22.0/23"
          tenant: "{{ netbox_tenant }}"
          assigned_object:
            virtual_machine: "an_existing_vm"
            name: "an_existing_interface"
      register: ip

    - name: Set vm primary ip
      netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "an_existing_vm"
          primary_ip4: "{{ ip.ip_address }}"
          cluster: "an_existing_cluster"
          site: "{{ netbox_site }}"
          tenant: "{{ netbox_tenant }}"

```

### Expected Behavior

A new available IP in the prefix should be created and associated to the interface in the vm

### Observed Behavior

The new IP is created but is not associated to the VM. By consquence the 2nd step in the playbook fails.
If I explicitly set an IP address instead of a prefix the IP is created *and* associated
