### ISSUE TITLE
[Bug]: netbox.netbox.netbox_device - Create issue (role: This field is required) 

### ISSUE THREAD

**Issue by IBS-IT** [netbox-community/ansible_modules#1112]
### Ansible NetBox Collection version

v3.14.0

### Ansible version

```
ansible [core 2.15.5]
```

### NetBox version

v3.6.4

### Python version

3.11

### Steps to Reproduce

Create device with this task

```
    - name: Create device
      netbox.netbox.netbox_device:
        netbox_url: 'https://netboxinstance'
        netbox_token: 'token'
        data:
          device_role: 'database-server'
          device_type: 'ap7901'
          name: 'Demo'
          site: 'ncsu-128'
        state: 'present'
```

### Expected Behavior

A new device should be created.

### Observed Behavior

Running the playbook with -vvv produces the following error message.
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "airflow": null,
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "custom_fields": null,
                "description": null,
                "device_role": "some-device-role",
                "device_type": "some-device-type",
                "face": null,
                "local_context_data": null,
                "location": null,
                "name": "device-name",
                "platform": null,
                "position": null,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": null,
                "serial": null,
                "site": "device-site",
                "status": null,
                "tags": null,
                "tenant": null,
                "vc_position": null,
                "vc_priority": null,
                "virtual_chassis": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.myorganization.com",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "{\"role\":[\"This field is required.\"]}"
}
```
