### ISSUE TITLE
[Bug]: Invalid value when adding power_outlet_template

### ISSUE THREAD

**Issue by an-ky** [netbox-community/ansible_modules#1115]
### Ansible NetBox Collection version

3.15.0

### Ansible version

```bash
ansible [core 2.14.6]
  config file = /home/andreas.kuechler@ad.monalysis.de/projects/infrastructure/ansible/ansible.cfg
  configured module search path = ['/home/andreas.kuechler@ad.monalysis.de/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/andreas.kuechler@ad.monalysis.de/.virtualenvs/venv-ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/andreas.kuechler@ad.monalysis.de/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/andreas.kuechler@ad.monalysis.de/.virtualenvs/venv-ansible/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/andreas.kuechler@ad.monalysis.de/.virtualenvs/venv-ansible/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.6.4

### Python version

3.10

### Steps to Reproduce

Running the following playbook 

```
- name: Setup Netbox
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    netbox_url: "http://localhost:8000"
    netbox_token: <your_token_here>

  tasks:
    - name: "Devices | add manufacturer"
      netbox.netbox.netbox_manufacturer:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "other"
          description: "Acme Crazy Gear"

    - name: "Devices | add device type"
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          model: Simple PDU
          manufacturer: "other"
          is_full_depth: false

    - name: "Devices | add interface template"
      netbox.netbox.netbox_device_interface_template:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: eth1
          type: 1000base-t
          mgmt_only: true
          device_type: Simple PDU

    - name: "Devices | add power port template"
      netbox.netbox.netbox_power_port_template:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: input
          type: iec-60309-2p-e-4h
          device_type: Simple PDU

    - name: "Devices | add power outlets"
      netbox.netbox.netbox_power_outlet_template:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "C19-1"
          type: "iec-60320-c19"
          power_port_template: "input"
          feed_leg: "A"
          device_type: Simple PDU
```

### Expected Behavior

A device type should be created with an interface template named eth1, a power port template named input and a power outlet template named C19-19

### Observed Behavior

ansible playbook returns an error when creating the power_outlet_template

```bash
$ ansible-playbook netbox_bug_power_outlet_template.yaml 
[WARNING]: Found variable using reserved name: connection

PLAY [Setup Netbox] *********************************************************************************************************************************************************************************************************************************************************************************************

TASK [Devices | add manufacturer] *******************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Devices | add device type] ********************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Devices | add interface template] *************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Devices | add power port template] ************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Devices | add power outlets] ******************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

{"devicetype_id":["“simple-pdu” is not a valid value."]}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
The interface and power port templates are properly created, but using the model name as device_type when creating power_outlet_templates produces an error.
When using the device_type **id**, the power_outlet_template is properly created.
