### ISSUE TITLE
[Docs]: vlan group option name is 'vlan_group' not 'group'

### ISSUE THREAD

**Issue by vincemulhollon** [netbox-community/ansible_modules#1137]
### Change Type

Correction

### Area

Configuration parameters

### Proposed Changes

The benefit is a microscopic improvement in the documentation examples for creating VLANs

There are no known drawbacks.

I'll submit a two line PR that seems to correct the issue, in a minute.

**Comment by vincemulhollon** [comment]
This is tested and working in my home lab with the option name 'vlan_group' instead of 'group' BTW:

```
- name: VLAN 10 PROD
  netbox.netbox.netbox_vlan:
    netbox_url: "{{ NETBOX_API }}"
    netbox_token: "{{ NETBOX_TOKEN }}"
    data:
      vlan_group: "Physical"
      vlan_role: "Active"
      name: "PROD"
      vid: "10"
      status: "Active"
      description: "Production VLAN"
      comments: "802.1(p) tag 4"
````
