### ISSUE TITLE
[Bug]: Unsupported parameters for (netbox.netbox.netbox_device) module: data.custom_fields['sw_version_re0']. Supported parameters include: airflow, asset_tag, cluster, comments, custom_fields, ...

### ISSUE THREAD

**Issue by xtxerr** [netbox-community/ansible_modules#1145]
### Ansible NetBox Collection version

v3.15.0

### Ansible version

```
ansible [core 2.15.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.5 (main, Sep 22 2023, 15:34:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v2.11.4

### Python version

3.11

### Steps to Reproduce
```
- name: Update Version RE0
  tags: device:version
  netbox.netbox.netbox_device:
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    data:
      name: "{{ inventory_hostname }}"
      custom_fields['sw_version_re0']: "{{ ansible_facts['junos']['version_RE0'] }}"
    state: present
```
### Expected Behavior

Being able to update custom_fields of a device.

### Observed Behavior

  "msg": "Unsupported parameters for (netbox.netbox.netbox_device) module: data.custom_fields['sw_version_re0']. Supported parameters include: airflow, asset_tag, cluster, comments, custom_fields, description, device_role, device_type, face, local_context_data, location, name, oob_ip, platform, position, primary_ip4, primary_ip6, rack, serial, site, status, tags, tenant, vc_position, vc_priority, virtual_chassis."
