### ISSUE TITLE
[Bug]:  Error during update LAG property for interface on non-master switch  of VC.  LAG exists for master of VC

### ISSUE THREAD

**Issue by netlamer** [netbox-community/ansible_modules#1148]
### Ansible NetBox Collection version

v3.13.0

### Ansible version

```bash
ansible [core 2.15.8]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/venv/venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/venv/venv/bin/ansible
  python version = 3.9.18 (main, Nov 18 2023, 01:00:14) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/root/venv/venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.7.0

### Python version

3.9

### Steps to Reproduce

Both switches are members of a VC.  switch--0  is a master, so aeXX (aggregated ethernet) interfaces created under master switch
playbook example  
```
- name: Update
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
      netbox.netbox.netbox_device_interface:
        netbox_url: netbox_URL
        netbox_token: netbox_token
        data:
          device: switch--0
          name: et-0/0/0:0
          type: 25gbase-x-sfp28
          description: bg-dc-2229-1
          lag: ae56

    - name: Create or update interface
      netbox.netbox.netbox_device_interface:
        netbox_url: netbox_URL
        netbox_token: netbox_token
        data:
          device: switch--1
          name: et-1/0/0:0
          type: 25gbase-x-sfp28
          lag: ae56

```

### Expected Behavior

update interface in netbox as a part of LAG

### Observed Behavior

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "bridge": null,
                "custom_fields": null,
                "description": "description",
                "device": "switch--1",
                "duplex": null,
                "enabled": null,
                "form_factor": null,
                "label": null,
                "lag": "ae56",
                "mac_address": null,
                "mark_connected": null,
                "mgmt_only": null,
                "mode": null,
                "mtu": null,
                "name": "et-1/0/0:0",
                "parent_interface": null,
                "poe_mode": null,
                "poe_type": null,
                "speed": null,
                "tagged_vlans": null,
                "tags": null,
                "tx_power": null,
                "type": "25gbase-x-sfp28",
                "untagged_vlan": null,
                "vrf": null,
                "wwn": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "netbox_URL",
            "query_params": null,
            "state": "present",
            "update_vc_child": false,
            "validate_certs": true
        }
    },
    "msg": "Could not resolve id of lag: ae56"
```
