### ISSUE TITLE
[Bug]: netbox_device_interface don't unassign an interface from a LAG (silently)

### ISSUE THREAD

**Issue by SteveRodrigue** [netbox-community/ansible_modules#1159]
### Ansible NetBox Collection version

v3.14.0

### Ansible version

```
  ansible [core 2.15.6]
  config file = /home/**hidden**/ansible.cfg
  configured module search path = ['/home/**hidden****hidden**/modules']
  ansible python module location = /home/**hidden**/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/**hidden**/collections:/home/**hidden**/nina_venv/lib/python3.9/site-packages
  executable location = /home/**hidden**/.venv/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/home/**hidden**/.venv/bin/python)
  jinja version = 3.1.2
  libyaml = True

```

### NetBox version

v3.3.10

### Python version

3.9

### Steps to Reproduce

Simply try to clear the LAG association with the module.

```
netbox.netbox.netbox_device_interface:
  netbox_url: "{{ netbox_url }}"
  netbox_token: "{{ netbox_token }}"
  data:
    device: targeted-device
    name: GigabitEthernet0/0
    lag: null
  state: present
```

This task works and doesn't return any error, but it would not set the lag value to null (it doesn't change it). Basically: it silently fail at setting the LAG field to null.

A similar change done with Swagger works (interfaces/{ID}/) will clear the LAG value (will set it to null).

### Expected Behavior

The Ansible module should clear/replace values when we are using null as the direct API call does.

### Observed Behavior

Silent fail: nothing changes in Netbox and Ansible reports a successful task.
