### ISSUE TITLE
[Bug]: Error when changing the subnet mask of an existing IP address (module netbox_ip_address)

### ISSUE THREAD

**Issue by Cyrilpop** [netbox-community/ansible_modules#1204]
### Ansible NetBox Collection version

v2.14.2

### Ansible version

```bash
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/netbox/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /usr/share/ansible/ansible_collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb 17 2023, 09:28:16) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.6.5

### Python version

3.11

### Steps to Reproduce

```yaml
    - name: "[Create IPs]"
      netbox.netbox.netbox_ip_address:
        data:
          address: "12.34.56.78"
          assigned_object:
            device: test-device
            name: test-interface-1
          vrf: test-vrf-1

    - name: "Change subnet mask"
      netbox.netbox.netbox_ip_address:
        data:
          address: "12.34.56.78/27"
          assigned_object:
            device: test-device
            name: test-interface-1
          vrf: test-vrf-1
```

### Expected Behavior

Possible bug in Ansible inventory regarding subnet mask. When changing the mask of an existing IP, the update should be reflected in Netbox without generating any errors.

### Observed Behavior

When changing the subnet mask in the inventory, the following message is displayed, although the update should be performed without having to manually delete in Netbox.
```bash
msg: '{"address":["Duplicate IP address found in test-vrf-1: 12.34.56.78/32"]}'
```
