### ISSUE TITLE
[Bug]: No way to make netbox_prefix with first_available idempotent

### ISSUE THREAD

**Issue by gc-nathanh** [netbox-community/ansible_modules#1212]
### Ansible NetBox Collection version

v3.15.0

### Ansible version

```bash
ansible [core 2.15.9]
  config file = None
  configured module search path = ['/home/stack/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stack/tools/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/stack/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/stack/tools/bin/ansible
  python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/home/stack/tools/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### NetBox version

v3.7.3

### Python version

3.9

### Steps to Reproduce

Create a new prefix dynamically using 

```
- name: Lets create some prefixes
    netbox.netbox.netbox_prefix:
      netbox_url: "{{ netboxurl }}"
      netbox_token: "{{ netboxtoken }}"
      data:
        parent: "10.100.248.0/22"
        prefix_length: 30
        description: "spine1-leaf1-p2p"
      first_available: true
      state: present
```
to create a new /30 prefix, then run the playbook a second time. 

### Expected Behavior

I expected the prefix to be created on the first playbook run, and no new prefixes created on the second run. 

### Observed Behavior

Running the playbook a second time creates another dynamically assigned prefix with the same description. 

I have attempted to use `query_params:` attempt to ensure uniqueness

```
- name: Lets create some prefixes
    netbox.netbox.netbox_prefix:
      netbox_url: "{{ netboxurl }}"
      netbox_token: "{{ netboxtoken }}"
      data:
        parent: "10.100.248.0/22"
        prefix_length: 30
        description: "spine1-leaf1-p2p"
      first_available: true
      state: present
      query_params:
      - description
```
results in a failure to create:
` fatal: [spine1]: FAILED! => {"changed": false, "msg": "{\"prefix\":[\"Duplicate prefix found in global table: 10.100.248.36/30\"]}"} `
