### ISSUE TITLE
[Bug]: Failed to establish connection to NetBox API

### ISSUE THREAD

**Issue by xibriz** [netbox-community/ansible_modules#1240]
### Ansible NetBox Collection version

v3.18.0

### Ansible version

```bash
ansible [core 2.16.6]
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### NetBox version

v4.0.2

### Python version

3.10

### Steps to Reproduce

The following task works fine in Netbox v3.7.2 but not in v4.0.2:

```yaml
- name: Create site
  netbox.netbox.netbox_site:
    netbox_url: URL
    netbox_token: TOKEN
    data:
      name: Test
      slug: test
    state: present
```

### Expected Behavior

TASK [Create site] ***********************************************************************************************************************************************************************************
ok: [localhost]

### Observed Behavior

TASK [Create site] ***********************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to establish connection to NetBox API"}
