### ISSUE TITLE
[Bug]: Cable Module is not idempotent

### ISSUE THREAD

**Issue by sapergus** [netbox-community/ansible_modules#1274]
### Ansible NetBox Collection version

v3.19.1

### Ansible version

```bash
ansible [core 2.17.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pergus/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pergus/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/pergus/.ansible/ansible_collections
  executable location = /home/pergus/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### NetBox version

v3.7.8

### Python version

3.10

### Steps to Reproduce

Running a cabling task more than once causes exceptions on subsequent runs. 
For example, connecting a console port to a console server port results in the following exception: console-ports not found in API_APPS_ENDPOINT.

The problem, as I understand it, is that on the second run, the object already exists in NetBox and the endpoint to the object is returned by _nb_endpoint_get(). However, the naem of the endpointthat pynetbox returns contains dashes instead of underscore, even though the pynetbox documentation states: "To call NetBox endpoints with dashes in their names, you should convert the dash to an underscore."

Here is an example of how pynetbox converts the name of an endpoint before returning it:
```
>>> import pynetbox
>>> nb = pynetbox.api("localhost:32768", token="XXX")
>>> dcim = getattr(nb, "dcim")
>>> console_ports = getattr(dcim, "console_ports")
>>> console_ports.name
'console-ports'
```

Previously reported bugs have been fixed by adding the endpoint with dashes to API_APPS_ENDPOINT and ENDPOINT_NAME_MAPPING.

I don't mind trying to fix this because I have playbooks that do a lot of cabling and I need them to be idempotent. However, I would like to know the best approach to take in solving this issue. I see three possible solutions:

1. Adding endpoints to API_APPS_ENDPOINT and ENDPOINT_NAME_MAPPING as has been done in the past.
2. Instead of accessing API_APPS_ENDPOINT and ENDPOINT_NAME_MAPPING directly in the code, do it through a function that converts underscores to dashes.
3. Open an issue in the pynetbox project and request that they return the endpoint name in the same format as required for a call.

Does anyone have any other suggestions?

There are several open bugs related to this issue, such as:

#946
#1217
#1040
#1015

### Expected Behavior

It should be possbile to run netbox_cable tasks more than once.

### Observed Behavior

The task below, raises the exception: console-ports not found in API_APPS_ENDPOINT.

```
- name: 7 - Connect FrontPort and RearPort
  netbox.netbox.netbox_cable:
    netbox_url: http://localhost:32768
    netbox_token: "XXX"
    data:
      termination_a_type: dcim.frontport
      termination_a:
        device: CablingDeviceA
        name: FrontPort
      termination_b_type: dcim.rearport
      termination_b:
        device: CablingDeviceA
        name: RearPort
  register: test_seven
```

**Comment by ellisgeek** [comment]
I think option 3 is ideal but there might be pushback due to the breaking nature of the change, so option 2 might be the best solution in the short term. Option 1 is less than ideal because it requires updating the code when a new endpoint is added.

**Comment by HoopesC** [comment]
I am getting the error `Exception: power-ports not found in API_APPS_ENDPOINTS`. The code below creates the `dcim.interface` -> `dcim.interface` cables first then the `dcim.powerport` -> `dcim.poweroutlet` cables. 

On a subsequent run, when all cables exist, the `dcim.interface` correctly mark as `Changed` while the `dcim.powerport` -> `dcim.poweroutlet` error out. 

Ansible NetBox Collection version
v3.17.0 (Also fails on v3.19.1)
NetBox version
v3.7.8
Python version
3.10

``` YAML
- name: Create cable
      netbox.netbox.netbox_cable:
        netbox_url: "{{ netbox_url_prod }}"
        netbox_token: "{{ netbox_token_ansible }}"
        data: "{{ item }}"
        validate_certs: false
      loop: "{{ netbox_data_cables }}"
      delegate_to: localhost
 ```
 Vars:
 ``` YAML
 netbox_data_cables:
  - color: "{{ netbox_cable_colors.aqua }}"
    description: Q-4S28AO07
    length: 7
    length_unit: m
    status: connected
    tenant: "{{ netbox_tenant }}"
    termination_a:
      device: "{{ inventory_hostname }}"
      name: eth1
    termination_a_type: dcim.interface
    termination_b:
      device: switch1
      name: d20
    termination_b_type: dcim.interface
    type: aoc
  - color: "{{ netbox_cable_colors.brown }}"
    description: QSFP-4SFP25G-CU2M
    length: 2
    length_unit: m
    status: connected
    tenant: "{{ netbox_tenant }}"
    termination_a:
      device: "{{ inventory_hostname }}"
      name: eth2
    termination_a_type: dcim.interface
    termination_b:
      device: switch2
      name: d20
    termination_b_type: dcim.interface
    type: dac-passive
  - color: "{{ netbox_cable_colors.black }}"
    length: 1
    length_unit: ft
    status: connected
    tenant: "{{ netbox_tenant }}"
    termination_a:
      device: "{{ inventory_hostname }}"
      name: p1
    termination_a_type: dcim.powerport
    termination_b:
      device: pdu1
      name: o25
    termination_b_type: dcim.poweroutlet
    type: power
  - color: "{{ netbox_cable_colors.black }}"
    length: 1
    length_unit: ft
    status: connected
    tenant: "{{ netbox_tenant }}"
    termination_a:
      device: "{{ inventory_hostname }}"
      name: p2
    termination_a_type: dcim.powerport
    termination_b:
      device: pdu1
      name: o35
    termination_b_type: dcim.poweroutlet
    type: power
```
