### ISSUE TITLE
[Bug]: netbox_virtual_chassis fails to query by master

### ISSUE THREAD

**Issue by shaderecker** [netbox-community/ansible_modules#1292]
### Ansible NetBox Collection version

3.19.1

### Ansible version

```bash
ansible [core 2.17.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/netbox-test/.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/netbox-test/.venv/bin/ansible
  python version = 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] (/home/ubuntu/netbox-test/.venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### NetBox version

v4.0.6

### Python version

3.10

### Steps to Reproduce

I want to rename a chassis and therefore cannot use the name parameter to search for it.
I set `query_params` to "master".

Playbook file:
```
- name: Rename network devices
  hosts: localhost
  gather_facts: false
  vars:
    netbox_uri: '{{ lookup("env", "NETBOX_API") }}'
    netbox_token: '{{ lookup("env", "NETBOX_TOKEN") }}'

  tasks:
    - name: "Update virtual chassis name in Netbox"
      netbox.netbox.netbox_virtual_chassis:
        netbox_url: "{{ netbox_uri }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "chassisname"
          master: "mastername"
        query_params:
          - master
```

### Expected Behavior

The existing virtual chassis is queried by the master parameter and updated to the new name.

### Observed Behavior

Fails with this error:
```
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_virtual_chassis_payload_79usucxd/ansible_netbox.netbox.netbox_virtual_chassis_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 795, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/home/ubuntu/netbox-test/.venv/lib/python3.10/site-packages/pynetbox/core/endpoint.py", line 162, in get
    ret = next(resp, None)
  File "/home/ubuntu/netbox-test/.venv/lib/python3.10/site-packages/pynetbox/core/response.py", line 128, in __next__
    next(self.response), self.endpoint.api, self.endpoint
  File "/home/ubuntu/netbox-test/.venv/lib/python3.10/site-packages/pynetbox/core/query.py", line 292, in get
    req = self._make_call(add_params=add_params)
  File "/home/ubuntu/netbox-test/.venv/lib/python3.10/site-packages/pynetbox/core/query.py", line 259, in _make_call
    raise RequestError(req)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "comments": null,
                "custom_fields": null,
                "description": null,
                "domain": null,
                "master": "mastername",
                "name": "chassisname",
                "tags": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "<redacted>",
            "query_params": [
                "master"
            ],
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "{\"master\":[\"Select a valid choice. 193 is not one of the available choices.\"]}"
}
```

So it converts the master name into its id (192) but then fails to work with that.
