### ISSUE TITLE
[Docs]: Mistake in comments for query_filters

### ISSUE THREAD

**Issue by kiltum** [netbox-community/ansible_modules#1321]
### Change Type

Correction

### Area

Configuration parameters

### Proposed Changes

Look at https://docs.ansible.com/ansible/latest/collections/netbox/netbox/nb_inventory_inventory.html, 
```
query_filters:
  - role: server
  - tag: web
  - tag: production

# See the NetBox documentation at https://netbox.readthedocs.io/en/stable/rest-api/overview/
# the query_filters work as a logical **OR**
#
```

But in this example they work as logical AND and will select devices, that has role server AND tag web AND tag production. But if I add 
```
- status: active
- status: provisioning
```
They will use OR 

Look like need more deep explain in plugin documentation, when rule OR applies, and when AND. Now looks like for `role` and `tag` always applies AND, and for other fields OR
