### ISSUE TITLE
[Bug]: netbox_ip_address not able to add the interface id through Ansible Variable

### ISSUE THREAD

**Issue by ebourgess** [netbox-community/ansible_modules#1326]
### Ansible NetBox Collection version

v3.20.0

### Ansible version

```bash
ansible [core 2.15.12]
  config file = /Users/ebourgess/dev/netbox-ansible-sync-test/ansible.cfg
  configured module search path = ['/Users/ebourgess/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ebourgess/dev/netbox-ansible-sync-test/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/ebourgess/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/ebourgess/dev/netbox-ansible-sync-test/bin/ansible
  python version = 3.9.6 (default, Aug  9 2024, 14:24:13) [Clang 16.0.0 (clang-1600.0.26.3)] (/Users/ebourgess/dev/netbox-ansible-sync-test/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### NetBox version

v4.1.1

### Python version

3.9

### Steps to Reproduce

Created an interface and then tried to use the id to add it to a new IP address

```yaml
- name: Create a network interface for the VM
      netbox.netbox.netbox_vm_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          virtual_machine: "{{ vm_name }}"
          name: "{{ vm_interface_name }}"
      register: interface

- name: Assign IP address to the interface
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ ip_address }}"
          status: "{{ ip_status }}"
          interface: "{{ interface.interface.id }}"
      register: ip

```

### Expected Behavior

I am expecting it to link the IP address to the interface via the interface id. 

### Observed Behavior

This doesn't work as the output I am getting is 

```sh
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not resolve id of interface: 803"}
```

However, when I hardcode the value it works.
