### ISSUE TITLE
[Bug]: netbox_cable fails on circuits with multiple terminations

### ISSUE THREAD

**Issue by DustinWi** [netbox-community/ansible_modules#1328]
### Ansible NetBox Collection version

v3.19.1

### Ansible version

```bash
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/home/dustin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']        
  ansible python module location = /home/dustin/projects/netbox/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /home/dustin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dustin/projects/netbox/.venv/bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/home/dustin/projects/netbox/.venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True

```

### NetBox version

v4.0.11 netbox-enterprise

### Python version

3.11

### Steps to Reproduce

* Create a circuit
* Create "A" side termination for the circuit to a Site
* Create "Z" side termination for the circuit to a Provider Network
* Try to use use netbox_cable module to create a cable from a Device interface to circuit

Sample Playbook
```yaml
---
- name: ========================= SETUP NETBOX
  hosts: netbox
  gather_facts: no
  connection: local
  vars:
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}" 
  
  tasks:
    - name: ========================= CIRCUIT
      netbox.netbox.netbox_circuit:
        netbox_url: "https://{{ inventory_hostname }}"
        netbox_token: "{{ netbox_token }}"
        data:
          cid: Circuit1
          circuit_type: Residential ISP
          commit_rate: 200000
          description: ISP Connection
          provider: Breezeline
          status: Active
        validate_certs: no
        state: present
    - name: ========================= CIRCUIT TERMINATION WALL JACK
      netbox.netbox.netbox_circuit_termination:
        netbox_url: "https://{{ inventory_hostname }}"
        netbox_token: "{{ netbox_token }}"
        data: 
          circuit: Circuit1
          description: Patch Panel
          port_speed: 200000
          pp_info: Attic Wall jack
          site: Site1
          term_side: A
          upstream_speed: 20000
        validate_certs: no
        state: present
    - name: ========================= CIRCUIT TERMINATION PROVIDER NETWORK
      netbox.netbox.netbox_circuit_termination:
        netbox_url: "https://{{ inventory_hostname }}"
        netbox_token: "{{ netbox_token }}"
        data: 
          circuit: Circuit1
          description: ISP
          port_speed: 200000
          term_side: Z
          upstream_speed: 20000
          provider_network: Breezeline Residential
        validate_certs: no
        state: present
    - name: ========================= CIRCUIT TERMINATION CABLE TO DEVICE
      netbox.netbox.netbox_cable:
        netbox_url: "https://{{ inventory_hostname }}"
        netbox_token: "{{ netbox_token }}"
        data:
          description: Router 1 - Gi0/0/1
          type: cat5e
          status: connected
          termination_a_type: dcim.interface
          termination_a:
            device: Router 1
            name: GigabitEthernet0/0/1
          termination_b_type: circuits.circuittermination
          termination_b:
            circuit: Circuit1
        validate_certs: no
        state: present

```

### Expected Behavior

All tasks complete OK or CHANGED and a cable is created in Netbox.

### Observed Behavior

Results
```bash
PLAY [========================= SETUP NETBOX ] ******************************************************************************************************************

TASK [========================= CIRCUIT ] ***********************************************************************************************************************
ok: [netbox.nosc.us.baesystems.com]

TASK [========================= CIRCUIT TERMINATION WALL JACK ] *************************************************************************************************
ok: [netbox.nosc.us.baesystems.com]

TASK [========================= CIRCUIT TERMINATION PROVIDER NETWORK ] ******************************************************************************************
ok: [netbox.nosc.us.baesystems.com]

TASK [========================= CIRCUIT TERMINATION CABLE TO DEVICE ] *******************************************************************************************
fatal: [netbox.nosc.us.baesystems.com]: FAILED! => {"changed": false, "msg": "More than one result returned for termination_b"}

PLAY RECAP *******************************************************************************************************************************************************************************
netbox.nosc.us.baesystems.com : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

Final task with verbosity enabled
```bash
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_cable_payload_kpl3s3dx/ansible_netbox.netbox.netbox_cable_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", l
ine 797, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dustin/projects/netbox/.venv/lib/python3.12/site-packages/pynetbox/core/endpoint.py", line 167, in get
    raise ValueError(
fatal: [netbox.nosc.us.baesystems.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "color": null,
                "comments": null,
                "custom_fields": null,
                "description": "Router 1 - Gi0/0/1",
                "label": null,
                "length": null,
                "length_unit": null,
                "status": "connected",
                "tags": null,
                "tenant": null,
                "termination_a": {
                    "device": "Router 1",
                    "name": "GigabitEthernet0/0/1"
                },
                "termination_a_type": "dcim.interface",
                "termination_b": {
                    "circuit": "Circuit1"
                },
                "termination_b_type": "circuits.circuittermination",
                "type": "cat5e"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.nosc.us.baesystems.com",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "More than one result returned for termination_b"
}
```
