### ISSUE TITLE
Calling netbox_ip_address for multiple hosts in rapid succession to get free IPs results in duplicate IPs

### ISSUE THREAD

**Issue by rayterrill** [netbox-community/ansible_modules#133]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

```
ansible 2.9.5
  config file = /home/popnimda/cisco/ansible.cfg
  configured module search path = ['/home/popnimda/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

###### Netbox:

v2.6.3

###### Collection:

netbox.netbox:0.1.10

##### SUMMARY

Running an ansible playbook that attempts to grab free IPs with netbox_ip_address assigns multiple machines the same IP address (i.e. host1 and host2 both get 192.168.2.1).

##### STEPS TO REPRODUCE

#production.ini
```
[test]
testvm1
testvm2
```

#host_vars/test1.yml
```
vm_name: "TEST1"
```

#host_vars/test2.yml
```
vm_name: "TEST2"
```

#test.yml playbook
```
---
- hosts: test
  gather_facts: False
  collections:
    - netbox.netbox
  tasks:
  - name: Create device
    netbox_device:
      netbox_url: https://netbox.portofportland.com
      netbox_token: "{{ netbox_token }}"
      validate_certs: no
      data:
        name: "{{ vm_name }}"
        site: HQ
        device_role: app-server
        device_type: vm
    delegate_to: localhost
  - name: Create interface within Netbox with only required information
    netbox_interface:
      netbox_url: https://netbox.portofportland.com
      netbox_token: "{{ netbox_token }}"
      validate_certs: no
      data:
        device: "{{ vm_name }}"
        name: "Network Adapter 1"
      state: present
    delegate_to: localhost
  - name: Get IP Address from Netbox
    netbox_ip_address:
      netbox_url: https://netbox.portofportland.com
      netbox_token: "{{ netbox_token }}"
      validate_certs: no
      data:
        prefix: "{{ netboxparam_prefix }}"
        dns_name: "{{ vm_name }}.{{ netboxparam_dnssuffix }}"
        interface:
          name: "Network Adapter 1"
          device: "{{ vm_name }}"
      state: present
    delegate_to: localhost
```

```yaml

```

##### EXPECTED RESULTS

Create separate devices, interfaces, and IP addresses for the two hosts

##### ACTUAL RESULTS

Creates separate devices and interfaces for the two hosts, but assigns the same IP address for both hosts.

```

```
