### ISSUE TITLE
[Bug]: pynetbox Module Not Detected for netbox.netbox.lookup Plugin in AWX

### ISSUE THREAD

**Issue by Superset1986** [netbox-community/ansible_modules#1330]
### Ansible NetBox Collection version

v3.20.0

### Ansible version

ansible [core 2.15.12]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.19 (main, Jun 11 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True

### NetBox version

v4.0.6

### Python version

3.9

### Steps to Reproduce

I am encountering an issue with the netbox.netbox.lookup plugin while running playbooks in AWX. The error message indicates that the pynetbox module is not installed, even though pynetbox is installed and visible when running pip list. Interestingly, other NetBox-related modules, such as netbox.netbox.netbox_vm_interface, works without any issues.    

I tried logging into the execution environment while the container was running and running python -c "import pynetbox" without errors.  I also did a pip list to confirm pynetbox was installed.  

First step of my playbook is to install pynetbox into the execution environment:

```yaml
    - name: pip install pynetbox
      shell: pip install plugins/pynetbox-7.4.0-py3-none-any.whl
      register: raw_output
      delegate_to: localhost
      run_once: true
``` 

Playbook task that is failing:
```yaml
    - name: "Query NetBox for all sites"
      debug:
        msg: >
          "Device {{ item.value.name }} (ID: {{ item.key }}) was
          manufactured by {{ item.value.device_type.manufacturer.name }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices', api_filter='role=firewall', api_endpoint=netbox_url, token=netbox_token)}}"
```

Playbook task that is working: 

```yaml
    - name: Create or update VM in Netbox
      netbox.netbox.netbox_vm_interface:
        netbox_token: '{{ NETBOX_TOKEN }}'
        netbox_url: '{{ NETBOX_API }}'
        data:
          virtual_machine: "{{ inventory_hostname }}"
          name: "{{ item[0] }}"
        state: present
        validate_certs: False
      loop: "{{ interfaces_data }}"
      delegate_to: localhost
```

### Expected Behavior

The netbox.netbox.lookup plugin should successfully detect the pynetbox module, and the playbook should execute without errors like the netbox.netbox.netbox_vm_interface module. 

### Observed Behavior

Task is failing with the following error: 
fatal: [localhost]: FAILED! => {"msg": "The pynetbox python module is required"}

**Comment by mstefany** [comment]
I was able to track this down and resolve it using Claude's (Sonnet 5) help. I don't think that it's netbox's bug, just a way different python3 versions collide in the execution environment.

My final working setup is as follows. Assuming you have standard repository structure of:
```
ansible/
  collections/
  execution-environments/
    ee-default-rhel9/
      bindep.txt
      execution-environment.yaml
      requirements.txt
      requirements.yaml
  inventories/
  playbooks/
  roles/
  rulebooks/
  ansible-navigator.yaml
  ansible.cfg
  README.md
```

and you have some role and/or playbook using `netbox.netbox` collection (and other collections) and also `netbox.netbox.nb_lookup` plugin, then your `execution-environment.yaml` should look something like:

```
---
version: 3

dependencies:
  galaxy: requirements.yaml
  python: requirements.txt
  python_interpreter:  # valid in ansible-automation-platform-26/ee-minimal-rhel9 images
    package_system: "python3.12"
    python_path: "/usr/bin/python3.12"
  system: bindep.txt

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:2.0-1782726413

# Custom package manager path for the RHEL based images
options:
  package_manager_path: /usr/bin/microdnf
...
```

where setting `dependencies.python_interpreter.package_system` and `dependencies.python_interpreter.python_path` to point to right python3 version is the important part.

`requirements.txt` can look like:

```
pynetbox
```

`requirements.yaml` can look like:

```
---
collections:
  - name: netbox.netbox
```

and, crucially, your ansible.cfg needs to look like:

```
[defaults]
interpreter_python = /usr/bin/python3.12
roles_path = roles
...
```

where setting `interpreter_python` is the important part.


Without these little tweaks, collections' requirements and other pip3 packages would be installed into `/usr/local/lib/python3.9/site-packages` while running `ansible-playbook --version` inside execution environment would search in `/usr/local/lib/python3.12/site-packages`.
