### ISSUE TITLE
[Bug]: netbox.netbox.netbox_fhrp_group doesn't support all field (at least name isn't supported)

### ISSUE THREAD

**Issue by SteveRodrigue** [netbox-community/ansible_modules#1339]
### Ansible NetBox Collection version

v3.20.0

### Ansible version

```bash
ansible [core 2.15.6]
  config file = /home/srodrigue3/projects/nina/ansible.cfg
  configured module search path = ['/home/srodrigue3/projects/nina/modules']
  ansible python module location = /home/srodrigue3/projects/nina/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/srodrigue3/projects/nina/collections:/home/srodrigue3/projects/nina/nina_venv/lib/python3.9/site-packages
  executable location = /home/srodrigue3/projects/nina/.venv/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/home/srodrigue3/projects/nina/.venv/bin/python)
  jinja version = 3.1.4
  libyaml = True

```

### NetBox version

v4.1.1

### Python version

3.9

### Steps to Reproduce

Simple, try something like this:

We should be able to specify the name in data:

```
- name: "Create FHRP group in Netbox"
  netbox.netbox.netbox_fhrp_group:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    data:
      name: "Not supported"  # Not supported!
      protocol: "other"
      group_id: 111
    state: present
```

### Expected Behavior

Group is created with a name.

### Observed Behavior

The Ansible task fails with this message.

```    msg: 'Unsupported parameters for (netbox.netbox.netbox_fhrp_group) module: data.name.
        Supported parameters include: auth_key, auth_type, custom_fields, description,
        group_id, protocol, tags.'```
