### ISSUE TITLE
[Bug]: There are not enough options for FHRP Group to work

### ISSUE THREAD

**Issue by Hramoff** [netbox-community/ansible_modules#1349]
### Ansible NetBox Collection version

v3.20.0

### Ansible version

```
ansible [core 2.15.6]
  config file = /home/hramov-ms-230320/Desktop/Ansible-2/ansible.cfg
  configured module search path = ['/home/hramov-ms-230320/Desktop/Ansible-2/modules']
  ansible python module location = /home/hramov-ms-230320/Desktop/Ansible-2/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/hramov-ms-230320/Desktop/Ansible-2/collections
  executable location = /home/hramov-ms-230320/Desktop/Ansible-2/.venv/bin/ansible
  python version = 3.11.6 (main, Oct 31 2023, 14:31:13) [GCC 12.2.0] (/home/hramov-ms-230320/Desktop/Ansible-2/.venv/bin/python3.11)
  jinja version = 3.1.1
  libyaml = False
```

### NetBox version

v4.0.11

### Python version

3.11

### Steps to Reproduce

```yaml
- name: Add VIP host into NetBox
  netbox.netbox.netbox_ip_address:
    data:
      **fhrpgroup:  NOT SUPPORTED**
    state: present
  delegate_to: localhost
      
```

```yaml
- name: "Create FHRP group within netbox"
  netbox.netbox.netbox_fhrp_group:
    data:
      **ip_address: NOT SUP**
      **ip_status: NOT SUP**
    state: present
 ```

### Expected Behavior

1. When creating an address in ipam, you need to manage it in the FHRP group
2. In the web interface, when creating an FHRP group, you can specify its address and status, this is not available in the module

### Observed Behavior

not supported
