### ISSUE TITLE
[Bug]: Could not resolve id of virtual_chassis

### ISSUE THREAD

**Issue by jefvantongerloo** [netbox-community/ansible_modules#1364]
### Ansible NetBox Collection version

v3.20.0

### Ansible version

```bash
ansible [core 2.18.1]
  python version = 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
  jinja version = 3.1.5
  libyaml = True
```

### NetBox version

v4.1.7

### Python version

3.11

### Steps to Reproduce

Add existing device to existing VC:
```
    - name: NETBOX >> Add devices to Virtual chassis
      netbox.netbox.netbox_device:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: '{{ inventory_hostname + "-" + chassis.unit | string }}'
          virtual_chassis:
            name: '{{ inventory_hostname }}'
            master: "{{ inventory_hostname + '-1' }}"
          vc_position: '{{ chassis.unit | string }}'
        state: present
      loop: '{{ device_chassis }}'
      loop_control:
        loop_var: chassis
```

### Expected Behavior

Units added to VC:
![image](https://github.com/user-attachments/assets/69314f9f-9ec0-4663-bee1-532ed07786a4)

### Observed Behavior

```
failed: [net-swi-0001] (item={'type': '<snip>', 'status': 'planned', 'unit': 4}) => {
    "ansible_loop_var": "chassis",
    "changed": false,
    "chassis": {
        "status": "planned",
        "type": "<snip>",
        "unit": 4
    },
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "airflow": null,
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "config_template": null,
                "custom_fields": null,
                "description": null,
                "device_role": null,
                "device_type": null,
                "face": null,
                "local_context_data": null,
                "location": null,
                "name": "net--swi-0001-4",
                "oob_ip": null,
                "platform": null,
                "position": null,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": null,
                "serial": null,
                "site": null,
                "status": null,
                "tags": null,
                "tenant": null,
                "vc_position": 4,
                "vc_priority": null,
                "virtual_chassis": {
                    "master": "net-swi-0001-1",
                    "name": "net-swi-0001"
                }
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "<snip>",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "Could not resolve id of virtual_chassis: {'name': 'net-swi-0001', 'master': 'net-swi-0001-1'}"
```

**Comment by jefvantongerloo** [comment]
Tested on version 3.22 and the issue is still present. This blocks adding devices to a virtual chassis, because the virtual chassis could not be resolved given the correct `master` and `name` attributes.

**Comment by theherox** [comment]
I ran into an issue which seems to be related close enough to this one that it doesn't warrant a brand new bug, so I'll post my workaround.  @jefvantongerloo I believe this will fix what you're trying to do as well.

In my particular case, I was having an idempotency issue when using the following 3-task process:
1. Create a new Virtual Chassis without any members with netbox_virtual_chassis
2. Create new devices and assign them to the VC with netbox_device
3. Assign a device as the VC master

Tasks 1 & 2 complete successfully, and then in Step 3, a new/duplicate VC is created and the device I'm trying to assign as master is removed from the original VC and added to the new/duplicate VC and set as master.  Subsequent runs fail because the search for the VC returns duplicate entries.

As for the workaround, provide the `query_params` parameter and specify `name` as the only query parameter so it only matches on the VC name instead of having to match `name` & `master`.

```
- name: Assign Virtual Chassis
  netbox.netbox.netbox_virtual_chassis:
    data:
      name: "{{ item.name }}"
      master: "{{ item.master }}"
    query_params:
      - name
  loop: "{{ virtual_chassis_data }}"
```

The fix to avoid this would be in `plugins/module_utils/netbox_utils.py` and change line [596](https://github.com/netbox-community/ansible_modules/blob/9701fa31b11e83ff568b2c614e07e282856c6764/plugins/module_utils/netbox_utils.py#L596) from `"virtual_chassis": set(["name", "master"]),` to `"virtual_chassis": set(["name"]),` which would make virtual chassis ONLY match on `name` by default but I'm unsure if there would be any adverse affects from that.
