### ISSUE TITLE
[Bug]:  netbox_vm_interface module doesn't accept mac_address anymore

### ISSUE THREAD

**Issue by rletocart** [netbox-community/ansible_modules#1376]
### Ansible NetBox Collection version

v3.19.1

### Ansible version

```bash
ansible [core 2.17.1]
  config file = /Users/raph/dev/ansible/netbox/ansible.cfg
  configured module search path = ['/Users/raph/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/raph/dev/ansible/netbox/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/raph/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/raph/dev/ansible/netbox/bin/ansible
  python version = 3.12.8 (main, Dec  3 2024, 18:42:41) [Clang 16.0.0 (clang-1600.0.26.4)] (/Users/raph/dev/ansible/netbox/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### NetBox version

v4.2.2

### Python version

3.11

### Steps to Reproduce

```yaml
- name: "ADD VM INTERFACES TO NETBOX"
  netbox.netbox.netbox_vm_interface:
    netbox_url: "{{ NETBOX_ENDPOINT }}"
    netbox_token: "{{ NETBOX_TOKEN }}"
    data:
      virtual_machine: "{{ inventory_hostname }}"
      name: "{{ item  }}"
      enabled: "true"
      mac_address: "{{ ansible_facts[item].macaddress | ansible.utils.hwaddr | upper }}"
    state: present
  loop: "{{ ansible_interfaces | list }}"
```

### Expected Behavior

Virtual machine net interfaces are created in netbox WITH a MAC address. This was working before v4.2.1

### Observed Behavior

MAC address seems simply ignored. I didn't get any error in ansible.
