### ISSUE TITLE
Remove or provide option to NOT append the "group_by" group name to inventory groups

### ISSUE THREAD

**Issue by smolz** [netbox-community/ansible_modules#138]
##### ISSUE TYPE

 - Feature Idea

##### SOFTWARE VERSIONS
all
###### Ansible:

all
###### Netbox:

all
###### Collection:

all
##### SUMMARY

When using the inventory plugin and specifically the `group_by` option the group_by name is prepended to the groups that are created for Ansible.  If I have device that has a role of branch_switch and I am grouping by `device_role`, in ansible the group is now `device_role_branch_switch` and now all of my group_vars have to be renamed to support this.
##### STEPS TO REPRODUCE

Instead of the inventory group names having the group_by prepended it would omit those.

```yaml
---
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox
token: TOKEN
validate_certs: True
config_context: True
group_by:
  - sites
  - device_roles
```

##### EXPECTED RESULTS

I would expect that if I group by `device_roles`, or any other option, I would just get the name (i.e. `branch_switch`)
##### ACTUAL RESULTS

What I get is the groups have the group_by variable prepended to groups `device_role_branch_switch`

```

```
