### ISSUE TITLE
[Bug]: Device Interface Module - Device query brings back more than one device

### ISSUE THREAD

**Issue by aoforb** [netbox-community/ansible_modules#1397]
### Ansible NetBox Collection version

3.20.0

### Ansible version

```bash
  ansible [core 2.17.3]
  python version = 3.12.3
  jinja version = 3.1.5
  libyaml = True
```

### NetBox version

4.1.4

### Python version

3.12

### Steps to Reproduce

1. Create a VC named
foo-switch

2. Add two devices to the VC
foo-switch(1)
foo-switch(2)

3. Make sure both devices have the same interface 'GigabitEthernet1/0/1', as per 9300 switch template

```
    - name: Test
      netbox.netbox.netbox_device_interface:
        netbox_url: https://netbox.fooooo
        netbox_token: "1234"
        data: {'name': 'GigabitEthernet1/0/1', 'device': 'foo-switch(1)', 'type': '1000base-t', 'description': 'fooo', 'enabled': True, 'mtu': 1500, 'mode': 'access'}
        state: present
```

Run task

### Expected Behavior

Return the correct interface for the given device, instead it returns all the members.

### Observed Behavior

![Image](https://github.com/user-attachments/assets/1a7ba8da-a30f-4c9a-960a-4880ba54ba8c)

Problematic code.
File: `ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py`
Lines: Around line 1000

Snip:
```
                elif (
                    parent == "interface"
                    and "device" in module_data
                    and self._version_check_greater(
                        self.version, "3.6", greater_or_equal=True
                    )
                ):
                    query_dict.update(
                        {"virtual_chassis_member_id": module_data["device"]}
                    )
                else:
                    query_dict.update({match + "_id": query_id})
```

Logic is to use `virtual_chassis_member_id` instead of `device_id`, if I comment out.
```
                    query_dict.update(
                        {"virtual_chassis_member_id": module_data["device"]}
                    )
```

It then works fine.

You can also test the same behaviour on the NetBox Rest API UI, using the `virtual_chassis_member_id` will always bring back more than one device.
