### ISSUE TITLE
[Bug]: netbox_circuit_termination fails with "A circuit termination must attach to a terminating object."

### ISSUE THREAD

**Issue by nsthompson** [netbox-community/ansible_modules#1401]
### Ansible NetBox Collection version

v3.21.0

### Ansible version

```bash
ansible [core 2.18.3]
  config file = None
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.13/site-packages/ansible
  ansible collection location = /home/vscode/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.13.2 (main, Feb 25 2025, 05:25:21) [GCC 12.2.0] (/usr/local/bin/python3.13)
  jinja version = 3.1.6
  libyaml = True
```

### NetBox version

v4.2.5

### Python version

3.11

### Steps to Reproduce

The tasks I am running look like this:

```yaml
- name: Configure A-side Circuit Terminations for Circuit {{ circuit.data.id }} from {{ circuit.data.provider }}
  netbox.netbox.netbox_circuit_termination:
    data:
      circuit: "{{ circuit.data.id }}"
      description: "{{ circuit.terminations.a.description | default(omit) }}"
      mark_connected: "{{ circuit.terminations.a.mark_connected | default(omit) }}"
      port_speed: "{{ circuit.terminations.a.port_speed | default(omit) }}"
      pp_info: "{{ circuit.terminations.a.pp_info | default(omit) }}"
      provider_network: "{{ circuit.terminations.a.provider | default(omit) }}"
      site: "{{ circuit.terminations.a.site | default(omit) }}"
      term_side: A
      upstream_speed: "{{ circuit.terminations.a.upstream_speed | default(omit) }}"
      xconnect_id: "{{ circuit.terminations.a.xconnect_id | default(omit) }}"
    state: "{{ circuit.terminations.a.state }}"
  when: circuit.terminations.a is defined

- name: Configure Z-side Circuit Terminations for Circuit {{ circuit.data.id }} from {{ circuit.data.provider }}
  netbox.netbox.netbox_circuit_termination:
    data:
      circuit: "{{ circuit.data.id }}"
      description: "{{ circuit.terminations.z.description | default(omit) }}"
      mark_connected: "{{ circuit.terminations.z.mark_connected | default(omit) }}"
      port_speed: "{{ circuit.terminations.z.port_speed | default(omit) }}"
      pp_info: "{{ circuit.terminations.z.pp_info | default(omit) }}"
      provider_network: "{{ circuit.terminations.z.provider | default(omit) }}"
      site: "{{ circuit.terminations.z.site | default(omit) }}"
      term_side: Z
      upstream_speed: "{{ circuit.terminations.z.upstream_speed | default(omit) }}"
      xconnect_id: "{{ circuit.terminations.z.xconnect_id | default(omit) }}"
    state: "{{ circuit.terminations.z.state }}"
  when: circuit.terminations.z is defined
```

My sample data:

```yaml
---
circuits:
  - data:
      id: 12345abcde
      type: corporate-wan
      provider: wwt
      description: "Circuit from US-MN-MSP-01 to US-MO-STL-60"
      status: active
    terminations:
      a:
        description: US-MN-MSP-01 Termination
        connected: false
        site: us-mn-msp-01
        state: present
      z:
        description: US-MO-STL-60 Termination
        connected: false
        site: us-mo-stl-60
        state: present
    state: present
```

### Expected Behavior

The expected behavior is that the circuit terminations are created.

### Observed Behavior

When using netbox.netbox.netbox_circuit_termination using the old key of 'site' the module fails and throws the error `A circuit termination must attach to a terminating object.`

This appears to be tied to the following breaking change in the [NetBox 4.2 release notes](https://github.com/netbox-community/netbox/releases/tag/v4.2.0):

`The site and provider_network foreign key fields on circuits.CircuitTermination have been replaced by the termination generic foreign key.`
