### ISSUE TITLE
Inventory bug: services queried by device name doesn't work for VMs, or names with spaces

### ISSUE THREAD

**Issue by DouglasHeriot** [netbox-community/ansible_modules#142]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.9.6

##### Netbox:

2.7.10

###### Collection:

0.10.1

##### SUMMARY

There are a few issues here: When the inventory queries the Netbox API for a list of services:
* It passes the device name instead of an ID
* If this device name has spaces, it is not cached properly and a warning appears
* If the host is a VM and not a device, then the list of services is not fetched as it's hard-coded to always query by device name and not VM name/ID.

I plan to work on fixing this, by always querying for list of services by ID, and properly constructing the URL for either device or VM query.

##### STEPS TO REPRODUCE

Here is my inventory yaml file:

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox
config_context: True

cache: True
cache_timeout: 3600
cache_plugin: jsonfile
cache_connection: /tmp/inventory_netbox

interfaces: False

group_by:
  - sites
  - tenants
  - racks
  - tags
  - device_roles
  - device_types
  - manufacturers
  - platforms

query_filters:
  - has_primary_ip: 'true'
```

##### EXPECTED RESULTS

* No warnings
* Services returned for both devices and VMs

##### ACTUAL RESULTS

```
[WARNING]: error in 'jsonfile' cache plugin while trying to read /tmp/inventory_netbox/netbox.netbox.nb_inventory_d46c3s_4f124 : b"[Errno
2] No such file or directory: '/tmp/inventory_netbox/netbox.netbox.nb_inventory_d46c3s_4f124'"
Fetching: https://netbox/api/ipam/services/?device=IMAG VMU
```
