### ISSUE TITLE
netbox_ip_address changing status does not work when using prefix

### ISSUE THREAD

**Issue by TerraTalpi** [netbox-community/ansible_modules#146]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]

###### Netbox:
netbox (v2.7.10)

###### Collection:
netbox-community/ansible_modules is version  v0.1.10
Installed pynetbox: 4.3.0

##### SUMMARY
When I create a new IP address with the netbox_ip_address module and only setting a prefix everything works and `status` is honored. However if I apply the same state again with a different `status` the status in netobox does not change, nor does ansible recognize that something is different an marks it with no change/green.

##### STEPS TO REPRODUCE
Please edit the three variables in the playbook to match your setup. Please set the `targetdevice` to an already existing device, otherwise the playbook below would greatly enlarge to create all necessary data for a simple dummy test device.

```yaml
- name: "Create prefix and assign IP from prefix"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox
  vars:
    netbox_url: http://netbox.local
    netbox_token: mysupercooltoken
    targetdevice: "testdevice"
  tasks:
    - name: "Create interface on {{ targetdevice }}"
      netbox_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ targetdevice }}"
          type: virtual
          name: "ipprefixtest"
    - name: "Create new Prefix for testing"
      netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "192.168.0.0/24"
          status: Active
    - name: "Add new IP Address from prefix 192.168.0.0/24 with state Reserved"
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "192.168.0.0/24"
          interface:
            device: "{{ targetdevice }}"
            name: "ipprefixtest"
          status: "Reserved"
    - name: "Now change the IP addr in prefix 192.168.0.0/24 to Active"
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "192.168.0.0/24"
          interface:
            device: "{{ targetdevice }}"
            name: "ipprefixtest"
          status: "Active"
```
The ansible-playbook output with --vvvv shows this [output greatly omitted, only the last task is shown:
```yaml
TASK [Now change the IP addr in prefix 192.168.0.0/24 to Active] ***************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "address": null,
                "custom_fields": null,
                "description": null,
                "dns_name": null,
                "family": null,
                "interface": {
                    "device": "testdevice",
                    "name": "ipprefixtest"
                },
                "nat_inside": null,
                "prefix": "192.168.0.0/24",
                "role": null,
                "status": "Active",
                "tags": null,
                "tenant": null,
                "vrf": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://netbox.pbx.unido.org",
            "state": "present",
            "validate_certs": true
        }
    },
    "ip_address": {
        "address": "192.168.0.1/30",
        "created": "2020-03-29",
        "custom_fields": {},
        "description": "",
        "dns_name": "",
        "family": 4,
        "id": 2092,
        "interface": 6957,
        "last_updated": "2020-03-29T17:33:43.603078Z",
        "nat_inside": null,
        "nat_outside": null,
        "role": null,
        "status": "reserved",
        "tags": [],
        "tenant": null,
        "vrf": null
    },
    "msg": "ip_address 192.168.0.1/30 already attached"
}
```

##### EXPECTED RESULTS
That the device `{{ targetdevice }}` has an IP-Address assigned to interface `ipprefixtest` with status `Active`.

##### ACTUAL RESULTS
The device `{{ targetdevice }}` has an IP-Address assigned to interface `ipprefixtest` with status `Reserved`.
