### ISSUE TITLE
netbox_device_interface error using 'mode'.

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/ansible_modules#158]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
[tdavis@mouse-r11 netbox]$ ansible --version
ansible 2.9.6
  config file = /home/tdavis/netbox/ansible.cfg
  configured module search path = ['/home/tdavis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tdavis/.local/lib/python3.6/site-packages/ansible
  executable location = /home/tdavis/.local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
###### Netbox:

v2.7.11

###### Collection:

github  head installed.
##### SUMMARY

Tagged All vs. Tagged (All)

##### STEPS TO REPRODUCE
```
    - name: create real interfaces
      netbox_device_interface:
        netbox_url: "{{ endpoint }}"
        netbox_token: "{{ token }}"
        data:
          device: "{{ ansible_hostname }}"
          name: "{{ item.name }}"
          form_factor: "{{ item.form_factor }}"
          tags: "{{ item.tags }}"
          mode: "Tagged All"
          mtu: "{{ item.mtu | default(1514) }}"
      loop: "{{ interfaces }}"

```

##### EXPECTED RESULTS

succeded.

##### ACTUAL RESULTS

```
failed: [mouse-r12] (item={'name': 'enp2s0', 'form_factor': '1000BASE-T (1GE)', 'tags': ['ovsbridge:br-external'], 'mtu': 9216}) => {"ansible_loop_var": "item", "changed": false, "item": {"form_factor": "1000BASE-T (1GE)", "mtu": 9216, "name": "enp2s0", "tags": ["ovsbridge:br-external"]}, "msg": "Tagged All was not found as a valid choice for interfaces"}
```

Looking at the _choices API, it should be 'Tagged (All)', not 'Tagged All'.  This affects netbox_vm_interface, netbox_device_interface, and netbox_interface.
