### ISSUE TITLE
netbox_device/netbox_device_interface are not idempotent

### ISSUE THREAD

**Issue by ignatenkobrain** [netbox-community/ansible_modules#165]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/brain/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 28 2020, 00:00:00) [GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)]
```

###### Netbox:
`7f4fb69ef8a1 (v2.7.8)`

###### Collection:
`0.1.10`

##### SUMMARY
`netbox_device` is not idempotent in regard of `Status`. It seems to compare ID with text.

##### STEPS TO REPRODUCE
```yaml
    - netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ hostname }}"
          device_type: Gen10 Compute
          device_role: Shared Zone
          serial: "{{ sn | upper }}"
          site: "{{ dc | upper}}"
          status: Inventory
```

##### EXPECTED RESULTS
`changed: false`

##### ACTUAL RESULTS
```json
changed: [localhost] => {
    "changed": true,
    "device": {
        "asset_tag": null,
        "cluster": null,
        "comments": "",
        "config_context": {},
        "created": "2020-04-07",
        "custom_fields": {},
        "device_role": 9,
        "device_type": 11,
        "display_name": "cmp0005.nax.pcigdc.com",
        "face": null,
        "id": 228,
        "last_updated": "2020-04-07T08:41:21.133697Z",
        "local_context_data": null,
        "name": "cmp0005.nax.pcigdc.com",
        "parent_device": null,
        "platform": null,
        "position": null,
        "primary_ip": null,
        "primary_ip4": null,
        "primary_ip6": null,
        "rack": null,
        "serial": "MXQ7140CHN",
        "site": 15,
        "status": "inventory",
        "tags": [],
        "tenant": null,
        "vc_position": null,
        "vc_priority": null,
        "virtual_chassis": null
    },
    "diff": {
        "after": {
            "status": "inventory"
        },
        "before": {
            "status": 5
        }
    },
    "invocation": {
        "module_args": {
            "data": {
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "custom_fields": null,
                "device_role": "Shared Zone",
                "device_type": "Gen10 Compute",
                "face": null,
                "name": "cmp0005.nax.pcigdc.com",
                "platform": null,
                "position": null,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": null,
                "serial": "MXQ7140CHN",
                "site": "NAX",
                "status": "Inventory",
                "tags": null,
                "tenant": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://ipam.na1.pcigdc.com",
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "device cmp0005.nax.pcigdc.com updated"
}
```
