### ISSUE TITLE
DCIM/Rack: width is changed on every run

### ISSUE THREAD

**Issue by toerb** [netbox-community/ansible_modules#167]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.6

###### Netbox:
2.7.11

###### Collection:
devel

##### SUMMARY
The value for the rack width was wrongly documented as str, while it should be int.
See https://github.com/netbox-community/netbox/issues/4274 for more details.
Because of the wrong documentation the rack width is expected as str in the `netbox_rack` module.

This leads to constant changes on rack objects with explicitly defined rack width on every run.

##### STEPS TO REPRODUCE
Run the following playbook twice:
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - netbox.netbox
  tasks:
  - name: Create Rack(s)
    netbox_rack:
      netbox_url:
      netbox_token:
      data:
        name: Test Rack
        site: Test Site
        width: 19
        status: Planned
      state: present
```

##### EXPECTED RESULTS
First run creates the rack.
Second run says OK and does not change anything.

##### ACTUAL RESULTS
First run creates the rack.
Second run changes the rack width from 19 to "19".
```
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "width": 19
+    "width": "19"
 }
```
