### ISSUE TITLE
Bug: netbox_virtual_machine is missing custom_fields

### ISSUE THREAD

**Issue by pugnacity** [netbox-community/ansible_modules#170]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
2.9.4

###### Netbox:
2.6.11

###### Collection:
v0.1.10

##### SUMMARY
Adding virtual machines with custom fields is not working 

##### STEPS TO REPRODUCE

```yaml
- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox

  tasks:
    - name: Create device within Netbox with only required information
      netbox_virtual_machine:
        netbox_url: http://netbox.tld
        netbox_token: 12345t6
        data:
          name: test100-vm
          cluster: Test Cluster
          custom_fields:
            works: False
        state: present
```

##### EXPECTED RESULTS
added VM with custom fields 

##### ACTUAL RESULTS

```
PLAY [Test Netbox modules] *********************************************************************************************************************************************************************************************************************************************************************************************

TASK [Create device within Netbox with only required information] ******************************************************************************************************************************************************************************************************************************************************
Wednesday 08 April 2020  16:43:58 +0200 (0:00:00.104)       0:00:00.104 *******
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

Unsupported parameters for (netbox_virtual_machine) module: custom_fields found in data. Supported parameters include: cluster, disk, memory, name, platform, primary_ip4, primary_ip6, rack, site, status, tags, tenant, vcpus, virtual_machine_role


PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Wednesday 08 April 2020  16:43:59 +0200 (0:00:01.032)       0:00:01.136 *******
```
