### ISSUE TITLE
nb_inventory - Lookup api key in OS env as option

### ISSUE THREAD

**Issue by jvanderaa** [netbox-community/ansible_modules#176]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:

Ansible 2.9.6

###### Netbox:

2.7.12 / 2.8

##### SUMMARY

Would like to have an option to define API token in environment variables instead of clear text in the yml config

##### STEPS TO REPRODUCE

Define nb_inventory plugin yml file

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: http://netbox03
validate_certs: false
config_context: false
token: <cleartext token>
group_by:
 - device_roles
 - platforms
compose:
  ansible_network_os: platform.slug
query_filters:
  - site: "mysite"
  - has_primary_ip: True
```

##### EXPECTED RESULTS

Would like to remove the token keyword, if missing lookup env

##### ACTUAL RESULTS

Failed to parse as unable to get to the NetBox data

```
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```
