### ISSUE TITLE
Netbox Inventory Feature Request

### ISSUE THREAD

**Issue by metabsd** [netbox-community/ansible_modules#179]
##### ISSUE TYPE
 - Feature Idea

###### Ansible:
2.9.5
###### Netbox:
2.7.11

###### Collection:
0.1.10

##### SUMMARY
When I use netbox.netbox.nb_inventory with or without group_by I noticed that the script makes a query in https: // domain / api / ipam / services /? Device = devicename for each device. I would like to know if I can deactivate this because we do not need this information. Thank you!

##### STEPS TO REPRODUCE
Running inventory

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: https://url
token: superdupertoken
validate_certs: False
config_context: False
query_filters:
  - role: dummy_role
```

##### EXPECTED RESULTS
Having the possibility of controlling certain requests according to our needs.

##### ACTUAL RESULTS
Several API requests not necessary.

Maybe this feature already exists. If so, I apologize in advance for my ignorance :P
I review the code and I don't see a way to do what I need. 
Thank you!
