### ISSUE TITLE
DCIM/Rack: new width of 21 inches for ETSI racks

### ISSUE THREAD

**Issue by toerb** [netbox-community/ansible_modules#189]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.6

###### Netbox:
2.8.1

###### Collection:
devel

##### SUMMARY
Netbox 2.8.1 introduced racks with the width of 21 inches.
https://github.com/netbox-community/netbox/releases/tag/v2.8.1

##### STEPS TO REPRODUCE
Run the following playbook:
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - netbox.netbox
  tasks:
  - name: Create Rack(s)
    netbox_rack:
      netbox_url:
      netbox_token:
      data:
        name: Test Rack
        site: Test Site
        width: 21
        status: Planned
      state: present
```

##### EXPECTED RESULTS
A new rack with 21 inches should be created.

##### ACTUAL RESULTS
The playbook fails since 21 inch racks are currently not allowed within ansible netbox collection.
