### ISSUE TITLE
netbox_interface fails due to "Multiple results found while searching for key: device"

### ISSUE THREAD

**Issue by lassizci** [netbox-community/ansible_modules#192]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.9.7

###### Netbox:

v2.7.11

###### Collection:

0.2.0

##### SUMMARY

`netbox_interface` finds multiple devices as the query doesn't seem to be exact.

##### STEPS TO REPRODUCE

Have devices worker1.mydomain.name and anotherworker1.mydomain.name in `devices` in Netbox.

```yaml
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  collections:
    - netbox.netbox
  vars_files:
    - vars/netbox/secrets.yml
  vars:
    netbox_url: https://netbox.mydomain
    devices: 
      - test1
      - test10

  tasks:
        
    - name: add devices
      netbox.netbox.netbox_device:
         netbox_url: "{{ netbox_url }}" 
         netbox_token: "{{ netbox_token }}" 
         data:
           name: "{{ item }}" 
           device_role: server
           device_type: generic
           site: testsite
      with_items: "{{ devices }}" 

    - name: add interfaces to devices
      netbox.netbox.netbox_interface:
         netbox_url: "{{ netbox_url }}" 
         netbox_token: "{{ netbox_token }}" 
         data:
           name: public
           device:  "{{ item }}" 
           type: "1000base-t"
      with_items: "{{ devices }}" 
```

##### EXPECTED RESULTS

Should add interface to test1

##### ACTUAL RESULTS

```
fatal: [test1]: FAILED! => changed=false 
  msg: 'Multiple results found while searching for key: device'
```

There's
```
"GET /api/dcim/devices/?q=test1 HTTP/1.1"
```

in the access_log. I guess the devices should rather be queried by `name`.
