### ISSUE TITLE
netbox_device_interface fails on a second run to form_factor

### ISSUE THREAD

**Issue by lassizci** [netbox-community/ansible_modules#193]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.9.7

###### Netbox:

v2.7.11

###### Collection:

0.2.0

##### SUMMARY

`netbox_device_interface` seems to fail every time after the initial interface creation due to `form_factor` missing in the existing data. I can't find such field from Netbox API. `netbox_interface` on the other hand specifies `type` instead of `form_factor`. Is this on purpose? I'm not sure I understood the difference, but tried this one instead, as I had [other issue]( https://github.com/netbox-community/ansible_modules/issues/192) with `netbox_interface`.

##### STEPS TO REPRODUCE

Run this task twice in a row

```yaml
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  collections:
    - netbox.netbox
  vars_files:
    - vars/netbox/secrets.yml
  vars:
    netbox_url: https://netbox.mydomain
   
  tasks:
    - name: add interface to device
      netbox.netbox.netbox_device_interface:
         netbox_url: "{{ netbox_url }}" 
         netbox_token: "{{ netbox_token }}" 
         data:
           name: public
           device:  test1 
           form_factor: "1000base-t"
```

##### EXPECTED RESULTS

Should succeed on both runs
##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_device_interface_payload_3tfvr86m/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 675, in _update_netbox_object
    if serialized_nb_obj[key] != updated_obj[key]:
fatal: [localhost]: FAILED! => changed=false 
  invocation:
    module_args:
      data:
        description: null
        device: test1
        enabled: null
        form_factor: 1000base-t
        lag: null
        mac_address: null
        mgmt_only: null
        mode: null
        mtu: null
        name: public
        tagged_vlans: null
        tags: null
        untagged_vlan: null
      netbox_token: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      netbox_url: https://netbox
      state: present
      update_vc_child: false
      validate_certs: true
  msg: form_factor does not exist on existing object. Check to make sure valid field.

```
