### ISSUE TITLE
netbox_ip_address not set IP in a virtual machine Interface

### ISSUE THREAD

**Issue by ivangrover** [netbox-community/ansible_modules#198]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
2.9.7

###### Netbox:
2.8.0

###### Collection:
0.2.0

##### SUMMARY
netbox_ip_address seems to fail every time an IP is associated with a virtual machine interface. On devices it works perfectly.

##### STEPS TO REPRODUCE

```yaml
- name: vms
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox

  vars:
    netbox_url: https://netbox.url
    netbox_token: token

  tasks:
    - name: create vm
      netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: vm_name
          cluster: cluster
          virtual_machine_role: vm
          platform: debian10
          vcpus: 2
          memory: 1024
          disk: 20
        state: present

    - name: create interface
      netbox_vm_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          virtual_machine: vm_name
          name: eth0
          enabled: true
        state: present

    - name: set ip 192.168.1.0/24
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: 192.168.1.0/24
          status: Active
          interface:
            name: eth0
            device: vm_name
        state: new
```

##### EXPECTED RESULTS
VM with a network interface and a IP address

##### ACTUAL RESULTS
VM and interface created but not IP address

```
The full traceback is:                                                                        
  File "/tmp/ansible_netbox_ip_address_payload_hyzpgj23/ansible_netbox_ip_address_payload.zip/
ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 360, in _nb_endp
oint_get                                                                                      
    response = nb_endpoint.get(**query_params)                                                
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/endpoint.py", line 139, in get   
    filter_lookup = self.filter(**kwargs)                                                     
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/endpoint.py", line 227, in filter
    ret = [self._response_loader(i) for i in req.get()]                                       
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 350, in get      
    return req_all()                                                                          
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 303, in req_all  
    req = self._make_call(add_params=add_params)                                              
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 274, in _make_cal
l                                                                                             
    raise RequestError(req)                                                                   
fatal: [localhost]: FAILED! => {                                                              
    "changed": false,                                                                         
    "invocation": {                                                                           
        "module_args": {                                                                      
            "data": {                                                                         
                "address": null,                                                              
                "custom_fields": null,                                                        
                "description": null,
                "dns_name": null,
                "family": null,
                "interface": {
                    "device": "vm_name",
                    "name": "eth0"
                },
                "nat_inside": null,
                "prefix": "192.168.1.0/24",
                "role": null,
                "status": "Active",
                "tags": null,
                "tenant": null,
                "vrf": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.url",
            "state": "new",
            "validate_certs": true
        }
    },
    "msg": "\n<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n    <title>Server Error</title>\n
    <link rel=\"stylesheet\" href=\"/static/bootstrap-3.4.1-dist/css/bootstrap.min.css\">\n   
 <link rel=\"stylesheet\" href=\"/static/font-awesome-4.7.0/css/font-awesome.min.css\">\n    <
meta charset=\"UTF-8\">\n</head>\n\n<body>\n    <div class=\"container-fluid\">\n        <div 
class=\"row\">\n            <div class=\"col-md-6 col-md-offset-3\">\n                <div cla
ss=\"panel panel-danger\" style=\"margin-top: 200px\">\n                    <div class=\"panel
-heading\">\n                        <strong>\n                            <i class=\"fa fa-wa
rning\"></i>\n                            Server Error\n                        </strong>\n   
                 </div>\n                    <div class=\"panel-body\">\n                     
   \n                            <p>\n                                There was a problem with
 your request. Please contact an administrator.\n                            </p>\n           
             \n                        <hr />\n                        <p>\n                  
          The complete exception is provided below:\n                        </p>\n<pre><stron
g>&lt;class &#x27;ValueError&#x27;&gt;</strong><br />\nField &#x27;id&#x27; expected a number 
but got &#x27;name&#x27;.</pre>\n                        <p>\n                            If f
urther assistance is required, please post to the <a href=\"https://groups.google.com/forum/#!
forum/netbox-discuss\">NetBox mailing list</a>.\n                        </p>\n               
         <div class=\"text-right\">\n                            <a href=\"/\" class=\"btn btn
-primary\">Home Page</a>\n                        </div>\n                    </div>\n        
        </div>\n            </div>\n        </div>\n    </div>\n</body>\n\n</html>\n"
}

PLAY RECAP ***********************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    re
scued=0    ignored=0    
```
