### ISSUE TITLE
netbox_ip_address fails to add anycast address to multiple devices

### ISSUE THREAD

**Issue by nilssl** [netbox-community/ansible_modules#201]
**ISSUE TYPE**
- Bug Report

**SOFTWARE VERSIONS**
Ansible:

2.9.7
Netbox:

v2.8.3
Collection:
0.2.0

**SUMMARY**
Problems using ansible module netbox_ip_address to add anycast address to interfaces.

When having anycast gateways we would like to add same IP-address to different devices, so if we make interface vlan 100 on dcswitch1 and dcswitch2, and we want to give them both address 10.0.0.1/24, they both should receive the address.

As the screenshot describes this works as intended in the web-gui.

![Screenshot from 2020-05-11 12-15-20](https://user-images.githubusercontent.com/2377995/81550856-217b1480-9381-11ea-8d7b-102b16b557a9.png)

When running inn parallel sometimes the ansible playbook just ads the interface to the other device, so we end up with one interface only, when expected is that both devices has the interface. This is harder to reproduce.

When intefaces exist the ansible module returns an error saying multiple results returned, maybe this is because it does not filter on device when searching for the IP-address?

**Steps to reproduce**
Run twice
```
---
- hosts: dcswitch1,dcswitch2
  gather_facts: no
  connection: local
  collections:
    - netbox.netbox

  tasks:
    #Bind IP adresse to interface in parallel
    - name: Add switch anycast to netbox
      netbox_ip_address:
        netbox_url: 'http://localhost:32771'
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 10.0.0.1/24
          interface:
            name: Vlan100
            device: '{{ inventory_hostname }}'
          role: Anycast
        validate_certs: no


- hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - netbox.netbox

  tasks:
    #Bind IP adresse to interface VLAN 100 for device 1
    - name: Add switch anycast to netbox
      netbox_ip_address:
        netbox_url: 'http://localhost:32771'
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 10.0.0.1/24
          interface:
            name: Vlan100
            device: dcswitch1
          role: Anycast
        validate_certs: no

    # Bind IP address to interface VLAN 100 for device 2
    - name: Add switch anycast to netbox
      netbox_ip_address:
        netbox_url: 'http://localhost:32771'
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 10.0.0.1/24
          interface:
            name: Vlan100
            device: dcswitch2
          role: Anycast
        state: new
        validate_certs: no
```

**Result**
``` 
oot@dell-pc:/home/ansible# ansible-playbook netbox_import.yml

PLAY [dcswitch1,dcswitch2] *******************************************************************************************************

TASK [Add switch anycast to netbox] **********************************************************************************************
changed: [dcswitch2]
changed: [dcswitch1]

PLAY [localhost] *****************************************************************************************************************

TASK [Add switch anycast to netbox] **********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "More than one result returned for 10.0.0.1/24"}

PLAY RECAP ***********************************************************************************************************************
dcswitch1                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
dcswitch2                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

root@dell-pc:/home/ansible# ansible-playbook netbox_import.yml

PLAY [dcswitch1,dcswitch2] *******************************************************************************************************

TASK [Add switch anycast to netbox] **********************************************************************************************
fatal: [dcswitch1]: FAILED! => {"changed": false, "msg": "More than one result returned for 10.0.0.1/24"}
fatal: [dcswitch2]: FAILED! => {"changed": false, "msg": "More than one result returned for 10.0.0.1/24"}

PLAY RECAP ***********************************************************************************************************************
dcswitch1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
dcswitch2                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

Some takeaways
- If we try to run the playbook in parallell only one IP-address gets added, while doing this in sequence both will be added as intended.
- If we try to run the playbook after both IP-addresses are configured in netbox this will return the following "More than one result returned"

**Comment by FragmentedPacket** [comment]
I will try and get a PR submitted tonight or tomorrow for this. I think we can just add `interface` to `ALLOWED_QUERY_PARAMS` for ip_address and it should resolve the issue.


Sorry for the delay in getting back to you.

**Comment by FragmentedPacket** [comment]
Just submitted PR #209. Do you mind testing it and letting me know if it fixes your issue?

**Comment by FragmentedPacket** [comment]
@nilssl Just wanted to check in with you. Can you validate #209 solves your issue?

**Comment by nilssl** [comment]
I will have it tested on monday, thanks for getting back to me on this issue.

**Comment by nilssl** [comment]
I still get the same error message :(

`
The full traceback is:
  File "/tmp/ansible_netbox_ip_address_payload_a9mf99p2/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 364, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/endpoint.py", line 143, in get
    "get() returned more than one result. "
fatal: [dcswitch1]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "data": {
                "address": "10.0.0.1/24", 
                "custom_fields": null, 
                "description": null, 
                "dns_name": null, 
                "family": null, 
                "interface": {
                    "device": "dcswitch1", 
                    "name": "Vlan100"
                }, 
                "nat_inside": null, 
                "prefix": null, 
                "role": "Anycast", 
                "status": null, 
                "tags": null, 
                "tenant": null, 
                "vrf": null
            }, 
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "netbox_url": "http://localhost:32768", 
            "state": "present", 
            "validate_certs": false
        }
    }, 
    "msg": "More than one result returned for 10.0.0.1/24"
}
`

**Comment by FragmentedPacket** [comment]
Change the state to new and try again

**Comment by FragmentedPacket** [comment]
@nilssl Sorry I just want to bump this again. In your example in the OP, it shows you use the `state: new` and that is the appropriate use of it, but in your last test the state is `present`.

I want to get this merged in and cut a new release ASAP.

**Comment by nilssl** [comment]
I seem to still get the same error when running with state: new
Have you tried running my play?

**Comment by FragmentedPacket** [comment]
I ran something similar and it worked. I also updated the tests as well to have the same scenario.

```
---
- hosts: localhost
  connection: local
  collections:
    - netbox.netbox
  gather_facts: no

  tasks:
    - name: "Create IP address on interfaces"
      netbox_ip_address:
        netbox_url: "http://localhost:32768"
        netbox_token: "0123456789abcdef0123456789abcdef01234567"
        data:
          address: "192.168.10.1/24"
          role: "Anycast"
          interface:
            name: "public"
            device: "R1"

    - name: "Create IP address on interfaces"
      netbox_ip_address:
        netbox_url: "http://localhost:32768"
        netbox_token: "0123456789abcdef0123456789abcdef01234567"
        data:
          address: "192.168.10.1/24"
          role: "Anycast"
          interface:
            name: "Ethernet1/1"
            device: "Test Nexus One"
        state: "new"
```

Running the playbook
```
PLAYBOOK: netbox_ip_addr_intf.yml **************************************************************************************************
1 plays in netbox_ip_addr_intf.yml

PLAY [localhost] *******************************************************************************************************************
META: ran handlers

TASK [Create IP address on interfaces] *********************************************************************************************
task path: /home/myohman/local_ansible_junk/netbox_ip_addr_intf.yml:9
changed: [localhost] => changed=true
  ip_address:
    address: 192.168.10.1/24
    created: '2020-05-27'
    custom_fields: {}
    description: ''
    dns_name: ''
    family: 4
    id: 7
    interface: 14
    last_updated: '2020-05-27T13:42:37.989934Z'
    nat_inside: null
    nat_outside: null
    role: anycast
    status: active
    tags: []
    tenant: null
    vrf: null
  msg: ip_address 192.168.10.1/24 created

TASK [Create IP address on interfaces] *********************************************************************************************
task path: /home/myohman/local_ansible_junk/netbox_ip_addr_intf.yml:20
changed: [localhost] => changed=true
  ip_address:
    address: 192.168.10.1/24
    created: '2020-05-27'
    custom_fields: {}
    description: ''
    dns_name: ''
    family: 4
    id: 8
    interface: 1
    last_updated: '2020-05-27T13:42:38.683944Z'
    nat_inside: null
    nat_outside: null
    role: anycast
    status: active
    tags: []
    tenant: null
    vrf: null
  msg: ip_address 192.168.10.1/24 created
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

If you clone this repo and then run the following after removing the existing collection from your collections path:
1. `git fetch origin pull/209/head:fix-my-issue`
2. `git checkout fix-my-issue`
3. `ansible-galaxy collection build .`
4. `ansible-galaxy collection install <netbox.tar.gz>`

And then run the playbook.
