### ISSUE TITLE
Rename devices and other entities

### ISSUE THREAD

**Issue by monkz** [netbox-community/ansible_modules#215]
##### ISSUE TYPE
 - Feature Idea

###### Ansible:
ansible 2.9.9

###### Netbox:
(v2.8.4)

###### Collection:
0.2.1

##### SUMMARY
It is not possible to rename a device.
This collection uses the name of an entity as identification. So on every rename (aka. destroy and create) the device loses the changelog.

I would like to identify the device by asset tag (which is also unique) or another unique attribute to rename a device

**Comment by FragmentedPacket** [comment]
Let me think about how we can accomplish this. Do you find yourself needing to change device names, etc. often?

I'm wondering if we can add a "new_name" sort of thing to modules to act upon to find the existing device/item and then update the name.

What other endpoints do you find yourself doing this on?

**Comment by monkz** [comment]
We recycle bare metal devices very often.

- New tenant - new name.
- Repairs done - new name as it gets a new purpose.
- Reinstall - new name.

I don't see other endpoints so far. Maybe Inventory Items. As HDDs may be mounted with another purpose.
But that is just our case. I think there may be other cases, where other things might be renamed.

In my eyes a "key" selector for every module would be great:
```
- hosts: all
  become: yes 
  tasks:
   - name: Create device within NetBox with dynamic information
      delegate_to: localhost
      become: no
      netbox.netbox.netbox_device:
        netbox_url: https://netbox.example.com
        netbox_token: 123456789123456789123456789123456
        data:
          name: "{{ ansible_hostname }}"
          device_type: TypeX
          device_role: Customer System
          status: Staged
          asset_tag: "{{ company_asset_tag }}"
        key_field: asset_tag
        state: present
```

this would set name, device_type, device_role, stage where an asset_tag is given or it would create an entry. The fact would have to be gathered first obviously - and the fact would be unique.

Another possibility would be mass updates:
```
- name: "Do things local"
  connection: local
  hosts: localhost
   - name: Set every device in a site as staged
      netbox.netbox.netbox_device:
        netbox_url: https://netbox.example.com
        netbox_token: 123456789123456789123456789123456
        data:
          site: very new site
          status: Staged
        key_field: site
        state: updated
```
This  would require a new state, that would not create an item if none exists.
