### ISSUE TITLE
Example playbook on README has bad indentation.

### ISSUE THREAD

**Issue by kaitoii11** [netbox-community/ansible_modules#226]
##### ISSUE TYPE

 - Documentation update
##### SUMMARY

Example playbook on README has bad indentation.

##### STEPS TO REPRODUCE

```yaml
- name: "Test NetBox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox

  tasks:
    - name: Create device within NetBox with only required information
      netbox_device:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          name: Test66
          device_type: Cisco Test
          device_role: Core Switch
          site: Test Site
          status: Staged
          state: present
```

##### EXPECTED RESULTS
State should be aligned with data.

```yaml
- name: "Test NetBox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox

  tasks:
    - name: Create device within NetBox with only required information
      netbox_device:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          name: Test66
          device_type: Cisco Test
          device_role: Core Switch
          site: Test Site
          status: Staged
        state: present
```
