### ISSUE TITLE
Playbook Failing with 405 Method Not allowed

### ISSUE THREAD

**Issue by abhilashchinthalapudi** [netbox-community/ansible_modules#234]
- Module question

###### Ansible:
Version : 2.9.3

###### Netbox:

2.7.10

###### Collection:

0.2.2
##### SUMMARY
I used my Ansible Playbook with Older version when it was netbox.community.ansible_modules collection and it works perfect 
I tried installing the newer version and validating playbook operations.
I am seeing some device updates are done through HTTP options method which we do not allow on HTTPS endpoint as per netbox logs and playbook error 

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pynetbox.core.query.RequestError: The request failed with code 405 Method Not Allowed but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.

##### STEPS TO REPRODUCE
Running the playbook with HTTPD OPTIONS DIsables

```
- name: "Update NB"
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - netbox.netbox
  tasks:
    - name: Update Information on custom fields of a machine
      netbox_device:
        netbox_url: "{{ url }}"
        netbox_token: "{{ api_token }}"
        data:
          name: "{{source_host}}"
          serial: "{{ hostvars[source_host]['SERIAL'] }}"
          primary_ip4: "{{ hostvars[source_host]['ip'] }}"
          status: Active
          custom_fields:
            Field1 : Value
```

##### EXPECTED RESULTS
Playbook run successful with updated information
##### ACTUAL RESULTS

Failed with 405 Error

```

```
