### ISSUE TITLE
netbox_ip_address: "msg": "Could not resolve id of interface: 1081"

### ISSUE THREAD

**Issue by lotusnoir** [netbox-community/ansible_modules#240]
Hello, 
I have an issue with this module trying to pass a variable into "**interface**" field.

```
- name: Create netbox_ip_address
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ item.address }}"
          dns_name: "{{ item.name }}"
          #interface: "{{ vminterfaceid }}"
          interface: 1081          <<< if u use quote or double quotes i get this error, only works when set without anything                                                                                                                                                                                                       
        state: present
      with_items: "{{ netbox_virtual_machine }}"
```

Unfortunately when i pass this field with a variable it always convert it with double quotes
```
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "address": "10.1.1.1",
                "custom_fields": null,
                "description": null,
                "dns_name": "test",
                "family": null,
                "interface": "1081", <<< value converted with double quotes when passed with variable
```
I saw that the field is in "raw" format, should it be considered like a numeric field ?
Thanks in advance
