### ISSUE TITLE
Failed to establish connection with Netbox API

### ISSUE THREAD

**Issue by misch42** [netbox-community/ansible_modules#253]
##### ISSUE TYPE
 - Module question

###### Ansible:

ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/misch/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
###### Netbox:

v2.8.6

###### Collection:

v0.2.3

##### SUMMARY

I created a play according to the example. When running my play I get an error that ansible cannot establish a connection to the netbox API.

A plain pynetbox request works:
```shell
import pynetbox

nb=pynetbox.api(url='http://127.0.0.1:8001', token='XXXXx')

all_prefixes = nb.ipam.prefixes.all()

print(all_prefixes)
```

I also do not see any traffic on port 8001 while running the play.

##### STEPS TO REPRODUCE

See above.

```yaml
- name: "Test NetBox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox

  tasks:
    - name: Create device within NetBox with only required information
      netbox_device:
        netbox_url: http://127.0.0.1:8001
        netbox_token: XXXX
        data:
          name: Test66
          device_type: Cisco Test
          device_role: Core Switch
          site: home
          status: Staged
        state: present
```

##### EXPECTED RESULTS

New device in netbox

##### ACTUAL RESULTS

Error message

```
The full traceback is:
  File "/tmp/ansible_netbox_device_payload_xd7oh6dh/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 417, in _connect_netbox_api
    nb = pynetbox.api(url, token=token, ssl_verify=ssl_verify)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "custom_fields": null,
                "device_role": "Core Switch",
                "device_type": "Cisco Test",
                "face": null,
                "name": "Test66",
                "platform": null,
                "position": null,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": null,
                "serial": null,
                "site": "home",
                "status": "Staged",
                "tags": null,
                "tenant": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://127.0.0.1:8001",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "Failed to establish connection to Netbox API"
}
```
