### ISSUE TITLE
Failed to establish connection to Netbox API

### ISSUE THREAD

**Issue by adamwoolhether** [netbox-community/ansible_modules#256]
##### ISSUE TYPE
 - Module question

###### Ansible:
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

###### Netbox:
v2.8.6

###### Collection:
v0.2.3

##### SUMMARY
Play made according to example results in error.

I've already downgrade pynetbox to 4.3.3, per #253 but issue remains

##### STEPS TO REPRODUCE

```
---
- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox

  tasks:
    - name: "Create device within Netbox with only required information"
      netbox_device:
        netbox_url: https://10.108.5.101/
        netbox_token: XXXX
        data:
            name: Test898
            device_type: Cisco Test
            device_role: core switch
            site: test site
            status: staged
        state: present
```

##### EXPECTED RESULTS

New netbox device

##### ACTUAL RESULTS
Error message. Full verbose output as follows:
```
The full traceback is:
  File "/tmp/ansible_netbox_device_payload_p4ojt6ti/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 419, in _connect_netbox_api
    self.version = float(nb.version)
  File "/usr/local/lib/python3.6/site-packages/pynetbox/api.py", line 230, in version
    http_session=self.http_session,
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 195, in get_version
    verify=self.ssl_verify,
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "custom_fields": null,
                "device_role": "core switch",
                "device_type": "Cisco Test",
                "face": null,
                "name": "Test898",
                "platform": null,
                "position": null,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": null,
                "serial": null,
                "site": "test site",
                "status": "staged",
                "tags": null,
                "tenant": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://10.108.5.101/",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "Failed to establish connection to Netbox API"
}
```
