### ISSUE TITLE
problem adding a front port to a device with a rear port..

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/ansible_modules#262]
##### ISSUE TYPE

 - Bug Report
###### Ansible:

ansible 2.9.10
  config file = /home/tdavis/gitlab/netbox/ansible.cfg
  configured module search path = ['/home/tdavis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tdavis/gitlab/netbox/venv/lib64/python3.6/site-packages/ansible
  executable location = /home/tdavis/gitlab/netbox/venv/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

###### Netbox:

netbox-2.8.6

###### Collection:

latest github release

##### SUMMARY

```
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp `"&& mkdir /tmp/ansible-tmp-1594171920.3645124-64740-1987896491334 && echo ansible-tmp-1594171920.3645124-64740-1987896491334="` echo /tmp/ansible-tmp-1594171920.3645124-64740-1987896491334 `" ) && sleep 0'
Using module file /home/tdavis/.ansible/collections/ansible_collections/netbox/netbox/plugins/modules/netbox_front_port.py
<127.0.0.1> PUT /home/tdavis/.ansible/tmp/ansible-local-64664ltlmutsv/tmpmxd8bk2v TO /tmp/ansible-tmp-1594171920.3645124-64740-1987896491334/AnsiballZ_netbox_front_port.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1594171920.3645124-64740-1987896491334/ /tmp/ansible-tmp-1594171920.3645124-64740-1987896491334/AnsiballZ_netbox_front_port.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/tdavis/gitlab/netbox/venv/bin/python3 /tmp/ansible-tmp-1594171920.3645124-64740-1987896491334/AnsiballZ_netbox_front_port.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1594171920.3645124-64740-1987896491334/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_netbox_front_port_payload_q68ig7sx/ansible_netbox_front_port_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 468, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/home/tdavis/gitlab/netbox/venv/lib64/python3.6/site-packages/pynetbox/core/endpoint.py", line 143, in get
    "get() returned more than one result. "
failed: [localhost] (item={'host': 'pp-e3-r10-u31-c1', 'name': 'LC-2', 'index': 2}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "description": null,
                "device": "pp-e3-r10-u31-c1",
                "name": "LC-2",
                "rear_port": "MPO",
                "rear_port_position": 2,
                "tags": null,
                "type": "lc"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.nersc.gov",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "item": {
        "host": "pp-e3-r10-u31-c1",
        "index": 2,
        "name": "LC-2"
    },
    "msg": "More than one result returned for rear_port"
}
```

##### STEPS TO REPRODUCE

1) create device.
2) add rear port with multiple positions.
3) try to add front port to 1 position.

```yaml
  - name: add front ports for the cassette
    netbox_front_port:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"
      data:
        device: "{{ item.host }}"
        name: "{{ item.name }}"
        type: lc
        rear_port: 'MPO'
        rear_port_position: "{{ item.index }}"
      state: present
    loop: "{{ frontports }}"
    connection: localhost

```

##### EXPECTED RESULTS

add front port to rear port with multiple indexes.

##### ACTUAL RESULTS

Failure.

**Comment by FragmentedPacket** [comment]
What if you change `rear_port` to a dictionary?

```yaml
rear_port:
  device: "{{ item.host }}"
  name: "MPO"
```
