### ISSUE TITLE
Setting a custom field with a integer value will fail

### ISSUE THREAD

**Issue by pugnacity** [netbox-community/ansible_modules#266]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
ansible 2.9.10

###### Netbox:
2.7.12

###### Collection:
0.2.3

##### SUMMARY
Setting a custom field with a integer value will fail

##### STEPS TO REPRODUCE
Set a custom field to a VM with a variable which contains only a integer value.

```yaml
- name: Get host info
  zabbix_host_info:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ zabbix_agent_hostname }}"
    timeout: 10
    exact_match: yes
    remove_duplicate: yes
  register: zabbix_host_info
  delegate_to: localhost

# apply Host ID to custom fied within netbox
- name: Set Zabbix HostID (VM)
  collections:
    - netbox.netbox
  netbox_virtual_machine:
    netbox_url:  "{{ netbox_url }}"
    netbox_token:  "{{ netbox_token }}"
    data:
      name: "{{ inventory_hostname }}"
      custom_fields:
          zabbix_hostid: "{{ zabbix_host_info.hosts.0.hostid }}"
  delegate_to: localhost
  become: false
  when:
    - ansible_virtualization_role == 'guest'

```

When extending the value with some prefix like `zabbix_hostid: "ID{{ zabbix_host_info.hosts.0.hostid }}"` The tasks works fine. Maybe its related to #231 because in 0.2.2 everything works fine. 

##### EXPECTED RESULTS
 ```
{
     "custom_fields": {
+        "zabbix_hostid": "10333"
     }
 }
```
##### ACTUAL RESULTS
It will set the ID to null

```
 {
     "custom_fields": {
         "zabbix_hostid": null
     }
 }

```
