### ISSUE TITLE
Inventory: IPaddresses of interfaces is lost when using cache.

### ISSUE THREAD

**Issue by matte4711** [netbox-community/ansible_modules#276]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.9.10

###### Netbox:

v2.8.7

###### Collection:

v0.3.0

##### SUMMARY

When using caching together with nb_inventory and expanding interfaces IP-address mapping gets lost when using cache.

##### STEPS TO REPRODUCE

The issue is reproducible by configure nb_inventory and using cache.

```yaml
plugin: netbox.netbox.nb_inventory
cache: true
cache_plugin: jsonfile
cache_timeout: 3600
api_endpoint: https://netbox-lab.netnod.se
interfaces: true
```

Take any device with a interface that have ip-address assigned to it and run the following command:
```shell
$ rm /tmp/ansible/ansible_inventory_netbox*
$ ansible-inventory --host ag1b-bck.gbg.netnod.se 2>/dev/null | jq '.interfaces[] | select(.name == "Ethernet1").ip_addresses[].address'
"172.20.9.2/31"
$ ansible-inventory --host ag1b-bck.gbg.netnod.se 2>/dev/null | jq '.interfaces[] | select(.name == "Ethernet1").ip_addresses[].address'
$ 
```

I have done some debugging and it looks like the issue is due to the ip-addresses query results from netbox is modified and the modified data is written to the cache. 

Removal of interface mapping is done here:
(https://github.com/netbox-community/ansible_modules/blob/devel/plugins/inventory/nb_inventory.py#L837) 

The ip-address-> interface mapping is needed to attach the ip-addresses to the interfaces. 
And in consecutive runs this is not available.

##### ACTUAL RESULTS

```

```
