### ISSUE TITLE
netbox_prefix doesn’t add new prefix to netbox and return changed=False everytime

### ISSUE THREAD

**Issue by Akasurde** [netbox-community/ansible_modules#278]
_From @FurryJulie on Jan 06, 2020 11:53_

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netbox prefix

##### ANSIBLE VERSION

```
ansible 2.9.2
  config file = /home/julied/venv/ansible-temp/ansible/ansible.cfg
  configured module search path = [u'/home/julied/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/julied/venv/ansible-temp/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/julied/venv/ansible-temp/venv/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```
##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/julied/venv/ansible-temp/ansible/ansible.cfg) = [u'/home/julied/venv/ansible-temp/ansible/inventories']
DEFAULT_ROLES_PATH(/home/julied/venv/ansible-temp/ansible/ansible.cfg) = [u'/home/julied/venv/ansible-temp/ansible/roles']
```

##### OS / ENVIRONMENT
Netbox version: v2.2.6

##### STEPS TO REPRODUCE

```yaml
- name: "common: netbox add hosts in netbox"
  netbox_prefix:
    netbox_token: "XXX"
    validate_certs: "no"
    netbox_url: "http://netbox.XXX"
    data:
      status: Active
      prefix: "192.168.0.0/24"
      family: 4
      state: present
      vrf: "test"
  delegate_to: localhost
  connection: local
```

##### EXPECTED RESULTS
changed=True
and the prefix is added to netbox

##### ACTUAL RESULTS

```
ok: [sftp01.XXX -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "family": 4,
                "prefix": "192.168.0.0/24",
                "state": "present",
                "status": 1,
                "vrf": 1
            },
            "first_available": false,
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://netbox.XXX",
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "Returned more than one result"
}

```
And the prefix is not present in netbox

_Copied from original issue: ansible/ansible#66204_
