### ISSUE TITLE
netbox_device module fails with custom NetBox slug name

### ISSUE THREAD

**Issue by Akasurde** [netbox-community/ansible_modules#279]
_From @karlism on Oct 23, 2019 15:12_

##### SUMMARY
`netbox_device` module fails to add device if it has non-standard slug name

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

netbox_device

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Oct 11 2019, 11:15:58) [Clang 8.0.1 (tags/RELEASE_801/final)]
```

##### CONFIGURATION

```paste below
COLOR_VERBOSE(/home/user/.ansible.cfg) = cyan
DEFAULT_CALLBACK_WHITELIST(/home/user/.ansible.cfg) = ['timer']
DEFAULT_HASH_BEHAVIOUR(/home/user/.ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = ['/home/user/ansible/library/netbox/netbox.py']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/user/.ansible/vault_pass
```

##### OS / ENVIRONMENT

OpenBSD 6.6 amd64

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: False

  tasks:
    - netbox_device:
        netbox_url: "https://netbox.example.com/"
        netbox_token: "XXX"
        state: present
        data:
          name: "ansibletest1"
          device_role: "Cable Management"
          device_type: "Unknown"
          site: "Example"
          comment: "device with '-' in slug"

    - netbox_device:
        netbox_url: "https://netbox.example.com/"
        netbox_token: "XXX"
        state: present
        data:
          name: "ansibletest2"
          device_role: "VM Guest"
          device_type: "Unknown"
          site: "Example"
          comment: "device with '_' in slug"
```
Related NetBox objects are following:
```
        {
            "id": 16,
            "name": "Cable Management",
            "slug": "cable-management",
            "color": "795548",
            "vm_role": true,
            "device_count": 24,
            "virtualmachine_count": null
        },
        {
            "id": 18,
            "name": "VM Guest",
            "slug": "vm_guest",  # <- note that "-" is replaced with "_" here
            "color": "aa1409",
            "vm_role": true,
            "device_count": 115,
            "virtualmachine_count": null
        },
```

##### EXPECTED RESULTS

I would expect `netbox_device` module to work with any slug name.

##### ACTUAL RESULTS

`netbox_device` module fails when NetBox slug value is modified, as it takes given value, changes it to lowercase and replaces spaces to dashes.

```paste below
Using /home/user/.ansible.cfg as config file

PLAY [localhost] ***************************************************************************************************************

TASK [netbox_device] ***********************************************************************************************************
changed: [localhost] => {"changed": true, "device": {"asset_tag": null, "cluster": null, "comments": "", "config_context": {}, "created": "2019-10-23", "device_role": 16, "device_type": 48, "display_name": "ansibletest1", "face": null, "id": 1094, "last_updated": "2019-10-23T15:02:38.424536Z", "local_context_data": null, "name": "ansibletest1", "parent_device": null, "platform": null, "position": null, "primary_ip": null, "primary_ip4": null, "primary_ip6": null, "rack": null, "serial": "", "site": 13, "status": 1, "tags": [], "tenant": null, "vc_position": null, "vc_priority": null, "virtual_chassis": null}, "msg": "Device ansibletest1 created"}

TASK [netbox_device] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not resolve id of device_role: vm-guest"}

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

_Copied from original issue: ansible/ansible#63862_

**Comment by Akasurde** [comment]
_From @FragmentedPacket on Oct 27, 2019 18:47_

@karlism Thanks for your issue.

I'm not developing the modules within Netbox core any longer. They can be found as an Ansible Collection now. https://galaxy.ansible.com/fragmentedpacket/netbox_modules

I believe what you're experiencing can be worked around by making `device_role` a dictionary with a `slug` key with the custom slug.

```
data:
  device_role:
    slug: "custom_slug"
```

We're converting the passed in value just as Netbox would by default and can't account for every way someone may format their slug behind the scenes and programmatically. This shouldn't convert anything and should find it. 

Try the above using the Netbox Ansible Collection, and then if that doesn't work, please open an issue on the Github for that collection and we can discuss further.

**Comment by karlism** [comment]
Unfortunately solution proposed by @FragmentedPacket didn't help, running following playbook:
```
- hosts: localhost
  gather_facts: False

  tasks:
    - netbox_device:
        netbox_url: "https://netbox.example.com/"
        netbox_token: "XXX"
        state: present
        data:
          name: "ansibletest"
          device_role:
            slug: "vm_guest"
          site: "ZG2"
          comment: "device with '_' in slug"
```
Produces following error:
```
PLAY [localhost] *****************************************************************************************************

TASK [netbox_device] *************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'intersection'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/username/.ansible/tmp/ansible-tmp-1602725995.0176892-48623-124512542907627/AnsiballZ_netbox_device.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/username/.ansible/tmp/ansible-tmp-1602725995.0176892-48623-124512542907627/AnsiballZ_netbox_device.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/username/.ansible/tmp/ansible-tmp-1602725995.0176892-48623-124512542907627/AnsiballZ_netbox_device.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.net_tools.netbox.netbox_device', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netbox_device_payload_hxc19jb7/ansible_netbox_device_payload.zip/ansible/modules/net_tools/netbox/netbox_device.py\", line 312, in <module>\n  File \"/tmp/ansible_netbox_device_payload_hxc19jb7/ansible_netbox_device_payload.zip/ansible/modules/net_tools/netbox/netbox_device.py\", line 243, in main\n  File \"/tmp/ansible_netbox_device_payload_hxc19jb7/ansible_netbox_device_payload.zip/ansible/modules/net_tools/netbox/netbox_device.py\", line 267, in ensure_device_present\n  File \"/tmp/ansible_netbox_device_payload_hxc19jb7/ansible_netbox_device_payload.zip/ansible/modules/net_tools/netbox/netbox_device.py\", line 258, in _find_ids\n  File \"/tmp/ansible_netbox_device_payload_hxc19jb7/ansible_netbox_device_payload.zip/ansible/module_utils/net_tools/netbox/netbox_utils.py\", line 298, in find_ids\n  File \"/tmp/ansible_netbox_device_payload_hxc19jb7/ansible_netbox_device_payload.zip/ansible/module_utils/net_tools/netbox/netbox_utils.py\", line 269, in build_query_params\nAttributeError: 'NoneType' object has no attribute 'intersection'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
```
ansible 2.9.14
  config file = /home/username/.ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Sep 30 2020, 14:16:50) [Clang 10.0.1 ]
```
