### ISSUE TITLE
Update Netbox inventory plugin add region grouping, optional interfaces&vlans gathering, slug and prefix length

### ISSUE THREAD

**Issue by Akasurde** [netbox-community/ansible_modules#280]
_From @Yannis100 on Aug 06, 2019 08:26_

##### SUMMARY

Add sites groups as children in their respective region groups
Add 1 value to choose the length of the group name prefix (before the '_') and 1 to "minify" the suffix part (using slugs (or lowercase and change special chars (space, -) to underscore))
Add interfaces per host and vlans per site

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Netbox inventory plugin

##### ADDITIONAL INFORMATION

Grouping by regions add sites as children of the group but currently add hosts too.
Interfaces and vlan gathering works, maybe not perfectly optimized?

Similar to use_slugs in nornir netbox inventory plugin
https://github.com/nornir-automation/nornir/blob/develop/nornir/plugins/inventory/netbox.py

For interfaces gathering, the following is a good example :
https://github.com/openfibernet/ansible-netbox-inventory/blob/master/netbox.py
or #59725

```yaml
plugin: netbox
api_endpoint: https://netbox:443
validate_certs: False
config_context: True
token: xxx
vlans: True
interfaces: True
use_slugs: True
substr_group: 8
group_by:
  - device_roles
  - device_types
  - sites
  - platforms
  - tags
  - regions
query_filters:
  - role: SWA
  - platform: ios-xe
```

```
ansible-inventory --graph
@all:
  |--@platform_ios-xe:
  |  |--3850-SWA01
  |--@device_r_SWA:
  |  |--3850-SWA01
  |--@device_t_WS-C3650-48PD-S:
  |  |--3650-SWA01
…
  |--@device_t_WS-C3850-12X48U-S:
  |  |--3850-SWA01
…
  |--@regions_AMR:
  |  |--@sites_US-PHX:
  |  |--@sites_USATL04:
  |  |  |--3850-SWA01
  |  |--@sites_USPHX03:
  |  |  |--3650-SWA01
  |--@regions_APAC:
  |  |--@sites_INBLR01:
  |  |  |--3850-SWA01-1
  |--@regions_EMEA:
  |  |--@sites_CHZRH04:
  |--@tags_uat:
  |  |--3850-SWA01-1
  |--@ungrouped:

```

If a site is not assigned to a region, the plugin may fail

_Copied from original issue: ansible/ansible#60124_
