### ISSUE TITLE
can't apply netbox_device_bay_templates & netbox_device_interface_templates with the same name to different device types.

### ISSUE THREAD

**Issue by adamwoolhether** [netbox-community/ansible_modules#282]
##### ISSUE TYPE

 - Module question

###### Ansible:

ansible 2.9.10
python 3.6.8

###### Netbox:

2.8.6

###### Collection:

0.3.1
pynetbox 5.0.4
##### SUMMARY

Unsure if bug or intended behavior: Interface/bay templates require a globally unique name. This also means you can't loop over device_types to apply the template to multiple device_types.

You CAN use the same name if done manually via the Netbox UI.

##### STEPS TO REPRODUCE

I tried two methods:
1. A ```task``` that uses ```loop``` to apply 4 different bays named by number to ```device_type``` A, and a separate ```task``` with similar structure applied to ```device_type```B

2. A ```task``` that uses ```loop``` over different devices to apply an ```interface``` with the same name.

Method 1.
```yaml
    - name: "TASK: SETUP S5S BAYS"
      netbox_device_bay_template:
        netbox_url: XXXX
        netbox_token: XXX
        validate_certs: no
        data:
          name: "{{ item.name }}"
          device_type: s5s
        state: present
      loop:
        - { name: "0" }
        - { name: "1" }
        - { name: "2" }
        - { name: "3" }
      tags: bays

    - name: "TASK: SETUP S5D BAYS"
      netbox_device_bay_template:
        netbox_url: XXXX
        netbox_token: XXXX
        validate_certs: no
        data:
          name: "{{ item.name }}"
          device_type: s5d
        state: present
      loop:
        - { name: "0" }
        - { name: "1" }
        - { name: "2" }
        - { name: "3" }
      tags: bays
```

Method 2:
```yaml
...
        data:
          device_type: "{{ item.dev }}"
          name: SFP+ (10GE)
          type: SFP+ (10GE)
        state: present
      loop:
        - { "dev": "s7dmb" }
        - { "dev": "s5bvmb" }
        - { "dev": "s5bmb" }
        - { "dev": "s5dmb" }
        - { "dev": "s5smb" }
        - { "dev": "s5gmb" }
      tags: interface
```

##### EXPECTED RESULTS

1. For eachof the device_types to have a device_bay template with 4 bays, with a range of names. Same as using [0-3] in the UI.
2. Similar, for each device_type to be given a new Interface template with the designated name.

##### ACTUAL RESULTS

The data is only given to one device_type, and the rest are skipped, meaning I have to add a whole new play with unique information in the playbook.

No indication of error.
```
TASK [TASK: SETUP S5S BAYS] ***************************************************************
changed: [localhost] => (item={'name': '0'})
changed: [localhost] => (item={'name': '1'})
changed: [localhost] => (item={'name': '2'})
changed: [localhost] => (item={'name': '3'})

TASK [TASK: SETUP S5D BAYS] ***************************************************************
changed: [localhost] => (item={'name': '0'})
changed: [localhost] => (item={'name': '1'})
changed: [localhost] => (item={'name': '2'})
changed: [localhost] => (item={'name': '3'})
```
