### ISSUE TITLE
nb_lookup plugin not found

### ISSUE THREAD

**Issue by sc68cal** [netbox-community/ansible_modules#292]
Following the documentation in the README, I created the following playbook

```yaml
---
- name: "Gather interface information from netbox"
  connection: local
  hosts: all
  gather_facts: False
  collections:
    - netbox.netbox
  vars:
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN')' }}"
    netbox_host: "{{ lookup('env', 'NETBOX_HOST') }}"

  tasks:
    - name: "Lookup devices via the API"
      debug:
        msg: "{{ query_result }}"
      vars:
        query_result: '{{ lookup("netbox.netbox.nb_lookup", "devices", api_filter="role=leaf-switch", api_endpoint=netbox_host, token=netbox_token) }}'

```

```
TASK [Lookup devices via the API] ************************************************************************************
fatal: [LAB2-6008-10-LFR02]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('nb_lookup', 'devices', api_endpoint='{{ netbox_host }}', token='{{ netbox_token }}') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: lookup plugin (nb_lookup) not found"}
```

This is after verifying that this collection was installed via Ansible galaxy and the plugin is present

```shell
ls ~/.ansible/collections/ansible_collections/netbox/netbox/plugins/lookup/nb_lookup.py
/Users/<sanitized>/.ansible/collections/ansible_collections/netbox/netbox/plugins/lookup/nb_lookup.py
```
