### ISSUE TITLE
Custom fields are not getting updated

### ISSUE THREAD

**Issue by autogun** [netbox-community/ansible_modules#311]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
```
ansible --version
ansible 2.9.9
  config file = /home/danny/test/ansible.cfg
  configured module search path = ['/home/danny/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python38/lib/python3.8/site-packages/ansible
  executable location = /opt/python38/bin/ansible
  python version = 3.8.3 (default, May 25 2020, 00:36:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

###### Netbox:
`v2.8.9`

###### Collection:
`netbox:1.0.0`

##### SUMMARY
`netbox_virtual_machine` module doesn't update an entry when data is **only** changed in `custom_fields`
If a tag is also being added/removed, entry is successfully updated. 

##### STEPS TO REPRODUCE

1. Create a custom field for `virtual machine` model
2. Populate it with data
3. Execute a playbook with a different data for that custom field
4. Observe `changed` state

```yaml
- name: "VIRTUAL MACHINE"
  local_action:
    module: netbox_virtual_machine
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ setup.ansible_facts.ansible_fqdn }}"
      status: Active
      virtual_machine_role: "Virtual Machine"
      custom_fields: 
        testfield: "abc123"
```

##### EXPECTED RESULTS

TASK [VIRTUAL MACHINE] **********************************************************************************
changed: [testvm -> localhost]
`"msg": "virtual_machine testvm updated",`
##### ACTUAL RESULTS

TASK [VIRTUAL MACHINE] **********************************************************************************
ok: [testvm -> localhost]
`"msg": "virtual_machine testvm already exists",`

```

```

**Comment by autogun** [comment]
A workaround I found to work by adding a temporary tag and removing it at the end updates all the fileds.

```yaml
- name: "VM VARIABLES"
  set_fact:
    my_tags:
      - "_placeholder_"
      - many other...

- name: "VIRTUAL MACHINE"
  local_action:
    module: netbox_virtual_machine
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ setup.ansible_facts.ansible_fqdn }}"
      status: Active
      virtual_machine_role: "Virtual Machine"
      custom_fields: 
        testfield: "abc123"
      tags: "{{ my_tags }}"

- name: "VIRTUAL MACHINE (Post run)"
  local_action:
    module: netbox_virtual_machine
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ setup.ansible_facts.ansible_fqdn }}"
      tags: "{{ my_tags | reject('search', '_placeholder_') | list }}"
    state: present
```
