### ISSUE TITLE
Can't assign existing IP to vm interface with netbox_ip_address

### ISSUE THREAD

**Issue by garbled1** [netbox-community/ansible_modules#315]
##### ISSUE TYPE

 - Bug Report
###### Ansible:

ansible 2.9.1
  config file = None
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

###### Netbox:

2.8.5
###### Collection:

1.0.0
##### SUMMARY

Can't assign IP to vm interface with netbox_ip_address
##### STEPS TO REPRODUCE

```yaml
- name: Assign IP to interface
  netbox.netbox.netbox_ip_address:
    netbox_url: '{{ netbox_server }}'
    netbox_token: '{{ netbox_token }}'
    data:
      prefix: '{{ netbox_prefix }}'
      #vrf: '{{ netbox_vrf }}'
      address: '{{ ansible_default_ipv4.address }}'
      dns_name: '{{ inventory_hostname_short }}'
      #family: 4
      interface:
        name: Ethernet
        virtual_machine: '{{ inventory_hostname_short }}'
    state: present
  register: vm_ip_info
  delegate_to: localhost

```

##### EXPECTED RESULTS

Attach existing IP address to the interface.  I have already defined the IP in netbox, but now I want it attached to this interface.

I've tried with and without the /23, multiple combinations.. nothing works.

##### ACTUAL RESULTS

```
{
    "msg": "address does not exist on existing object. Check to make sure valid field.",
    "changed": false,
    "invocation": {
        "module_args": {
            "netbox_url": "http://fafnir.garbled.net",
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "data": {
                "prefix": "192.168.10.0/23",
                "address": "192.168.10.32/23",
                "dns_name": "antares",
                "interface": {
                    "name": "Ethernet",
                    "virtual_machine": "antares"
                },
                "family": null,
                "vrf": null,
                "tenant": null,
                "status": null,
                "role": null,
                "description": null,
                "nat_inside": null,
                "tags": null,
                "custom_fields": null
            },
            "state": "present",
            "validate_certs": true,
            "query_params": null
        }
    },
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {}
}
```

**Comment by ThomasADavis** [comment]
Is the device really called 'Ethernet' you want to add an IP to?  Or is it like 'eth0'.

**Comment by garbled1** [comment]
I did actually name it "Ethernet", I guess eth0 would be better, but, eh.

**Comment by FragmentedPacket** [comment]
You shouldn't need the `prefix` specified here. I assume if you remove that, it should work.

If that does work, I believe we can fix this by adding `mutually_exclusive` to the module to prevent this issue.

**Comment by FragmentedPacket** [comment]
I haven't been able to reproduce this :(

**Comment by FragmentedPacket** [comment]
@garbled1 Any update on this? I would like to get this taken care of you, but haven't been able to reproduce.

**Comment by fdallaca** [comment]
Hi @FragmentedPacket , I have the same issue using collections v1.0.2 on Ansible Tower 3.7.2:

**SOFTWARE VERSIONS**
ansible 2.9.11
python version = 3.6

Netbox:
715e1d13643e (v2.8.7)

Collection:
v1.0.2

**SUMMARY**
Can't create/assign IP to vm interface with netbox_ip_address (same error if the ip already exist).

**STEPS TO REPRODUCE**
```
# Create/Ensure all interface ip
- name: Create/Ensure all ip
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ item | ipaddr('address')}}"
      prefix: "{{ item | ipaddr('network/prefix')}}"
      interface:
        name: "interface_{{ interface_item.name }}"
        virtual_machine: "{{ ext_hostname }}"
  loop: "{{ iparray }}"
```

**ACTUAL RESULTS**
```
{
    "msg": "address does not exist on existing object. Check to make sure valid field.",
    "changed": false,
    "exception": "  File \"/tmp/ansible_netbox.netbox.netbox_ip_address_payload_15kqw_2n/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 885, in _update_netbox_object\n    if serialized_nb_obj[key] != updated_obj[key]:\n",
    "invocation": {
        "module_args": {
            "netbox_url": "***",
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "data": {
                "address": "10.100.8.66",
                "prefix": "10.100.8.0/23",
                "interface": {
                    "name": "interface_311_Server-Backend-3",
                    "virtual_machine": "ansibledeploy11.private.cineca.it"
                },
                "family": null,
                "vrf": null,
                "tenant": null,
                "status": null,
                "role": null,
                "description": null,
                "nat_inside": null,
                "dns_name": null,
                "tags": null,
                "custom_fields": null
            },
            "state": "present",
            "validate_certs": true,
            "query_params": null
        }
    },
    "_ansible_no_log": false,
    "item": "10.100.8.66/23",
    "ansible_loop_var": "item",
    "_ansible_item_label": "10.100.8.66/23"
}
```
