### ISSUE TITLE
Cannot modify a virtual machine

### ISSUE THREAD

**Issue by garbled1** [netbox-community/ansible_modules#316]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.9.1
  config file = None
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

###### Netbox:

2.8.5
###### Collection:

1.0.0
##### SUMMARY

Attempts to modify a virtual machine returns virtual machine already exists.
##### STEPS TO REPRODUCE

```yaml
- name: Mark interface as primary
  netbox.netbox.netbox_virtual_machine:
    netbox_url: '{{ netbox_server }}'
    netbox_token: '{{ netbox_token }}'
    data:
      name: '{{ inventory_hostname_short }}'
      cluster: '{{ vm_cluster }}'
      #virtual_machine_role: 'Server'
      status: 'Active'
      tags:
        - VM
      primary_ip4: '{{ ansible_default_ipv4.address }}'
  register: vm_info
  delegate_to: localhost

```

##### EXPECTED RESULTS

Modify the vm

##### ACTUAL RESULTS

```
{
    "changed": false,
    "msg": "virtual_machine antares already exists",
    "virtual_machine": {
        "id": 29,
        "name": "antares",
        "status": "active",
        "site": 4,
        "cluster": 4,
        "role": 8,
        "tenant": null,
        "platform": null,
        "primary_ip": null,
        "primary_ip4": null,
        "primary_ip6": null,
        "vcpus": null,
        "memory": null,
        "disk": null,
        "comments": "",
        "local_context_data": null,
        "tags": [
            "VM"
        ],
        "custom_fields": {},
        "config_context": {},
        "created": "2020-08-23",
        "last_updated": "2020-08-23T10:38:52.097424-07:00"
    },
    "invocation": {
        "module_args": {
            "netbox_url": "http://fafnir.garbled.net",
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "data": {
                "name": "antares",
                "cluster": "Hydra",
                "status": "Active",
                "tags": [
                    "VM"
                ],
                "primary_ip4": "192.168.10.32",
                "site": null,
                "virtual_machine_role": null,
                "vcpus": null,
                "tenant": null,
                "platform": null,
                "primary_ip6": null,
                "memory": null,
                "disk": null,
                "custom_fields": null
            },
            "state": "present",
            "validate_certs": true,
            "query_params": null
        }
    },
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {}
}
```
