### ISSUE TITLE
Cannot add service to virtual machine

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#317]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
```
ansible 2.9.11
  config file = $PATH_TO_ANSIBLE_PROJECT/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $PATH_TO_ANSIBLE_PROJECT/.venv/lib/python3.5/site-packages/ansible
  executable location = $PATH_TO_ANSIBLE_PROJECT/.venv/bin/ansible
  python version = 3.5.2 (default, Jul 17 2020, 14:04:10) [GCC 5.4.0 20160609]
```

###### Netbox:
`v2.8.7`

###### Collection:
`v1.0.0`

##### SUMMARY
Creating a service using `netbox.netbox.netbox_service` and assigning it to a `virtual_machine` fails because `device` is a required parameter.

##### STEPS TO REPRODUCE
1. Create a virtual machine in netbox.
2. Run the playbook below (define the templated vars).

```yaml
- name: Add service to virtual machine on netbox
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Add service to virtual machine on netbox
      netbox.netbox.netbox_service:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "HTTP"
          port: "80"
          protocol: "TCP"
          virtual_machine: "{{ virtual_machine }}"
        state: present
```

##### EXPECTED RESULTS
The service is successfully assigned to the virtual machine.

```
changed: [localhost]
```

##### ACTUAL RESULTS
The task fails.

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: device found in data"}
```

**Comment by biganthony** [comment]
Take a look at this. If you set 'device' to **NULL** it will work.

```yaml
- name: Create Netbox Service
  hosts: all
  gather_facts: False
  tasks:
    - name: Create node_exporter service
      netbox.netbox.netbox_service:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: null
          virtual_machine: "{{ inventory_hostname }}"
          name: node_exporter
          port: 9100
          protocol: TCP
          ipaddresses:
            - address: "{{ hostvars[inventory_hostname].primary_ip4 }}"
        state: present
      delegate_to: localhost
```
