### ISSUE TITLE
Inventory - IP addresses missing from virtual machine interfaces

### ISSUE THREAD

**Issue by biganthony** [netbox-community/ansible_modules#321]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.9.11
###### Netbox:

2.9.1
###### Collection:

1.0.1
##### SUMMARY

When interfaces is set to TRUE the IP address array is empty for all VMs
##### STEPS TO REPRODUCE

set `interfaces: True` in inventory yml

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: http://netbox
validate_certs: True
config_context: False
services: True
interfaces: True
fetch_all: False
plurals: False

group_by:
  - role

query_filters:
  - cluster_id: 1

compose:
  netbox_vm_id: id
```

##### EXPECTED RESULTS

```json
interfaces": [
  {
   "description": "",
   "enabled": true,
   "id": 4,
   "ip_addresses": [
       "List of IP objects": "Example"
    ],
   "mac_address": null,
   "mode": null,
   "mtu": null,
   "name": "ens18",
   "tagged_vlans": [],
   "tags": [],
   "untagged_vlan": null,
   "url": "http://netbox/api/virtualization/interfaces/4/",
   "virtual_machine": {
    "id": 13,
    "name": "VM NAME",
    "url": "http://i/api/virtualization/virtual-machines/13/"
   }
  }
 ]
```
##### ACTUAL RESULTS

```json
interfaces": [
  {
   "description": "",
   "enabled": true,
   "id": 4,
   "ip_addresses": [],
   "mac_address": null,
   "mode": null,
   "mtu": null,
   "name": "ens18",
   "tagged_vlans": [],
   "tags": [],
   "untagged_vlan": null,
   "url": "http://netbox/api/virtualization/interfaces/4/",
   "virtual_machine": {
    "id": 13,
    "name": "VM NAME",
    "url": "http://i/api/virtualization/virtual-machines/13/"
   }
  }
 ]
```

Might be related to this.
netbox-community/netbox#4721
https://github.com/netbox-community/ansible_modules/issues/319
