### ISSUE TITLE
Can't add vlans by VID

### ISSUE THREAD

**Issue by craigers521** [netbox-community/ansible_modules#336]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
 - Module question

###### Ansible:
ansible 2.9.11

###### Netbox:
(v2.8.8)

###### Collection:
1.0.2

##### SUMMARY
Trying to add tagged and untagged vlans to device interface using the netbox_device_interface module

##### STEPS TO REPRODUCE
When adding a single untagged vlan integer recieve error that "more than one result was recieved", ideally would like to add vlans by vid + vlangroup.  Tagged vlans again, ideally would like to pass in a list of integers of VIDs

```yaml
***test data looks like this: ***

"port_element": [
            {
                "id": "1/1",
                "name": "",
                "tagged": [],
                "trunk_group": "",
                "untagged": 128
            },
            {
                "id": "1/2",
                "name": "",
                "tagged": [],
                "trunk_group": "",
                "untagged": 128
            }, ...etc...


***Playbook task looks like this: ***

- name: add remaining interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ lookup('ENV', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('ENV', 'NETBOX_API_KEY') }}"
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item['id'] }}"
          description: "{{ item['name'] }}"
          type: 1000Base-T (1GE)
          mode: Tagged
          untagged_vlan:
            - vid: "{{ item['untagged'] }}"
              site: cab2
          tagged_vlans:
            - vid: "{{ item['tagged'] }}"
              site: cab2
        state: present
      with_items: "{{aruba_facts['port_element'] }}"

```

##### EXPECTED RESULTS
Each interface to be created and have its list of tagged and untagged vlans added

##### ACTUAL RESULTS

```
The full traceback is:
  File "/var/folders/p3/ncsky8252f3d1gm_jr299mf00000gp/T/ansible_netbox.netbox.netbox_device_interface_payload_o1n9b8q1/ansible_netbox.netbox.netbox_device_interface_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 482, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/usr/local/lib/python3.8/site-packages/pynetbox/core/endpoint.py", line 141, in get
    raise ValueError(
failed: [cab2tcsw1] (item={'id': '1/1', 'name': '', 'trunk_group': '', 'untagged': 128, 'tagged': []}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "description": "",
                "device": "cab2tcsw1",
                "enabled": null,
                "form_factor": null,
                "lag": null,
                "mac_address": null,
                "mgmt_only": null,
                "mode": "Tagged",
                "mtu": null,
                "name": "1/1",
                "tagged_vlans": [
                    {
                        "site": "cab2",
                        "vid": []
                    }
                ],
                "tags": null,
                "type": "1000Base-T (1GE)",
                "untagged_vlan": [
                    {
                        "site": "cab2",
                        "vid": "128"
                    }
                ]
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://netauto-preprod:8000",
            "query_params": null,
            "state": "present",
            "update_vc_child": false,
            "validate_certs": true
        }
    },
    "item": {
        "id": "1/1",
        "name": "",
        "tagged": [],
        "trunk_group": "",
        "untagged": 128
    },
    "msg": "More than one result returned for untagged_vlan"
}
```
