### ISSUE TITLE
group_by tags doesn't work

### ISSUE THREAD

**Issue by paulmcgoldrick** [netbox-community/ansible_modules#337]
##### ISSUE TYPE

 - Bug Report
 

###### Ansible:
2.9.7, 2.9.11
###### Netbox:

e819ca69e2d1 (v2.9.2)
###### Collection:

1.0.2
##### SUMMARY

Parse error when using `group_by` with `tags`
##### STEPS TO REPRODUCE

add `tags` to your `group_by` configuration

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: <ep>
validate_certs: False
token: <tk>
group_by:
  - device_roles
  - tags
```

##### EXPECTED RESULTS

`ansible-inventory` returns a proper inventory with groups defined for tags
##### ACTUAL RESULTS

```
[...]
[WARNING]:  * Failed to parse <...>/netbox.yml with auto plugin: sequence item 1:               
expected str instance, dict found                                      
[...]
```
