### ISSUE TITLE
Registering IP fails

### ISSUE THREAD

**Issue by bqk-** [netbox-community/ansible_modules#342]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.13

###### Netbox:
2.7.4

##### SUMMARY
I am running the following task:
```
- name: Reserve IP address
  netbox.netbox.netbox_ip_address:
      netbox_url: "{{ netbox.url }}"
      netbox_token: "{{ netbox.token }}"
      data:
        prefix: "{{ ipam.prefix }}"
        tenant: "{{ ipam.tenant }}"
        dns_name: "{{ dns_hostname }}"
        interface:
          name: eth0
          device: dummy
      state: present
  register: netbox_result
  throttle: 1
```

And get a python parsing error:
`invalid literal for int() with base 10: &#39;name&#39;`

##### STEPS TO REPRODUCE
Run the following task.

##### EXPECTED RESULTS
Task to register the new IP if missing, otherwise grab the existing IP.

##### ACTUAL RESULTS
`invalid literal for int() with base 10: &#39;name&#39;`

Note: I tried a name without numbers in it for the interface, same error.
