### ISSUE TITLE
how to modify an specific attribute to None 

### ISSUE THREAD

**Issue by dsz211** [netbox-community/ansible_modules#347]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Module question
##### SUMMARY

for example, vlan_119 belong to site: xyz, role:abc, tenant: 123
we want to remove vlan_119's attribute(site/role/tenant).
```
- name: modify vlan"
  collections:
    - netbox.netbox
  netbox_vlan:
    netbox_url: "{{ _netbox_url }}"
    netbox_token: "{{ _netbox_token }}"
    state: "present"
    validate_certs: no
    data:
      name: "vlan_119"
      vid: "11"
      site: 
      tenant: 
      vlan_role: 
    query_params:
      - vid
      - group
      - site
```
but it did not change anyting of the role/site/tennat
 ##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

 remove vlan_119's attribute(site/role/tenant).
##### ACTUAL RESULTS

nothing changed

```

```
