### ISSUE TITLE
Cannot control what attributes make ip address objects unique using query_params

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#372]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

```
ansible 2.10.2
  config file = $ANSIBLE_PROJECT/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/.ansible/venv/lib/python3.5/site-packages/ansible
  executable location = $HOME/.ansible/venv/bin/ansible
  python version = 3.5.2 (default, Oct  7 2020, 17:19:02) [GCC 5.4.0 20160609]
```

###### Netbox:

`v2.9.8`

###### Collection:

`v1.1.0`

##### SUMMARY

In the past I have used the `query_params` parameter to enable assigning already existing ip addresses to a device.
This doesn't seem to work anymore as it still creates a new ip address object whenever
the same ip address is added to a device interface.
I would expect that setting `query_params` to `["address", "vrf"]` means that the address and vrf values
make an ip address object unique, and therefore allow you to assign an existing ip address to an interface or different interface.

##### STEPS TO REPRODUCE

1. Add device to netbox called `netbox-testvm` and add an interface with the name `eth0`.
2. Run the playbook below (define the templated vars).

```yaml
- name: Test netbox_ip_address query_params
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Add ip address to netbox and don't assign it to a device
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: 192.168.0.1/24
        query_params:
          - address
          - vrf
        state: present

    - name: Assign same ip address to a device
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: 192.168.0.1/24
          assigned_object:
            device: netbox-testvm
            name: eth0
        query_params:
          - address
          - vrf
        state: present
```

##### EXPECTED RESULTS

The ip address added from the first task is assigned to the device in the second task.

```
TASK [Add ip address to netbox and don't assign it to a device] ********************
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "state": "absent"
+    "state": "present"
 }

changed: [localhost]

TASK [Assign same ip address to a device] ********************
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "assigned_object": null
+    "assigned_object": 1
 }

changed: [localhost]
```

##### ACTUAL RESULTS

The ip address was added twice.

```
TASK [Add ip address to netbox and don't assign it to a device] ********************
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "state": "absent"
+    "state": "present"
 }

changed: [localhost]

TASK [Assign same ip address to a device] ********************
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "state": "absent"
+    "state": "present"
 }

changed: [localhost]
```
