### ISSUE TITLE
netbox.netbox_ip_address confusing deprecation warning

### ISSUE THREAD

**Issue by garbled1** [netbox-community/ansible_modules#373]
##### ISSUE TYPE

 - Documentation update

###### Ansible:

ansible 2.9.1
  config file = None
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

###### Netbox:
2.9.8

###### Collection:
1.1.0

##### SUMMARY
If I set 'data: family: 4'  I get the following deprecation warning.  But the documentation for the module doesn't say anything about this being deprecated, and we are well past 0.3.0, so I'm totally confused as to if I should use this or not?

[DEPRECATION WARNING]: Param 'data["family"]' is deprecated. See the module 
docs for more information. This feature will be removed in version 0.3.0. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

##### STEPS TO REPRODUCE

```yaml
- name: Request a new IP, and assign it to the interface
  netbox.netbox.netbox_ip_address:
    netbox_url: '{{ netbox_server }}'
    netbox_token: '{{ netbox_token }}'
    data:
      prefix: '{{ netbox_prefix }}'
      vrf: '{{ netbox_vrf }}'
      family: 4
      status: Reserved
      dns_name: '{{ vm_name }}.{{ domainname }}'
      assigned_object:
        name: '{{ vm_interface_name }}'
        virtual_machine: '{{ vm_name }}'
    state: new
```

##### EXPECTED RESULTS
Documentation consistent with deprecation warning, or remove the warning if it's not true?

##### ACTUAL RESULTS
confusion.
