### ISSUE TITLE
Method PATCH not allowed when updating VM or any interface (possibly more?)

### ISSUE THREAD

**Issue by garbled1** [netbox-community/ansible_modules#374]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.9.1
config file = None
configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

###### Netbox:

2.9.8
pynetbox 5.0.7

###### Collection:

1.1.0

##### SUMMARY
Attempt to update a VM's settings, get Method PATCH not allowed

##### STEPS TO REPRODUCE

```yaml
- name: Set the primary v4 addr
  netbox.netbox.netbox_virtual_machine:
    netbox_url: '{{ netbox_server }}'
    netbox_token: '{{ netbox_token }}'
    data:
      name: '{{ vm_name }}'
      primary_ip4: '{{ vm_assigned_ip_record["value"]["address"].split("/")[0] }}'
  register: vm_info_new
  delegate_to: localhost

```

##### EXPECTED RESULTS

Update the vm with primary_ip4

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File \"/home/awx/.ansible/tmp/ansible-tmp-1604666690.0729764-8685-4023590615692/AnsiballZ_netbox_virtual_machine.py\", line 102, in <module>
    _ansiballz_main()
  File \"/home/awx/.ansible/tmp/ansible-tmp-1604666690.0729764-8685-4023590615692/AnsiballZ_netbox_virtual_machine.py\", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/awx/.ansible/tmp/ansible-tmp-1604666690.0729764-8685-4023590615692/AnsiballZ_netbox_virtual_machine.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_virtual_machine', init_globals=None, run_name='__main__', alter_sys=True)
  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_netbox.netbox.netbox_virtual_machine_payload_m9_ez4c7/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py\", line 249, in <module>
  File \"/tmp/ansible_netbox.netbox.netbox_virtual_machine_payload_m9_ez4c7/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_virtual_machine.py\", line 245, in main
  File \"/tmp/ansible_netbox.netbox.netbox_virtual_machine_payload_m9_ez4c7/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_virtualization.py\", line 69, in run
  File \"/tmp/ansible_netbox.netbox.netbox_virtual_machine_payload_m9_ez4c7/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 962, in _ensure_object_exists
  File \"/tmp/ansible_netbox.netbox.netbox_virtual_machine_payload_m9_ez4c7/ansible_netbox.netbox.netbox_virtual_machine_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 941, in _update_netbox_object
  File \"/var/lib/awx/venv/ansible/lib/python3.7/site-packages/pynetbox/core/response.py\", line 419, in update
    return self.save()
  File \"/var/lib/awx/venv/ansible/lib/python3.7/site-packages/pynetbox/core/response.py\", line 391, in save
    if req.patch({i: serialized[i] for i in diff}):
  File \"/var/lib/awx/venv/ansible/lib/python3.7/site-packages/pynetbox/core/query.py\", line 409, in patch
    return self._make_call(verb=\"patch\", data=data)
  File \"/var/lib/awx/venv/ansible/lib/python3.7/site-packages/pynetbox/core/query.py\", line 274, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 405 Method Not Allowed: {'detail': 'Method \"PATCH\" not allowed.'}
```

**Comment by FragmentedPacket** [comment]
Please upgrade `pynetbox` and see if the issue is resolved.

**Comment by garbled1** [comment]
It does still exist with pynetbox 5.1.0.

**Comment by garbled1** [comment]
So did some digging with tcpdump:
```
PATCH /api/virtualization/virtual-machines/ HTTP/1.1
{"primary_ip4": 656}
```

Which I think is the problem.  The API reference shows there is a PATCH method for /virtualization​/virtual-machines​/{id}​/  but only GET/PUT for without the /{id}/.  So when you do a partial like that, you need to change the url to the /id/ style..  not sure if thats in pynetbox or the module...

**Comment by garbled1** [comment]
Actually, this problem seems to be worse than what I said earlier.  It appears I can't modify anything I've tried.  For example, if I try to just update the interface of a device with a new mac_address, I get the same error.  I largely suspect it's the same issue, that it's always going to the base URL, and not the URL/id/.  This happens for both cases of the below code.

```
---
- name: find an ip in netbox and root out its interface, update the MAC
  hosts: localhost
  connection: local
  collections:
    - netbox.netbox
  vars_files:
    - vars/passwords.yml
  vars:
    ip_to_find: 192.168.10.9
    mac_of_ip: '00:aa:aa:aa:aa:aa'

  roles:
    - network_settings

  tasks:

    - name: hunt for the IP
      set_fact:
        ip_record: '{{ query("netbox.netbox.nb_lookup", "ip-addresses", api_filter="address="+ip_to_find, api_endpoint=netbox_server, token=netbox_token) }}'

    - name: if VM, update the mac on this iface
      netbox.netbox.netbox_vm_interface:
        netbox_url: '{{ netbox_server }}'
        netbox_token: '{{ netbox_token }}'
        data:
          virtual_machine: '{{ ip_record[0]["value"]["assigned_object"]["virtual_machine"]["name"] }}'
          name: '{{ ip_record[0]["value"]["assigned_object"]["name"] }}'
          mac_address: '{{ mac_of_ip }}'
      when:
        - ip_record | length == 1
        - ip_record[0]['value']['assigned_object_type'] == 'virtualization.vminterface'

    - name: If device, update the mac on the interface
      netbox.netbox.netbox_device_interface:
        netbox_url: '{{ netbox_server }}'
        netbox_token: '{{ netbox_token }}'
        data:
          device: '{{ ip_record[0]["value"]["assigned_object"]["device"]["name"] }}'
          name: '{{ ip_record[0]["value"]["assigned_object"]["name"] }}'
          mac_address: '{{ mac_of_ip }}'
      when:
        - ip_record | length == 1
        - ip_record[0]['value']['assigned_object_type'] == 'dcim.interface'

```
