### ISSUE TITLE
netbox_device appears to be ignoring `validate_certs: no`

### ISSUE THREAD

**Issue by tomkivlin** [netbox-community/ansible_modules#375]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.9.4

###### Netbox:

v2.8.5

###### Collection:

netbox.netbox:1.1.0

##### SUMMARY

Using the `netbox_device` module, I am unable to connect to the Netbox server and I see SSL errors in the verbose output, despite `validate_certs: no` being set in the playbook.

##### STEPS TO REPRODUCE

Using the playbook below, run `ansible-playbook playbook.yaml -vvvv`

```yaml
- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  collections:
    - netbox.netbox
  gather_facts: False

  tasks:
    - name: Update device 
      netbox_device:
        netbox_url: http://netbox.url.com
        netbox_token: abcdefghetc.
        validate_certs: no
        data:
          name: Device Name
          rack: Rack Name
          face: front
          position: 17
        state: present
```

##### EXPECTED RESULTS

Successful update of the device.

##### ACTUAL RESULTS

I get an SSL error.

```
The full traceback is:
  File "/var/folders/cs/7rgwynld4wv3jxk7f4dytrp9l4z1zl/T/ansible_netbox_device_payload_dptx51j5/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 475, in _connect_netbox_api
    self.version = float(nb.version)
  File "/Users/kivlint/.virtualenvs/ansible-jan2020/lib/python3.7/site-packages/pynetbox/core/api.py", line 126, in version
    base=self.base_url, http_session=self.http_session,
  File "/Users/kivlint/.virtualenvs/ansible-jan2020/lib/python3.7/site-packages/pynetbox/core/query.py", line 200, in get_version
    req = self.http_session.get(self.normalize_url(self.base), headers=headers,)
  File "/Users/kivlint/.virtualenvs/ansible-jan2020/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Users/kivlint/.virtualenvs/ansible-jan2020/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kivlint/.virtualenvs/ansible-jan2020/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kivlint/.virtualenvs/ansible-jan2020/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "custom_fields": null,
                "device_role": null,
                "device_type": null,
                "face": "front",
                "local_context_data": null,
                "name": "Device Name",
                "platform": null,
                "position": 17,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": "Rack Name",
                "serial": null,
                "site": null,
                "status": null,
                "tags": null,
                "tenant": null,
                "vc_position": null,
                "vc_priority": null,
                "virtual_chassis": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://netbox.url.com",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "Failed to establish connection to Netbox API"
}
```
