### ISSUE TITLE
Netbox_Vlan does not respect vlan in other vlan_groups

### ISSUE THREAD

**Issue by nilssl** [netbox-community/ansible_modules#381]
ISSUE TYPE

    Bug Report

SOFTWARE VERSIONS
Ansible:

ansible 2.10.1
Netbox: v2.9.9
Collection: netbox.netbox:1.1.0
SUMMARY

When having a setup which is using the same VLAN on different devices and identifying uniqueness by vlan group, the ansible module changes the VLAN from one group to another instead of making a new VLAN within the right group.

STEPS TO REPRODUCE

Using the playbook below, run ansible-playbook playbook.yaml

```
- name: "Create VLAN and VLAN groups"
  connection: local
  hosts: localhost
  collections:
    - netbox.netbox
  gather_facts: False

  tasks:
    - name: Create vlan group1
      netbox_vlan_group:
        netbox_url: netbox
        netbox_token: abcdefgh
        data:
           name: group1
           site: site1

    - name: Create vlan group2
      netbox_vlan_group:
        netbox_url: netbox
        netbox_token: abcdefgh
        data:
           name: group2
           site: site1
    - name: Create vlan
      netbox_vlan:
        netbox_url: netbox
        netbox_token: abcdefgh
        data:
           name: host_vlan
           vlan_group: group1
           site: site1
           vid: 100

    - name: Create vlan
      netbox_vlan:
        netbox_url: netbox
        netbox_token: abcdefgh
        data:
           name: host_vlan
           vlan_group: group2
           site: site1
           vid: 100
```

EXPECTED RESULTS

Two groups is created, one vlan gets created for each group.

ACTUAL RESULTS

Two groups is created, only one vlan gets created and moved from group 1 to group 2

ACTUAL RESULTS on play nr2

The groups are still there "Green"

Vlan100 is moved between group1 and group2.
