### ISSUE TITLE
Enhancement: Add option to use the virtual chassis name as inventory_hostname

### ISSUE THREAD

**Issue by nahun** [netbox-community/ansible_modules#382]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:

2.9 or 2.10

###### Netbox:

2.9.10

###### Collection:

devel

##### SUMMARY

The inventory plugin returns virtual chassis masters and uses the master's name as the host name (inventory_hostname). I'd like to use the virtual chassis name instead as the name in the inventory. Adding an option can pretty easily add that. I will be submitting a PR.

##### STEPS TO REPRODUCE

Example inventory options file:
```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.example.com

virtual_chassis_name: yes
```

##### EXPECTED RESULTS

New behavior would only change the host name to a master device to the virtual chassis name. Nothing else in the host vars would change. For example the display name would still show the master device name. The tags would still be from the master device.
