### ISSUE TITLE
Lookup Plugin Support Environment Lookup

### ISSUE THREAD

**Issue by jvanderaa** [netbox-community/ansible_modules#390]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:
2.10.4

###### Netbox:
2.9.10

###### Collection:
1.1.0

##### SUMMARY
To support the use of environment variables for the NetBox URL and NetBox Token, which will help clean up code

##### STEPS TO REPRODUCE
Set the environment
Look to get at the data without having to add the key/value pair for NetBox

```yaml
- name: "GET SITES WITH NB_QUERY"
      set_fact:
        sites: "{{ query('netbox.netbox.nb_lookup', 'sites') }}"
```

##### EXPECTED RESULTS

Would expect to get the data

##### ACTUAL RESULTS

Get an error that these were not set.
