### ISSUE TITLE
Bug: netbox_ip_address does not add IP to interface under most scenarios

### ISSUE THREAD

**Issue by slinderud** [netbox-community/ansible_modules#399]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
ansible 2.10.4

###### Netbox:
Netbox 2.10.1

###### Collection:
Devel

##### SUMMARY
When using netbox_ip_address there is a few inconsistencies when trying to create a new IP and bind it to an interface on a VM.

##### STEPS TO REPRODUCE AND ACTUAL RESULTS
1. Interface, state: present
This will create the IP address. But not bind it to the interface
```
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: False
        data:
          prefix: "{{ prefix }}"
          interface:
            name: eth0
            virtual_machine: "{{ hostname }}" 
        state: present
```

2. Interface, state: new
This will create the IP address. But not bind it to the interface
```
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: False
        data:
          prefix: "{{ prefix }}"
          interface:
            name: eth0
            virtual_machine: "{{ hostname }}" 
        state: new
```

3. Assigned_object, state: present
error: `"msg": "A prefix and interface is required"`
```
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: False
        data:
          prefix: "{{ prefix }}"
          assigned_object:
            name: eth0
            virtual_machine: "{{ hostname }}" 
        state: present
```

4.Assigned_object, state: new
This will create the ip address, and bind it to the interface
```
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: False
        data:
          prefix: "{{ prefix }}"
          assigned_object:
            name: eth0
            virtual_machine: "{{ hostname }}" 
        state: new
```

##### EXPECTED RESULTS
Since interface and assigned_object is mutually exclusive, they should give consistent behaviour.
And new/present should create the IP and bind it to the interface of the VM by using both assigned_object and interface.

Again, thanks for your fantastic work :)
