### ISSUE TITLE
[Feature]: Module Defaults (group/netbox)

### ISSUE THREAD

**Issue by FragmentedPacket** [netbox-community/ansible_modules#411]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Implement `module_defaults` to the NetBox collection.

The implementation required is within `meta/runtime.yml` with adding the `action_groups` keyword.

E.g.

```yaml
---
action_groups:
  netbox:
    - netbox_device
    - netbox_ip_addresses
    - etc.
```

This should allow users to define `module_defaults` and supply the following in a playbook and then omit those parameters from the tasks themself:

```yaml
---
- hosts: localhost
   module_defaults:
     group/netbox:
       netbox_url: ....
       netbox_token: .....
```

More info [here](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html).
