### ISSUE TITLE
ENFORCE_GLOBAL_UNIQUE w/existing IP interface assignments for netbox_ip_address

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/ansible_modules#413]
##### ISSUE TYPE

 - Module question

###### Ansible:
2.10.4

###### Netbox:
2.10.3

###### Collection:
1.2.1

###### pynetbox:
5.0.8 - 5.3.0 ( I tested with all jus in case)

##### SUMMARY
Existing IPs not assigned to interfaces cannot be assigned to an interface (that has no IP assigned) using netbox_ip_address when unique IPs are enforced by NetBox and the IP address's netmask does not match a parent prefix with the same netmask.

Not sure what the correct approach here should be.  This could be as planned, but I thought this used to work when I tested the middle of last year.

##### STEPS TO REPRODUCE
1.) Enable `ENFORCE_GLOBAL_UNIQUE` in NetBox.
2.) Add an IP to NetBox, but do not assign to an interface and do not create a parent prefix with the same netmask.
3.) Create a new interface on any device.
4.) Use netbox_ip_address to assign said IP to the previous interface.

```yaml
    - name: Add IP Addresses into NetBox
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox.url }}"
        netbox_token: "{{ netbox.token }}"
        data:
          address: 10.10.114.1/24
          dns_name: switch_vl730.test.com
          assigned_object:
            device: switch
            name: Vlan730
```

##### EXPECTED RESULTS
I would expect the existing IP to now be assigned to the interface, and any other updates like dns_name to be updated if any changes.

##### ACTUAL RESULTS
Ansible task fails because NetBox reports the IP is existing/duplicate
