### ISSUE TITLE
2.0.0 broke duplicate IPs for IPs set with a non-null role

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/ansible_modules#432]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/test-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test-user/.local/lib/python3.8/site-packages/ansible
  executable location = /home/test-user/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

###### Netbox:

v2.10.4

###### Collection:

2.0.0

##### SUMMARY

After the release of 2.0.0 You can no longer add duplicate IPs even with a role set on the IP that provides the NetBox exception to the unique IP enforcement.  This feature was introduced in 1.2.1 originally.

If duplicate IPs exist with a role assigned and different interfaces assigned, the module will report back that the IP already exists and cannot be updated.

If you delete all duplicate IPs and try to create 2 new duplicate IPs just assigned to different interfaces/devices, 2 IPs are not created in netbox, but instead the existing IP address record is reassigned to whatever the last device/interface the module entered the record for.  IE it just moves the record's assignment per the changelog detail.

If any of the links I provide break or data is wiped, we can just run the playbook again.

##### STEPS TO REPRODUCE

With netbox.netbox:1.2.1 the below works [as expected](https://master.netbox.dev/ipam/ip-addresses/?q=ansible-netbox-1.2.1).  The duplicate addresses are created and associated to each device/interface in the playbook.
```yaml 
- name: NetBox Ansible Module 1.2.1
  hosts: localhost
  gather_facts: no

  vars:
    data:
      - address: 121.121.121.121/32
        assigned_object:
          device: B1_disty_switch
          name: ge1/0/0
        description: ansible-netbox-1.2.1
        dns_name: ansible-netbox-1.2.1
        role: HSRP
        status: Active
      - address: 121.121.121.121/32
        assigned_object:
          device: NB-TEST-SWITCH
          name: ge-0/0/0
        description: ansible-netbox-1.2.1
        dns_name: ansible-netbox-1.2.1
        role: HSRP
        status: Active
      - address: 1.121.121.121/32
        assigned_object:
          device: B1_disty_switch
          name: ge1/0/0
        description: ansible-netbox-1.2.1
        dns_name: ansible-netbox-1.2.1
        role: HSRP
        status: Active
      - address: 1.121.121.121/32
        assigned_object:
          device: NB-TEST-SWITCH
          name: ge-0/0/0
        description: ansible-netbox-1.2.1
        dns_name: ansible-netbox-1.2.1
        role: HSRP
        status: Active

  tasks:
    - name: Create or Update IP addresses
      netbox_ip_address:
        netbox_url: https://master.netbox.dev
        netbox_token: f33d962bc0c3cd28692733b73ef3ff17e27571e8
        data: "{{ item }}"
      loop: "{{ data }}"
```

With netbox.netbox:2.0.0 the below works [NOT as expected](https://master.netbox.dev/ipam/ip-addresses/?q=ansible-netbox-2.0.0).  The duplicate addresses are moved from one device to the other if you look at the address changelog and output of the search.
```yaml 
- name: NetBox Ansible Module 2.0.0
  hosts: localhost
  gather_facts: no

  vars:
    data:
      - address: 200.200.200.200/32
        assigned_object:
          device: B1_disty_switch
          name: ge1/0/0
        description: ansible-netbox-2.0.0
        dns_name: ansible-netbox-2.0.0
        role: HSRP
        status: Active
      - address: 200.200.200.200/32
        assigned_object:
          device: NB-TEST-SWITCH
          name: ge-0/0/0
        description: ansible-netbox-2.0.0
        dns_name: ansible-netbox-2.0.0
        role: HSRP
        status: Active
      - address: 2.200.200.200/32
        assigned_object:
          device: B1_disty_switch
          name: ge1/0/0
        description: ansible-netbox-2.0.0
        dns_name: ansible-netbox-2.0.0
        role: HSRP
        status: Active
      - address: 2.200.200.200/32
        assigned_object:
          device: NB-TEST-SWITCH
          name: ge-0/0/0
        description: ansible-netbox-2.0.0
        dns_name: ansible-netbox-2.0.0
        role: HSRP
        status: Active

  tasks:
    - name: Create or Update IP addresses
      netbox_ip_address:
        netbox_url: https://master.netbox.dev
        netbox_token: f33d962bc0c3cd28692733b73ef3ff17e27571e8
        data: "{{ item }}"
      loop: "{{ data }}"
```

With netbox.netbox:2.0.0  & query_params usage the below works [NOT as expected](https://master.netbox.dev/ipam/ip-addresses/?q=ansible-netbox-2.0.0_QP).  The duplicate addresses are moved from one device to the other if you look at the address changelog and output of the search.
```yaml 
- name: NetBox Ansible Module 2.0.0 with query_params
  hosts: localhost
  gather_facts: no

  vars:
    data:
      - address: 202.202.202.202/32
        assigned_object:
          device: B1_disty_switch
          name: ge1/0/0
        description: ansible-netbox-2.0.0_QP
        dns_name: ansible-netbox-2.0.0_QP
        role: HSRP
        status: Active
      - address: 202.202.202.202/32
        assigned_object:
          device: NB-TEST-SWITCH
          name: ge-0/0/0
        description: ansible-netbox-2.0.0_QP
        dns_name: ansible-netbox-2.0.0_QP
        role: HSRP
        status: Active
      - address: 2.202.202.202/32
        assigned_object:
          device: B1_disty_switch
          name: ge1/0/0
        description: ansible-netbox-2.0.0_QP
        dns_name: ansible-netbox-2.0.0_QP
        role: HSRP
        status: Active
      - address: 2.202.202.202/32
        assigned_object:
          device: NB-TEST-SWITCH
          name: ge-0/0/0
        description: ansible-netbox-2.0.0_QP
        dns_name: ansible-netbox-2.0.0_QP
        role: HSRP
        status: Active

  tasks:

    - name: Create or Update IP addresses
      netbox_ip_address:
        netbox_url: https://master.netbox.dev
        netbox_token: f33d962bc0c3cd28692733b73ef3ff17e27571e8
        data: "{{ item }}"
        query_params:
          - address
          - assigned_object
          - description
      loop: "{{ data }}"

```

##### EXPECTED RESULTS

Whether it works or not as expected, the output is generally the same.  I sometimes find odd behaviors in 2.0.0 if I edit records created by 1.2.1 and it does not know which to update, so it just complains that the record is a duplicate.  If a solution/fix is proposed, I can test with the above playbooks and also test updating a record created by 1.2.1 and the patch for 2.0.0.

Here is an expected result in Netbox itself: https://master.netbox.dev/ipam/ip-addresses/?q=ansible-netbox-1.2.1

##### ACTUAL RESULTS

https://master.netbox.dev/ipam/ip-addresses/?q=ansible-netbox-2.0.0
