### ISSUE TITLE
Cannot add tags to netbox_cable

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#448]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
2.10.6

###### Netbox:
2.10.5

###### Collection:
1.2.1

##### SUMMARY
When you use the `netbox_cable` module and set `data.tags` the task fails.

Also, the [documentation](https://docs.ansible.com/ansible/latest/collections/netbox/netbox/netbox_cable_module.html) doesn't show you can set tags, but you can definitely add tags to cables in netbox.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Add netbox cable with tag
      netbox.netbox.netbox_cable:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          termination_a:
            device: netbox-test
            name: eth0
          termination_a_type: dcim.interface
          termination_b:
            device: netbox-test2
            name: eth0
          termination_b_type: dcim.interface
          tags:
            - test
        state: present
```

##### EXPECTED RESULTS

The cable is added successfully to netbox with the tag.

##### ACTUAL RESULTS

The task fails and the cable is not added to netbox.

```
TASK [Add netbox cable with tag] ********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (netbox.netbox.netbox_cable) module: tags found in data. Supported parameters include: color, label, length, length_unit, status, termination_a, termination_a_type, termination_b, termination_b_type, type"}
```
