### ISSUE TITLE
Can Not Set Device Status

### ISSUE THREAD

**Issue by DCAuto** [netbox-community/ansible_modules#449]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.17

###### Netbox:
v2.10.4

###### Collection:
1.2.0

##### SUMMARY
Trying to set a device status returns the following:

{"status": ["0 is not a valid choice."]}

##### STEPS TO REPRODUCE
```
    - name: Create base device
      netbox_device:
        netbox_url: https://netbox.dc.psu.edu:3389
        netbox_token: "{{ Key }}"
        data:
          name: "{{ inventory_hostname }}"
          status: 0
        state: present
        validate_certs: no
      register: device
```
Using int(0) or str('Offline') or str('offline') for the status returns the same error.

##### EXPECTED RESULTS
Device status to change to Offline, or any other option desired

##### ACTUAL RESULTS
```
fatal: [qfx-5110-32q-172.31.12.247]: FAILED! => {"changed": false, "msg": {"status": ["0 is not a valid choice."]}}
```
