### ISSUE TITLE
[Bug]: netbox_service finds multiple addresses instead of one

### ISSUE THREAD

**Issue by fheinonen** [netbox-community/ansible_modules#470]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.10.6
###### Netbox:

2.10.5
###### Collection:

3.0.0
##### SUMMARY

netbox_service returns `"msg": "More than one result returned for ipaddresses"` when specifying virtual_machine id or name
##### STEPS TO REPRODUCE
1. add two virtual machines with both having a loopback interface with address 127.0.0.1/8
2. Add services with netbox.netbox.netbox_service module with an 127.0.0.1/8 IP address     

```yaml
   - name: Gather facts on listening ports
     community.general.listen_ports_facts:
     become: True

   - name: Create TCP or UDP loopback service
      netbox.netbox.netbox_service:
        netbox_url: "{{ lookup('ENV', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('ENV', 'NETBOX_API_KEY') }}"
        data:
          virtual_machine: "{{ inventory_hostname }}"
          name: "{{ item.name }}"
          port: "{{ item.port }}"
          protocol: "{{ item.protocol }}"
          ipaddresses: 
            - address: 127.0.0.1/8
        state: present
      delegate_to: localhost
      when: item.address == "127.0.0.1"
      loop: "{{ ansible_facts.tcp_listen + ansible_facts.udp_listen }}"
```

##### EXPECTED RESULTS

Expecting netbox to find one virtual machine loopback interface address, instead of multiple
##### ACTUAL RESULTS

The following error happened when running the playbook: `"msg": "More than one result returned for ipaddresses"`

```
   "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "custom_fields": null,
                "description": null,
                "device": null,
                "ipaddresses": {
                    "address": "127.0.0.1/8"
                },
                "name": "chronyd",
                "port": 323,
                "ports": null,
                "protocol": "udp",
                "tags": null,
                "virtual_machine": "machine1.example.com"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.example.com",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
```
