### ISSUE TITLE
nb_lookup doc displays wrong type for validate_certs parameter

### ISSUE THREAD

**Issue by mathieu-mp** [netbox-community/ansible_modules#476]
##### ISSUE TYPE
 - Documentation update

###### Collection:
3.0.0

##### SUMMARY
nb_lookup documentation mentions ``string`` type for validate_certs parameter and ``yes`` default, while it should be ``boolean`` and ``True`` default.

**Comment by inigoleaga** [comment]
Hello @mathieu-mp,

Do you know how it should be written in a playbook? I'm trying this with no luck:

'''yaml
- name: Obtain list of devices from Netbox
      ansible.builtin.debug:
        msg:
        - "Device {{ item.value.display_name }} (ID: {{ item.key }}) was manufactured by {{ item.value.device_type.manufacturer.name }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'circuits', api_endpoint='https://mynetbox.domain.es',validate_certs='False', token='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA') }}"
      delegate_to: localhost
```

Thanks in advance,

**Comment by mathieu-mp** [comment]
Hi @inigoleaga 

This is how I call it, with False as a boolean (unquoted) :
```yaml
- debug:
    var: vms_list
  vars:
    vms_list: "{{ query('netbox.netbox.nb_lookup', 'virtual-machines', validate_certs=False) }}"
```

I provide ``NETBOX_API`` & ``NETBOX_TOKEN`` as env variables.  
My URL differs from your example, as it looks like 'https://mynetbox.domain.es/' with an ending ``/``

Hope this helps

**Comment by inigoleaga** [comment]
Hello @mathieu-mp,

Thanks for you message. I have tried like this:

```yaml
    - name: Obtain list of devices from Netbox
      ansible.builtin.debug:
        msg:
        - "Device {{ item.value.display_name }} (ID: {{ item.key }}) was manufactured by {{ item.value.device_type.manufacturer.name }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices', api_endpoint='https://mynetbox.domain.es/', validate_certs=False, token='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA') }}"
      delegate_to: localhost
```

But I'm still getting the same error:

```
ERROR! An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'requests.exceptions.SSLError'>, original message: HTTPSConnectionPool(host='mynetbox.domain.es', port=443): Max retries exceeded with url: /api/dcim/devices/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
````

Maybe I'm doing something else wrong...
