### ISSUE TITLE
Creating a virtual chassis modifies existing one

### ISSUE THREAD

**Issue by gardar** [netbox-community/ansible_modules#477]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.10.7

###### Netbox:

08f02a9b1133 (v2.9.9)

###### Collection:

3.0.0

##### SUMMARY

If create a virtual chassis with netbox.netbox.netbox_virtual_chassis and supply only a name, then if I do it again specifying another name then the chassis I created previously gets updated with the new name and a second chassis does not get created.

##### STEPS TO REPRODUCE

Run a playbook with netbox.netbox.netbox_virtual_chassis supplying only name as data twice with different names.

```yaml
- netbox.netbox.netbox_virtual_chassis:                          
    netbox_url: "{{ url }}"                
    netbox_token: "{{ token }}"            
    validate_certs: "{{ validate_certs }}" 
    data:                                                        
      name: "{{ virtual_chassis_name1 }}"        

- netbox.netbox.netbox_virtual_chassis:                          
    netbox_url: "{{ url }}"                
    netbox_token: "{{ token }}"            
    validate_certs: "{{ validate_certs }}" 
    data:                                                        
      name: "{{ virtual_chassis_name2 }}"        

```

##### EXPECTED RESULTS

Two virtual chassis to be created

##### ACTUAL RESULTS

Only one virtual chassis is created, and the name of it is updated on the second run.

```

```
