### ISSUE TITLE
[Bug]: Editing interfaces for a device in a virtual chassis

### ISSUE THREAD

**Issue by netixx** [netbox-community/ansible_modules#480]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.9.10 (AWX)

###### Netbox:

v2.10.8

###### Collection:

v3.0.0

##### SUMMARY

When editing interfaces for master devices which belong to a virtual chassis, netbox will include the slave interfaces in the results. It is common for interfaces to have the same name for a master and a slave (eg. firewall cluster).
The module calls `self._nb_endpoint_get` which will fail if multiple matches are found.
This breaks the `netbox_device_interface` module when trying to edit interfaces from a master device.

##### STEPS TO REPRODUCE

```yaml
netbox_device_interface:
data:
  device": "xx"
  name: "Port 16"
  lag:
    name: "xxx_lag"
    device: "xx"
```

##### EXPECTED RESULTS

Interface of the master device is updated.

##### ACTUAL RESULTS

Module failure:

```
"msg": "More than one result returned for Port 16",
```
