### ISSUE TITLE
Unable to update an existing IP

### ISSUE THREAD

**Issue by tortuegenialez** [netbox-community/ansible_modules#481]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.16 and 2.10.4

###### Netbox:
v2.9.3

###### Collection:
3.0.0 (devel branch)

##### SUMMARY
Unable to update an existing IP

##### STEPS TO REPRODUCE
Run the following playbook:

```yaml
- name: Create IP address within Netbox with only required information
  netbox_ip_address:
    netbox_url: http://netbox.local
    netbox_token: thisIsMyToken
    data:
      address: 192.168.1.42/24
    state: present

- name: Attach a previously created IP (192.168.1.42/24) to GigabitEthernet1 (NetBox 2.9+)
  netbox_ip_address:
    netbox_url: http://netbox.local
    netbox_token: thisIsMyToken
    data:
      address: 192.168.1.42/24
      vrf: Test
      assigned_object:
        name: GigabitEthernet1
        device: test100
    state: present
```
##### EXPECTED RESULTS
Creation of 192.168.1.42, then update it to be attached to device test100 on interface GigabitEthernet1 
##### ACTUAL RESULTS
2 IP created:
```
TASK [Create IP address within Netbox with only required information] ****************************************************************************************************************
--- before
+++ after
@@ -1 +1 @@
-state: absent
+state: present

changed: [localhost] => changed=true
  ip_address:
    address: 192.168.1.42/24
    assigned_object: null
    assigned_object_id: null
    assigned_object_type: null
    created: '2021-04-01'
    custom_fields: {}
    description: ''
    dns_name: ''
    family: 4
    id: 3290
    last_updated: '2021-04-01T09:01:10.504520Z'
    nat_inside: null
    nat_outside: null
    role: null
    status: active
    tags: []
    tenant: null
    url: http://netbox.local/api/ipam/ip-addresses/3290/
    vrf: null
  msg: ip_address 192.168.1.42/24 created

TASK [Attach a new available IP of 192.168.1.0/24 to GigabitEthernet1 (NetBox 2.9+)] *************************************************************************************************
--- before
+++ after
@@ -1 +1 @@
-state: absent
+state: present

changed: [localhost] => changed=true
  ip_address:
    address: 192.168.1.42/24
    assigned_object: 74
    assigned_object_id: 74
    assigned_object_type: dcim.interface
    created: '2021-04-01'
    custom_fields: {}
    description: ''
    dns_name: ''
    family: 4
    id: 3291
    last_updated: '2021-04-01T09:01:11.721921Z'
    nat_inside: null
    nat_outside: null
    role: null
    status: active
    tags: []
    tenant: null
    url: http://netbox.local/api/ipam/ip-addresses/3291/
    vrf: 1
  msg: ip_address 192.168.1.42/24 created
```

**Comment by tortuegenialez** [comment]
It looks to me that when the [_handle_state_new_present](https://github.com/netbox-community/ansible_modules/blob/devel/plugins/module_utils/netbox_ipam.py#L206) function is called `self.nb_object` is null because `object_query_params` contains ids for the device, not only the IP: `{'assigned_object': 74, 'assigned_object_id': 74, 'address': '192.168.1.42/24', 'vrf_id': 1, 'interface_id': 74}`.
So when `_ensure_object_exists` is called, it will call `_create_netbox_object` instead of `_update_netbox_object`

**Comment by tortuegenialez** [comment]
Attached PR https://github.com/netbox-community/ansible_modules/pull/482

**Comment by andybro19** [comment]
Have you tried adding:

```yaml
query_params:
  - address
```

For example:

```yaml
- name: Create IP address within Netbox with only required information
  netbox_ip_address:
    netbox_url: http://netbox.local
    netbox_token: thisIsMyToken
    data:
      address: 192.168.1.42/24
    query_params:
      - address
    state: present

- name: Attach a previously created IP (192.168.1.42/24) to GigabitEthernet1 (NetBox 2.9+)
  netbox_ip_address:
    netbox_url: http://netbox.local
    netbox_token: thisIsMyToken
    data:
      address: 192.168.1.42/24
      vrf: Test
      assigned_object:
        name: GigabitEthernet1
        device: test100
    query_params:
      - address
    state: present
```
