### ISSUE TITLE
Allow netbox_ip_address module to accept raw json values as assigned objects to deal with duplicate objects

### ISSUE THREAD

**Issue by dsmaugy** [netbox-community/ansible_modules#486]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Allow `netbox.netbox.netbox_ip_address` module to accept raw json values for `assigned_object`. 
As of right now, any VMs or devices listed as an assigned object to an IP address has to be a string. If there are multiple devices/VMs with the same name, there is no way to differentiate between the multiple objects. An error will occur: 

```
"msg": "More than one result returned for virtual_machine"
```

##### STEPS TO REPRODUCE

The `netbox.netbox.netbox_vm_interface` module is able to handle duplicate virtual machines correctly by accepting raw json values as part of the VM query. By specifying other relevant info such as VM cluster in the json, the API is able to find the correct VM even if there are multiple VMs with the same name. e.g:
```yaml
netbox.netbox.netbox_vm_interface:
    ...
    data:
      # explicitly specify the cluster in case there are multiple VMs with same name
      virtual_machine: {"name": "<vm_name>", "cluster": "<cluster_name>"} 
```

It would be great if `netbox.netbox.netbox_ip_address` (and any other relevant modules) had this same functionality as `netbox.netbox.netbox_vm_interface`.
