### ISSUE TITLE
Netbox-site check - playbook help

### ISSUE THREAD

**Issue by hrv231** [netbox-community/ansible_modules#487]
##### ISSUE TYPE

 - Module question

###### Ansible:

ansible 2.10.5
  config file = /home/user1/ansible/ansible/ansible.cfg
  configured module search path = ["/home/user1/ansible/ansible/'/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/user1/ansible/ansible/library'"]
  ansible python module location = /home/user1/ansible/lib/python3.7/site-packages/ansible
  executable location = /home/user1/ansible/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]

###### Netbox:

v2.10.4
###### Collection:

 /home/user1/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
ansible.netcommon      2.0.1  
ansible.utils          2.0.2  
community.general      1.3.4  
community.kubernetes   1.1.1  
community.network      2.1.0  
google.cloud           1.0.1  
juniper.device         0.1.0  
junipernetworks.junos  2.0.1  
**netbox.netbox          3.0.0**  
paloaltonetworks.panos 2.1.0  

 /home/user1/ansible/lib/python3.7/site-packages/ansible_collections
Collection                Version
------------------------- -------
netbox.netbox             2.1.0  

##### SUMMARY

Hello,
I'm trying to create new devices on netbox, and I would like a way to check that if the device is there and have a Site assigned to it, then do not update the device with this new Site, in my case TEMPORARY SITE.
I know the module works great, because I'm able to create new devices, but the problem is for the devices I already have in netbox, they update the site.
I don't think this is an issue with the module, I just need help.
I don't know how to say in my playbook, if the device has a site assigned, do not update it.
##### STEPS TO REPRODUCE

```yaml
  tasks:
    - name: GATHER DEVICE FACTS
      junipernetworks.junos.junos_facts:
    - name: Create device within Netbox
      netbox_device:
        netbox_url: https://5.5.5.5
        netbox_token: 5555555555555555555555555555555
        validate_certs: no
        data:
          name: "{{ansible_net_hostname}}"
          device_type: "{{ansible_net_model}}"
          device_role: "CE Router"
          site: "{{ 'TEMPORARY SITE'|default(omit) }}"
          status: active
          platform: "Juniper Junos"
          serial: "{{ansible_net_serialnum}}"
        state: present
      delegate_to: localhost
```

##### EXPECTED RESULTS

I need help with my playbook.
##### ACTUAL RESULTS

```

```
