### ISSUE TITLE
netbox_ip_address Failed to establish connection to Netbox API

### ISSUE THREAD

**Issue by alexeysorok** [netbox-community/ansible_modules#488]
##### ISSUE TYPE

 - Module question

##### SUMMARY
 I want to add an address to the interface for the device, but I get an error: 

"msg": "Failed to establish connection to Netbox API"
 ![ip](https://user-images.githubusercontent.com/41438642/114995488-8b137500-9ea6-11eb-8467-c989ac0dfd28.PNG)
Moreover, with other modules there is no such error, I added a device, added an interface, there are no errors 
 

##### STEPS TO REPRODUCE

```yaml
---
- name: Example IP Addr  
  hosts: "localhost"

  tasks:
    - name: "Ensure that an IP inside 192.168.1.0/24 is attached to LAN"
      netbox_ip_address:
        netbox_url: "http://netbox"
        netbox_token: "token"
        data:
          prefix: 192.168.1.0/24
          assigned_object:
            name: LAN
            device: test-server
          validate_certs": no
        state: new
```

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_netbox_ip_address_payload_m14d6py0/ansible_netbox_ip_address_payload.zip/ansible/modules/net_tools/netbox/netbox_ip_address.py", line 280, in main
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "assigned_object": {
                    "device": "test-server",
                    "name": "LAN"
                },
                "prefix": "192.168.1.0/24",
                "validate_certs\"": false
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://netbox",
            "state": "new",
            "validate_certs": true
        }
    },    
}
```

This playbook ok 

```yaml
---
- name: Example Add Interface
  hosts: "localhost"

  tasks:
    - name: "Create interface within Netbox with only required information"
      netbox.netbox.netbox_device_interface:
        netbox_url: "http://netbox"
        netbox_token: "token"
        data:
         device: test-server
         name: LAN
         type: 1000Base-t (1GE)
        state: present

```
