### ISSUE TITLE
Inventory plugin broken after upgrading Netbox to 2.11.x

### ISSUE THREAD

**Issue by diekgait** [netbox-community/ansible_modules#492]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.16

###### Netbox:
2.11.0

###### Collection:
3.0.0

##### SUMMARY
After upgrading netbox from 2.10.6 to 2.11.0 the inventory plugin to longer works. This is caused by a rename of "rack-groups" into "locations" in Netbox version 2.11.x

##### STEPS TO REPRODUCE

- Create an inventory file with an "api_endpoint" that points to a Netbox 2.11.0 server.

- Run ansible-inventory-3 --list

```
ansible-inventory-3 --list
```

##### EXPECTED RESULTS
A list with my inventory.

##### ACTUAL RESULTS
An warning that no inventory was parsed

##### Solution
In nb_inventory.py on line 814 change:
```
"/api/dcim/rack-groups/?limit=0"
```
into:
```
"/api/dcim/locations/?limit=0"
```

And it will work again. Since the entire module has been renamed it may be elegant to replace "rack-groups" with "locations" in other places as well.

For more information check "breaking changes" in the Netbox 2.11.0 release notes:
https://github.com/netbox-community/netbox/releases

**Comment by jvanderaa** [comment]
Interesting breaking change of NetBox. Not seeing much value in that.

Was there a migration path available? Or would changing to locations break NetBox 2.9 & 2.10 installs?

**Comment by diekgait** [comment]
Changing to locations will break compatibility with Netbox 2.9 and 2.10. We could use nb.version to get the version number and based on that use either one URL or the other.

**Comment by bluikko** [comment]
Would be nice to get #496 merged. Using Tower/AWX that downloads collections automatically means that making a one-line change is not simple.

**Comment by nahun** [comment]
Just wanted to get this out there, I've submitted a PR #510 for full `locations` functionality. Its not done yet as I haven't updated any testing though.

**Comment by FragmentedPacket** [comment]
I'm going to close this issue out as #496 has been merged in and I will try and get a release out this weekend.

@nahun's PR adds additional functionality.

**Comment by bluikko** [comment]
Does it really work? I could not get any other groups than `all` and `ungrouped` with the following inventory:
```
---
plugin: netbox.netbox.nb_inventory
api_endpoint: https://api.netbox.domain.example
token: abc123
validate_certs: true
config_context: false
virtual_chassis_name: true
plurals: false
group_by:
  - rack_group
query_filters:
  - role: server
  - status: active
  - platform: el
```

The expected query results are listed but no `rack_group_*` groups exist for the locations. The devices definitely have the "location" parameter set.
