### ISSUE TITLE
Add netbox_secret and netbox_secret_role modules

### ISSUE THREAD

**Issue by devon-mar** [netbox-community/ansible_modules#495]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:

2.9.15

###### Netbox:

2.10.10

###### Collection:

3.0.0

##### SUMMARY

Currently secrets can only be looked up through the `nb_lookup` plugin. The new modules would allow creating secrets and secret roles.

I can take care of this issue if it's accepted.

##### STEPS TO REPRODUCE

Example usage:
```yaml
[...]

- name: Update the enable password
  netbox.netbox.netbox_secret:
    netbox_url: http://netbox.local
    netbox_token: token
    netbox_key: "{{ lookup('file', 'netbox.key') }}"
    data:
      name: Enable password
      secret_role: enable-password
      plaintext: "{{ enable_secret }}"
```

##### EXPECTED RESULTS
The secret is created with the given data.
