### ISSUE TITLE
Add location to netbox_device

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#499]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

2.11

##### SUMMARY

Locations were added in netbox 2.11 and location should be added as an option for netbox_device. E.g:

```yaml
- name: Add netbox device to location
  netbox.netbox.netbox_device:
    data:
      name: device
      location: location
    state: present
```
