### ISSUE TITLE
Add location to netbox_rack

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#500]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

2.11

##### SUMMARY

Locations were added in netbox 2.11 and location should be added as an option for netbox_rack. E.g:

```yaml
- name: Add netbox rack to location
  netbox.netbox.netbox_rack:
    data:
      name: rack
      location: location
    state: present
```
