### ISSUE TITLE
Add netbox_location module

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#501]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

2.11

##### SUMMARY

Locations were added in netbox 2.11 and a module `netbox_location` should be created to be able to add, update, and delete locations in netbox. E.g:

```yaml
- name: Add location
  netbox.netbox.netbox_location:
    data:
      name: location
      site: site
      parent_location: parent location
      description: this is a location
    state: present

- name: Delete location
  netbox.netbox.netbox_location:
    data:
      name: location
    state: absent
```
