### ISSUE TITLE
Add netbox_site_group module

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#502]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

2.11

##### SUMMARY

Site groups were added in netbox 2.11 and a module `netbox_site_group` should be created to be able to add, update, and delete site groups in netbox. E.g:

```yaml
- name: Add site group
  netbox.netbox.netbox_site_group:
    data:
      name: site group
      parent_site_group: parent site group
      description: this is a site group
    state: present

- name: Delete site group
  netbox.netbox.netbox_site_group:
    data:
      name: site group
    state: absent
```
