### ISSUE TITLE
Add site_group to netbox_site

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#503]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

2.11

##### SUMMARY

Site groups were added in netbox 2.11 and site_group should be added as an option for netbox_site. E.g:

```yaml
- name: Add netbox site to site group
  netbox.netbox.netbox_site:
    data:
      name: site
      site_group: site group
    state: present
```
