### ISSUE TITLE
Add mark_connected to netbox_device_interface

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#504]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

2.11

##### SUMMARY

Since netbox 2.11 you can mark an interface as connected without a cable. The mark_connected option should be added to netbox_device_interface. E.g:

```yaml
- name: Mark interface as connected
  netbox.netbox.netbox_device_interface:
    data:
      device: device
      name: interface
      mark_connected: true
    state: present
```
