### ISSUE TITLE
Add scope_type and scope to netbox_vlan_group

### ISSUE THREAD

**Issue by andybro19** [netbox-community/ansible_modules#505]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

2.11

##### SUMMARY

Since netbox 2.11 you assign a VLAN group to a scope rather than just a site. The options scope_type and scope should be added to netbox_vlan_group. E.g:

```yaml
- name: Add vlan group to location
  netbox.netbox.netbox_vlan_group:
    data:
      name: vlan group
      scope_type: dcim.location
      scope: location
    state: present
```

`scope_type` will have these choices:
* dcim.location
* dcim.rack
* dcim.region
* dcim.site
* dcim.sitegroup
* virtualization.cluster
