### ISSUE TITLE
[netbox.netbox.netbox_device] Collection v3.1.0: More than one result returned for rack

### ISSUE THREAD

**Issue by igloo777** [netbox-community/ansible_modules#515]
- NetBox version - v.2.11.2
- Python version - 3.8
- Collection version - 3.1.0
- Ansible version - 2.10.4

## Steps to Reproduce

1. Create test set:
- test-site1
  - Rack1
  - Rack999
- test-site2
  - Rack1
- test-switch1

```yml
---
- hosts: localhost
  collections: netbox.netbox
  vars:
    netbox_url: "https://localhost"
    netbox_token: "token"
  
  tasks:
    - name: Update Site1
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: test-site1
          status: Active
        state: present
        validate_certs: false

    - name: Test Site1 - Rack1
      netbox.netbox.netbox_rack:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: Rack1
          site: test-site1
          status: Active
          type: Wall-mounted cabinet
          u_height: 12
        state: present
        validate_certs: false

    - name: Test Site1 - Rack999
      netbox.netbox.netbox_rack:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: Rack999
          site: test-site1
          status: Active
          type: Wall-mounted cabinet
          u_height: 12
        state: present
        validate_certs: false

    - name: Update Site2
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: test-site2
          status: Active
        state: present
        validate_certs: false

    - name: Test Site2 - Rack1
      netbox.netbox.netbox_rack:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: Rack1
          site: test-site2
          status: Active
          type: Wall-mounted cabinet
          u_height: 12
        state: present
        validate_certs: false

    - name: Configure test switch test1
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: test-switch1
          device_type: PowerSwitch N1548P
          device_role: Access Switch
          platform: Dell OS6
          site: test-site1
          rack: Rack1
          status: planned
        state: present
        validate_certs: false
```

2. Attach test-switch1 to test-site1/Rack1 to get error

If I attach test-switch1 to test-site1/Rack999 (uniq rack) i get no error.

It seems like the "site" attribute is not included in the search query.

### Expected Behavior

I expect the query should return only one result.

### Observed Behavior
```
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_device_payload_4v8rx3m5/ansible_netbox.netbox.netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 559, in _nb_endpoint_get
    response = nb_endpoint.get(**query_params)
  File "/home/igloo/.local/lib/python3.8/site-packages/pynetbox/core/endpoint.py", line 141, in get
    raise ValueError(
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "custom_fields": null,
                "device_role": "Access Switch",
                "device_type": "PowerSwitch N1548P",
                "face": null,
                "local_context_data": null,
                "name": "test-switch1",
                "platform": "Dell OS6",
                "position": null,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": "Rack1",
                "serial": null,
                "site": "test-site1",
                "status": "planned",
                "tags": null,
                "tenant": null,
                "vc_position": null,
                "vc_priority": null,
                "virtual_chassis": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://test.lcl",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    }
}

MSG:

More than one result returned for rack
```

**Comment by FragmentedPacket** [comment]
https://netbox-ansible-collection.readthedocs.io/en/latest/getting_started/how-to-use/advanced.html#passing-in-dictionaries Should help you get past this.

Basically:
```
rack:
  name: Rack1
  site: test-site1
```

**Comment by igloo777** [comment]
I'm not sure this case should be handled by `advanced things` mentioned in doc above.

Configuration 
```yaml
    - name: Test Site1 - Rack1
      ...
        data:
          name: Rack1
          site: test-site1
```
already create a uniq set for rack search. 

I expeted that config below univocally identifies the rack.
```yml
 - name: Configure test switch test1
      netbox.netbox.netbox_device:
        data:
          ...
          site: test-site1
          rack: Rack1
```

Am I wrong? Are there the cases when we may have >1 rack with the same rack name on one site (I mean the netbox modeling logic)?

**Comment by igloo777** [comment]
I've tried to put the query_params into config, but it didn't help.
```
    - name: Configure test switch test1
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: test-switch1
          device_type: PowerSwitch N1548P
          device_role: Access Switch
          platform: Dell OS6
          site: test-site1
          rack: Rack1
          status: planned
        query_params:
          - site
          - rack
        state: present
```
It still return `More than one result returned for rack`.

**Comment by FragmentedPacket** [comment]
You would do this for the rack. So taking your last task as an example.

```
    - name: Configure test switch test1
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: test-switch1
          device_type: PowerSwitch N1548P
          device_role: Access Switch
          platform: Dell OS6
          site: test-site1
          rack:
            name: Rack1
            site: test-site1
          status: planned
        state: present
```

**Comment by igloo777** [comment]
Thanks, it works!
By the way, I would recommend describing this case in all modules, one way or another related to racks.

**Comment by FragmentedPacket** [comment]
That is probably a good point. I decided against that due to it affects all modules, but it doesn't hurt to add an example to each module.

I'll close this issue and then open another for updating docs.

**Comment by igloo777** [comment]
> That is probably a good point. I decided against that due to it affects all modules, but it doesn't hurt to add an example to each module.
> 
> I'll close this issue and then open another for updating docs.

umh.. I have a question, don't you think that here too many `site` keys?
```
          site: test-site1
          rack:
            name: Rack1
            site: test-site1
```
