### ISSUE TITLE
[Bug]: Updating a LAG to an existing interface is failing

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/ansible_modules#519]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.10.7

###### Netbox:

2.11.3

###### Collection:

3.1.0

##### SUMMARY

Ansible task for updating a lag in a interface fails by saying that not enough information was provided to identify the object.

##### STEPS TO REPRODUCE

Create a file servername.yaml that will be used as external argument to create object in netbox
```
SERVER:
  - hostname: servername   # Defines the name of the device that will be created in netbox
    siteslug: "trash"                # Defines the value to be used in netbox for the site 
    model: server-model        #  Defines the value to be used for the Model Information
    platform_type: Physical Appliance    # Defines the value to be used in netbox
    LAG_INTERFACES:
      - name: LACP-IOLAN                 # Defines the value to be used in netbox
        description: "2x10G in LACP ACTIVE Configuration"
        type:  Link Aggregation Group (LAG)  # -> Create link agregation
        mode: access                     # Defines 802.1Q configuration
      - name: LACP-DMZ
        description: "2x10G in LACP ACTIVE Configuration"
        type:  Link Aggregation Group (LAG)  # -> Create link agregation
        mode: access                         # Defines 802.1Q configuration
    PHYSICAL_INTERFACES:
      - name: 10GB-LC1
        type: 10gbase-x-sfpp
        mode: access
        mgmt_only: false
        lag:
           name: LACP-IOLAN
      - name: 10GB-LC2
        type: 10gbase-x-sfpp
        mgmt_only: false    
        mode: access          # Can be ommited
        label: eth3b
        lag:
            name: LACP-DMZ
```
Create a yaml playbook netbox_update_servers.yaml

```
---
# This playbook is used to create a server in netbox
- name: "Update Netbox with a new server information"
  hosts: localhost
  connection: local
  #no_log: True
  vars:
    netbox_url: https://netbox.xxx
    netbox_token: xxx

tasks:
    - name: Create or Update device matching the server
      netbox.netbox.netbox_device:
        netbox_token: "{{ netbox_token }}"
        netbox_url: "{{ netbox_url }}"
        validate_certs: False
        data: 
          name: "{{ item.hostname }}"   
          device_type:  "{{ item.model }}"  
          site: "{{ item.siteslug }}"  
          platform:  "{{ item.platform_type }}" 
      loop: "{{ SERVER }}" 
      loop_control:
        label: "{{ item.hostname }} model {{ item.model }} - Site {{ item.siteslug }}"
      tags: [update-all, update-device]      
    - name: Create or update Physical interfaces
      netbox.netbox.netbox_device_interface:
        netbox_token: "{{ netbox_token }}"
        netbox_url: "{{ netbox_url }}"
        validate_certs: False
        data: 
          device: "{{ SERVER[0].hostname }}" 
          name: "{{ item.name }}" 
          type: "{{ item.type }}"
          mgmt_only: false
          mode: "{{ item.mode }}"
          mac_address: "{{ item.mac_address|default(omit) }}" 
          label: "{{ item.label|default(omit) }}" 
      loop: "{{ SERVER[0].PHYSICAL_INTERFACES }}" 
      loop_control:
        label: "{{ item.name }} type {{ item.type }} - mode {{ item.mode }} -mac {{ item.mac_address|default(omit) }} - label {{ item.label|default(omit) }}"
      tags: [update-all, update-device-interfaces] 

    - name: Create Link_Aggregation_Type
      netbox.netbox.netbox_device_interface:
        netbox_token: "{{ netbox_token }}"
        netbox_url: "{{ netbox_url }}"
        validate_certs: False
        data: 
          device: "{{ SERVER[0].hostname }}" 
          name: "{{ item.name }}" 
          type: "{{ item.type }}"
          mgmt_only: false
          mode: "{{ item.mode }}"
          mac_address: "{{ item.mac_address|default(omit) }}" 
          description: "{{ item.description | default(omit) }}" 
      loop: "{{ SERVER[0].LAG_INTERFACES }}" 
      loop_control:
        label: "{{ item.name }} type {{ item.type }} - mode {{ item.mode }}"
      tags: [update-all, create-device-interfaces-lag] 

    # NOT WORKING FOR NOW...
    - name: Update Physical interfaces used by Link_Aggregation_Type
      netbox.netbox.netbox_device_interface:
        netbox_token: "{{ netbox_token }}"
        netbox_url: "{{ netbox_url }}"
        validate_certs: False
        data: 
          device: "{{ SERVER[0].hostname }}" 
          name: "{{ item.name }}" 
          type: "{{ item.type }}"
          mgmt_only: false
          mode: "{{ item.mode }}"          
          lag:
            name: "{{ item.lag|default(omit) }}" 
      loop: "{{ SERVER[0].PHYSICAL_INTERFACES }}" 
      when: item.lag is defined            
      loop_control:
        label: "{{ item.name }} -  lag {{ item.lag|default(omit)  }}" 
      tags: [update-all, update-device-interfaces-lag]       

```

Run playbook:
ansible-playbook playbooks/netbox_update_servers.yaml --extra-vars @servername.yaml -vvvv

##### EXPECTED RESULTS

LAG interface was added to physical interface 
##### ACTUAL RESULTS

```
failed: [localhost] (item=10GB-LC2 -  lag {'name': 'LACP-DMZ'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "description": null,
                "device": "servername",
                "enabled": null,
                "form_factor": null,
                "label": null,
                "lag": {
                    "name": {
                        "name": "LACP-DMZ"
                    }
                },
                "mac_address": null,
                "mark_connected": null,
                "mgmt_only": false,
                "mode": "access",
                "mtu": null,
                "name": "10GB-LC2",
                "tagged_vlans": null,
                "tags": null,
                "type": "10gbase-x-sfpp",
                "untagged_vlan": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.xxx",
            "query_params": null,
            "state": "present",
            "update_vc_child": false,
            "validate_certs": false
        }
    },
    "item": {
        "label": "eth3b",
        "lag": {
            "name": "LACP-DMZ"
        },
        "mgmt_only": false,
        "mode": "access",
        "name": "10GB-LC2",
        "type": "10gbase-x-sfpp"
    },
    "msg": "Could not resolve id of lag: {'name': {'name': 'LACP-DMZ'}}"
}
```

**Comment by jcralbino** [comment]
I have upgraded the netbox to 2.11.4 issue is still there.

**Comment by bluikko** [comment]
I know it will not help you - but I got tired of all the breakage and just talk straight to the API in every case except `nb_lookup` and the inventory. It is not much different from using the Ansible modules in the end.

**Comment by jcralbino** [comment]
Hello
Thanks for your feedback. My understanding is that if I do a call to the api I will need to deal with more logic namely checking if it is there before otherwise create will create an error. So then I need to do update.. so getting this idempotent behaviour would be more complex.. but maybe I am wrong..

**Comment by sc68cal** [comment]
I've built multiple LAGs for our infrastructure like so:


```yaml
  tasks:
    - name: Create Uplink port-channel interfaces
      netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "port-channel {{ item }}"
          device: "{{ inventory_hostname }}"
          type: Link Aggregation Group (LAG)
        state: present
      loop: "{{ range(1, 8) | list }}"

    - name: Assign uplink to parent LAGs
      netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ inventory_hostname }}"
          name: "ethernet1/1/{{ item }}"
          lag:
            name: "port-channel {{ item }}"
        state: present
      loop: "{{ range(1, 8) | list }}"
```

WIth no issues
