### ISSUE TITLE
multiple modules, same error:  "msg": "state is present but all of the following are missing: name"

### ISSUE THREAD

**Issue by n2aws** [netbox-community/ansible_modules#529]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
ansible [core 2.11.0]

###### Netbox:
2.10.4

###### Collection:
3.1.1,  But also tested with:
3.1.0
3.0.0

(all with same result)

##### SUMMARY
I get the same error, regardless of module I attempt to use: (Tested with netbox_device, netbox_site, netbox_manufacturer)

`state is present but all of the following are missing: name`

##### STEPS TO REPRODUCE
Example from official documentation:
```yaml
cat roles/netbox/tasks/main.yml 
# tasks file for netblox
---

- name: "Example for state: present"
  netbox.netbox.netbox_device:
    netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
    data:
      name: "Test Device"
      device_type: "C9410R"
      device_role: "Core Switch"
      site: "Main"
    state: present
```

Being called from a playbook with:
```yaml
---

- name: Add items to netbox
  hosts: localhost
  connection: local
  roles:
    - netbox
```

##### EXPECTED RESULTS
An example cut/pasted from the docs (obviously replacing the URL and API key) should result in a device called "Test Device" being created.

##### ACTUAL RESULTS
I get an error 
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asset_tag": null,
                "cluster": null,
                "comments": null,
                "custom_fields": null,
                "device_role": "Core Switch",
                "device_type": "C9410R",
                "face": null,
                "local_context_data": null,
                "name": "Test Device",
                "platform": null,
                "position": null,
                "primary_ip4": null,
                "primary_ip6": null,
                "rack": null,
                "serial": null,
                "site": "Main",
                "status": null,
                "tags": null,
                "tenant": null,
                "vc_position": null,
                "vc_priority": null,
                "virtual_chassis": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://<<edited>>,
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "state is present but all of the following are missing: name"
}

```
As you can see from the task definition, and resulting debug output, "name" is clearly defined and parsed.
However, I still get the error message.

It's worth noting, that I took all of the "data" elements from this debug output, an dmade sure to populate *all* fields (assuming the error was about some other field other than "name", but it resulted in the exact same response.
Additionally worth noting, I'm only showing an example netbox_device, but the same error is happening with multiple as mentioned above.

As an example of one where I populated all fields as a test (in this case, netbox_site)
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asn": "Foo",
                "comments": "Foo",
                "contact_email": "Foo",
                "contact_name": "Foo",
                "contact_phone": "Foo",
                "custom_fields": "Foo",
                "description": "Foo",
                "facility": "Foo",
                "latitude": "Foo",
                "longitude": "Foo",
                "name": "Foo",
                "physical_address": "Foo",
                "region": "Foo",
                "shipping_address": "Foo",
                "slug": "Foo",
                "status": "Foo",
                "tags": [
                    "Foo"
                ],
                "tenant": "Foo",
                "time_zone": "Foo"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://<<edited>>",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "state is present but all of the following are missing: name"
}
```

I DO see a note in the documentation `These same fields are required when creating a device via the netbox_device module, but with the important addition of name.` However, as you can see.. it's being provided.
