### ISSUE TITLE
nb_lookup interface-connections throws unhandled exception

### ISSUE THREAD

**Issue by f-kessler** [netbox-community/ansible_modules#538]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

core 2.11.1

###### Netbox:

v2.9.11

###### Collection:

3.1.1

##### SUMMARY

The data is received from netbox API, but an manhandled exception will be shown and the task fails.

##### STEPS TO REPRODUCE

```yaml
  tasks:
    - name: Task 1 get connections
      debug:
        msg: >
          " connections: {{ item.value }} "
      loop: "{{ query('netbox.netbox.nb_lookup', 'interface-connections',
                      api_endpoint=''+nb_address,
                      token=''+nb_token,
                      validate_certs=False,
                      api_filter='') }}"
      register: connections
```

##### EXPECTED RESULTS

Data will be retrieved from netbox and handled wihtout exception.

##### ACTUAL RESULTS

```
fatal: [device_name]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'KeyError'>, original message: 'id'"
}
```
