### ISSUE TITLE
[Bug]: netbox_vm_interface cannot be used with "ambiguous" VLANs

### ISSUE THREAD

**Issue by fabricat** [netbox-community/ansible_modules#557]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.9.19
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]

###### Netbox:

2.11.9

###### Collection:

3.1.1

##### SUMMARY

When I try to use the `netbox_vm_interface` plugin to create a network interface for a VM in Netbox, under some circumstances, I get the following error message:
> More than one result returned for untagged_vlan

I am using VLAN **IDs** as values of `untagged_vlan`, and the issue only happens with **some IDs** (not always).
For example, if I manually search for VLAN "22" in Netbox (using the generic "search" field) and I get only one result, then using Ansible to create a VM interface on that VLAN succeeds.
On the contrary, if I get multiple results when I manually search for VLAN "3", then the creation of VM interfaces on this VLAN is going to fail!

I have tried to avoid the issue by using the `query_params` option, but I could not figure out how to use it.

##### STEPS TO REPRODUCE

**It is important to have some "ambiguous" VLANs already present in Netbox**
For example:

- VLAN ID 3, name `this is the correct one`
- VLAN ID 25, name `this has a 3 in the name (misleading)`
- VLAN ID 22, name `unambiguous`

Run the following playbook:

```yaml
---
- name: issue example
  hosts: localhost
  tasks:

  - name: add vNIC OK
    netbox.netbox.netbox_vm_interface:
      netbox_url: "{{ NETBOX_URL }}"
      netbox_token: "{{ NETBOX_TOKEN }}"
      state: present
      data:
        virtual_machine: "test-VM"
        name: "test-NIC22"
        untagged_vlan: 22

  - name: add vNIC FAIL
    netbox.netbox.netbox_vm_interface:
      netbox_url: "{{ NETBOX_URL }}"
      netbox_token: "{{ NETBOX_TOKEN }}"
      state: present
      data:
        virtual_machine: "test-VM"
        name: "test-NIC3"
        untagged_vlan: 3
```

##### EXPECTED RESULTS

The interfaces should be created/updated successfully for **any VLAN ID**, not only some IDs.

##### ACTUAL RESULTS

I could only get interfaces to be created for some VLAN IDs.
It seems that the working IDs are the ones "non ambiguous" when searching for VLANs in Netbox.

I mean, if I manually search for VLAN 1439 in Netbox (using the generic "search" field) and I get only one result, then VM interface creation succeeds.
On the contrary, if I manually search for VLAN "3", I get several results: creation of VM interfaces on this VLAN is going to fail!

```
PLAY [issue example] ***********************************************************************************************************************************

TASK [add vNIC OK] ************************************************************************************************************************************
changed: [localhost]

TASK [add vNIC FAIL] **********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "More than one result returned for untagged_vlan"}

PLAY RECAP *********************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   ```

**Comment by jsenecal** [comment]
The same is also true for other object types such as VRFs import and export _targets. Probably related.

**Comment by rodvand** [comment]
I see this is a while ago but you can narrow it down by doing something like this:

```
data:
  virtual_machine: "test-VM"
  name: "test-NIC3"
  mode: "access"
  untagged_vlan:
    vid: 22    
```

Not sure if this fully covers you issue, so just re-open it if needed.
