### ISSUE TITLE
The error was: 'dict object' has no attribute 'prefix'\n\n when my my dict does include a value - 'prefix'

### ISSUE THREAD

**Issue by marky2376** [netbox-community/ansible_modules#559]
##### ISSUE TYPE

 - Module question

###### Ansible:
Ansible 2.9.18

###### Netbox:
v2.11.4

###### Collection:
3.1.1

##### SUMMARY
I am creating a new prefix with the module netbox.netbox.netbox_prefix.  Registering the netbox dict as a variable then trying to filter a value in another task.  

    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'prefix'\n\nThe error appears to be in '/tmp/bwrap_1661_kmw00u2r/awx_1661_4u8n4f49/project/ReserveIPNetbox.yml': line 66, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"Set fact for Prefix\"\n      ^ here\n",
    "_ansible_no_log": false

##### STEPS TO REPRODUCE

``` 
- name: Get a new prefix when circuit is South Carolina
      netbox.netbox.netbox_prefix:
        netbox_url: http://netbox.truvista.net:8085
        validate_certs: False
        netbox_token: 
        data:
          parent: "206.74.x.0/24"
          prefix_length: "{{ prefix_length }}"
          description: "{{ c_description }}"
        state: present
        first_available: yes
      register: c_prefix
      when: location == "South_Carolina"

- name: "Set fact for Prefix"
      set_fact:
        prefix2: "{{ c_prefix['prefix'] }}"
      when: (location == "South_Carolina" or location == "Georgia")

```

##### EXPECTED RESULTS
The variable should be set as just the prefix value of the dict.  This works with exact same logic on the  netbox.netbox.netbox_ip_address module, so not sure what is different about these dicts.  I get a similar problem when I do an nblookup.  It doesn't seem to find the value so it prints all my prefixes. 

This is an example of the prefix dict:

 {
            "key": 7199,
            "value": {
                "created": "2019-09-27",
                "custom_fields": {},
                "description": "DSL MGMT Pool",
                "display": "10.8.0.0/16",
                "family": {
                    "label": "IPv4",
                    "value": 4
                },
                "id": 7199,
                "is_pool": false,
                "last_updated": "2019-09-27T19:40:49.367624Z",
                "prefix": "10.8.0.0/16",
                "role": null,
                "site": null,
                "status": {
                    "label": "Active",
                    "value": "active"
                },
                "tags": [],
                "tenant": null,
                "url": "http://netbox.truvista.net:8085/api/ipam/prefixes/7199/",
                "vlan": null,
                "vrf": null
            }

##### ACTUAL RESULTS

```
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'prefix'\n\nThe error appears to be in '/tmp/bwrap_1661_kmw00u2r/awx_1661_4u8n4f49/project/ReserveIPNetbox.yml': line 66, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"Set fact for Prefix\"\n      ^ here\n",
    "_ansible_no_log": false
```
