### ISSUE TITLE
vcpus are not represented as integers in Netbox

### ISSUE THREAD

**Issue by fabricat** [netbox-community/ansible_modules#562]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.9.19
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]

###### Netbox:

2.11.9

###### Collection:

3.1.1

##### SUMMARY

Every time I execute `netbox_virtual_machine` (with "state: present") on a VM already existing in Netbox, the item is alwasy marked as **changed**
Checking the `diff`, I see that the only difference is:

    --- before
    +++ after
    @@ -1,3 +1,3 @@
     {
    -    "vcpus": "2.00"
    +    "vcpus": 2
     }

Indeed I notice that vCPU count in Netbox is now represented as a **float** number, also on the web UI.

Anyway, having a _falsey_ "changed" status is annoying, since real changes are not evident.

##### STEPS TO REPRODUCE

```yaml
- name: "Test Netbox vcpus issue"
  connection: local
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create a VM with 2 vCPU
      netbox_virtual_machine:
        netbox_url: http://netbox.local
        netbox_token: thisIsMyToken
        data:
          name: Test Virtual Machine
          cluster: test cluster
          vcpus: 2
        state: present
```
The first time, the VM is created.
If you run the same playbook once again (`ansible-playbook -D test.yml`), the VM is shown as **changed** (the only difference is the `vcpus` format).

##### EXPECTED RESULTS

The first time, the VM is created, thus the task result is **changed**.
The second time the task result should be **ok**.

##### ACTUAL RESULTS

The second time you run the playbook, the task result always appear as **changed**.
