### ISSUE TITLE
Getting issues when added racks to rack group

### ISSUE THREAD

**Issue by richardjohnallsopp** [netbox-community/ansible_modules#57]
##### ISSUE TYPE

 - Bug Report
##### SUMMARY

I see an error when trying to add racks to a rack group
##### STEPS TO REPRODUCE

Using the netbox_rack_groups and netbox_racks collections to add a rack group and racks.

```yaml
    - name: "Create rack group in Netbox"
      fragmentedpacket.netbox_modules.netbox_rack_group:
        netbox_url: 
        netbox_token: "{{  netbox_key  }}"
        data:
          site: "{{ item.value.sitename }}"
          name: "{{ item.value.rackgroupname }}"
        state: present
      #check_mode: yes
      loop: "{{ query('dict', rackgroups) }}"
      #when: "{{ item.value.drack }}" != ""
      tags: add_rack_group

# task add racks to rack group
    - name: "Create racks and add to rack group in Netbox"
      fragmentedpacket.netbox_modules.netbox_rack:
        netbox_url: 
        netbox_token: "{{  netbox_key  }}"
        data:
          site: "{{ item.value.sitename }}"
          name: "{{ item.value.rackname }}"
          group: "{{ item.value.group_name }}"
          serial_number: "{{ item.value.serialnumber | default(omit) }}"
          asset_tag: "{{ item.value.assettag | default(omit) }}"
          type: "{{ item.value.type }}"
          width: "{{ item.value.width }}"
          height: "{{ item.value.height }}"
        state: present
      #check_mode: yes
      loop: "{{ query('dict', racks) }}"
      #when: "{{ item.value.drack }}" != ""
      tags: add_racks
```

##### EXPECTED RESULTS

It would add the rack group
##### ACTUAL RESULTS

I get an error:
msg: 'Could not resolve id of group: yok-mdf-01

```
flynn@ncl-ansible-01:~/ansible/playbooks/netbox$ ansible-playbook netbox_add_devices.yaml --tags "add_rack_group,add_racks"

PLAY [Add devices to netbox] ***********************************************************************************************************************************************************************

TASK [netbox_build_racks : Create rack group in Netbox] ********************************************************************************************************************************************
ok: [localhost] => (item={'key': u'rackgroup1', 'value': {u'sitename': u'YOK', u'rackgroupname': u'YOK-MDF-01'}})

TASK [netbox_build_racks : Create racks and add to rack group in Netbox] ***************************************************************************************************************************
failed: [localhost] (item={'key': u'rack2', 'value': {u'sitename': u'YOK', u'serialnumber': u'', u'group_name': u'YOK-MDF-01', u'width': u'19 inches', u'assettag': u'', u'rackname': u'YOK-MDF-01-RACK-02', u'height': u'42', u'type': u'4-post cabinet'}}) => changed=false
  ansible_loop_var: item
  item:
    key: rack2
    value:
      assettag: ''
      group_name: YOK-MDF-01
      height: '42'
      rackname: YOK-MDF-01-RACK-02
      serialnumber: ''
      sitename: YOK
      type: 4-post cabinet
      width: 19 inches
  msg: 'Could not resolve id of group: yok-mdf-01'
failed: [localhost] (item={'key': u'rack3', 'value': {u'sitename': u'YOK', u'serialnumber': u'', u'group_name': u'YOK-MDF-01', u'width': u'19 inches', u'assettag': u'', u'rackname': u'YOK-MDF-01-RACK-03', u'height': u'42', u'type': u'4-post cabinet'}}) => changed=false
  ansible_loop_var: item
  item:
    key: rack3
    value:
      assettag: ''
      group_name: YOK-MDF-01
      height: '42'
      rackname: YOK-MDF-01-RACK-03
      serialnumber: ''
      sitename: YOK
      type: 4-post cabinet
      width: 19 inches
  msg: 'Could not resolve id of group: yok-mdf-01'
failed: [localhost] (item={'key': u'rack1', 'value': {u'sitename': u'YOK', u'serialnumber': u'', u'group_name': u'YOK-MDF-01', u'width': u'19 inches', u'assettag': u'', u'rackname': u'YOK-MDF-01-RACK-01', u'height': u'42', u'type': u'4-post cabinet'}}) => changed=false
  ansible_loop_var: item
  item:
    key: rack1
    value:
      assettag: ''
      group_name: YOK-MDF-01
      height: '42'
      rackname: YOK-MDF-01-RACK-01
      serialnumber: ''
      sitename: YOK
      type: 4-post cabinet
      width: 19 inches
  msg: 'Could not resolve id of group: yok-mdf-01'

```
