### ISSUE TITLE
ansible_host_dns_name not taking effect

### ISSUE THREAD

**Issue by sirhc-chris** [netbox-community/ansible_modules#571]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
```
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```
###### Netbox:

```
v2.11.7
```
###### Collection:

```
Collection    Version
------------- -------
netbox.netbox 3.1.1
```
##### SUMMARY

When setting `ansible_host_dns_name: true` in my netbox inv file, the `ansible_host` variable still uses `primary_ip`
##### STEPS TO REPRODUCE

Netbox inventory:
```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox
validate_certs: true
token: omitted
ansible_host_dns_name: true
config_context: true
device_query_filters:
  - cf_ansible_inventory: true
keyed_groups:
  ...
```
Relevant group vars:
```yaml
ansible_user: omitted
ansible_password: omitted
ansible_connection: winrm
ansible_winrm_transport: kerberos
ansible_port: 5986
ansible_winrm_server_cert_validation: validate
```

##### EXPECTED RESULTS

`ansible_host` uses `dns_name`
    
##### ACTUAL RESULTS

`ansible_host` uses `primary_ip`

```
root@localhost:/$ ansible-inventory -i inventories/netbox/netbox-inventory.yml --host server01 | grep ansible_host
    "ansible_host": "192.168.0.10",
```
