### ISSUE TITLE
[Bug]: Netbox_vlan:  More than one result returned for vlan_group

### ISSUE THREAD

**Issue by apellini** [netbox-community/ansible_modules#574]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
Ansible 4.3.0

###### Netbox:
2.11.9

###### Collection:
3.1.1

##### SUMMARY
I have two VLAN_GROUP with same name but with different Site as Scope and when I try to insert a VLAN into a specific VLAN Group it fails with this error message

##### STEPS TO REPRODUCE

```yaml
    - name: test
      netbox.netbox.netbox_vlan:
        netbox_url: https://1.1.1.1
        netbox_token: <secret data
        data:
          vid: 10
          name: Test VLAN
          vlan_group: tenant1
          site: site1
          status: Active
        validate_certs: no
        state: present
      throttle: 1
      delegate_to: localhost

```

##### EXPECTED RESULTS
VLAN is inserted into the specific VLAN Group

##### ACTUAL RESULTS

```
msg: More than one result returned for vlan_group
```
