### ISSUE TITLE
nb_lookup: unrecognised term power-panels

### ISSUE THREAD

**Issue by rmammadli** [netbox-community/ansible_modules#575]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.10

###### Netbox:

2.10

###### Collection:

Collection: 3.1.1

##### SUMMARY

Querying netbox api by using nb_lookup plugin does not return any information for power-panels.

##### STEPS TO REPRODUCE

```yaml
- name: Check if power panel(s) exist(s)
  set_fact:
    power_panel_check:  "{{ item }}"
  loop: "{{ query('netbox.netbox.nb_lookup', 'power-panels', api_filter='name=' ~ var_to_hold_power_panel_name, api_endpoint=netbox_url, token=netbox_token) }}"
  register: power_panel_room_result
```

##### EXPECTED RESULTS

Getting a list of avaiable power-panels in netbox.

##### ACTUAL RESULTS

Error message: "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unrecognised term power-panels. Check documentation"

```

```
