### ISSUE TITLE
[Bug]: Updating custom fields with netbox.netbox.netbox_device_interface always generate changes

### ISSUE THREAD

**Issue by SteveRodrigue** [netbox-community/ansible_modules#581]
##### SUMMARY
If you have more than 1 custom fields in netbox interfaces table and you want to update only 1 field (not all of them), the module always generates a "changed" status.

##### STEPS TO REPRODUCE
1. Create any custom field for interfaces in Netbox. Use the module to update that field. Correct status is reported.
2. Create a second custom field for interfaces in Netbox. Rerun the same task to update the first field (and not the newly created one). The module will always report a changed status.
3. Destroy the second field and rerun the task: back to normal status behaviour.

```yaml
    - name: Update a custom field
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_api_token_rw }}"
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ interface_name }}"
          type: "{{ interface_type }}"
          custom_fields:
            test_field: "If more than one custom field exists, this task will always have a changed status."
        state: present

```

##### EXPECTED RESULTS
In theory, only the affected custom field should be checked/compared. If other custom fields exists, they should be ignored when the "diff/check" is done in the module.

##### ACTUAL RESULTS
Task changed but should not on the second run where we haven't changed anything in that custom field.
