### ISSUE TITLE
[Feature Request] Extend compose on nb_inventory to have the ability of restricting fetching to fields specified instead of only appending

### ISSUE THREAD

**Issue by YoucefYousfi** [netbox-community/ansible_modules#582]
##### ISSUE TYPE
 - Feature Idea

##### SOFTWARE VERSIONS
netbox.netbox collection on version 3.1.1

###### Ansible:
Ansible 2.9 or more

###### Netbox:
Any that's compatible with compose

###### Collection:
version 3.1.1

##### SUMMARY
Due to how I use Netbox, I would like to be able to retrieve less information from the plugin nb_inventory. I haven't found a way to do that according to the documentation.

To that goal, as a suggestion (but there are probably other ways to do it), I was thinking of using ```compose``` in addition to a new ```compose_mode``` that can be set to ```append``` or ```restrict``` (by default, it would append to maintain current functionality). It would need to work with other fields such as ```interface: yes``` to be able to fully control the result.

##### STEPS TO REPRODUCE

```yaml
plugin: netbox.netbox.nb_inventory
compose_mode: 'restrict'
compose:
  foo: last_updated
  bar: display_name
  nested_variable: rack.display_name
```

##### EXPECTED RESULTS
Restricted output
