### ISSUE TITLE
[netbox_cable] create or update cable is too slow with high number of cables already available

### ISSUE THREAD

**Issue by rmammadli** [netbox-community/ansible_modules#608]
##### ISSUE TYPE
 - Feature Idea

###### Ansible:
v2.10

###### Netbox:
v3.0.6

###### Collection:
v3.1.2

##### SUMMARY
We are using netbox_cable module to create / update cables within our netbox instance.

There are ~ 2500 cables right now and number of cables will grow exponentially as we plan to migrate / manage the whole infrastucture with netbox.

The module netbox_cable uses pynetbox to retrieve all cables through API call and then executes search within obtained data for certain cable (if exists) by using termination ids & termination types.

https://github.com/netbox-community/ansible_modules/blob/febe59dc5ba98b88df165cc72e89f7b16370b455/plugins/module_utils/netbox_dcim.py#L141-L149

Unfortunately it slows down the whole ansible run due to the fact, that this search will be done for every create / update cable request.

Netbox v3.0.6 offers possibility to make a precise GET request to Netbox API based on parameters below:

- termination_a_type
- termination_a_id 
- termination_b_type
- termination_b_id 

https://github.com/netbox-community/netbox/issues/7394
https://github.com/netbox-community/netbox/pull/7465

It would be great to implement the exact search of cable using termination ids and types within netbox_cable module.

##### STEPS TO REPRODUCE

Prerequisites:

- number of cables in netbox 2500
- data available in netbox from data structure **rack** given below
  -  rack
  -  location
  - device types
  - device roles
  -  etc

```
- name: Plug/connect powerports into/to poweroutlets
  netbox.netbox.netbox_cable:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      termination_a_type: dcim.powerfeed
      termination_a:
        name: "{{ item.1.name }}"
      termination_b_type: dcim.powerport
      termination_b:
        device: "{{ item.1.connected_device }}"
        name: "{{ item.1.connected_port }}"
      type: "{{ item.1.cable_type | default(omit) }}"
      label: "{{ item.1.label | default(omit) }}"
      color: "{{ item.1.color | default(omit) }}"
      length: "{{ item.1.length | default(omit) }}"      
      length_unit : "{{ item.1.length_unit | default(omit) }}"
      status: "{{ item.1.status | default(omit) }}"
    state: "{{ item.1.state }}"
  loop: "{{ rack | subelements('powerfeeds') }}"

```

where data structure **rack** ( some parameters within **powerfeeds** are used in another moudles ):
```
rack:
- name: room-1-001-012
  site: site-a
  state: present
  status: reserved
  facility_id: site-a-room-1-001-012
  location: site-a-room-1-001
  custom_fields:
    - name: custom fields for rack object
      manufactor: "nVent/Schroff"
      techn_space: Tech Space
  rack_role: ref
  tenant: "site-a"  
  u_height: 47
  width: 19
  powerfeeds:
    - name: room-1-001-012-USV-1
      power_panel: room-1-USV-1
      state: present
      status: planned
      type: primary
      amperage: 32
      phase: three-phase
      voltage: 400
      connected_device: site-apdu_room-1-001-012-601
      connected_port: CEE-Stecker
      cable_status: planned
    - name: room-1-001-012-NN-1
      power_panel: room-1-NN-1
      state: present
      status: planned
      type: redundant
      amperage: 32
      phase: three-phase
      voltage: 400
      connected_device: site-apdu_room-1-001-012-602
      connected_port: CEE-Stecker
      cable_status: planned
...
```

##### EXPECTED RESULTS
Execution of **netbox_cable** module would be faster and would be completed in a short period of time.

##### ACTUAL RESULTS
Too slow execution for existing netbox instance with around 2500 cables available. 

Just for two cables:

```
=============================================================================== 
rack : Plug/connect powerports into/to poweroutlets ------------------- 217.79s
...
```
