### ISSUE TITLE
Calling hostvars within netbox

### ISSUE THREAD

**Issue by hrv231** [netbox-community/ansible_modules#611]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.10.5
  config file = /home/user1/ansible2/ansible/ansible.cfg
  configured module search path = ["/home/user1/ansible2/ansible/'/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/user1/ansible2/ansible/library'"]
  ansible python module location = /home/user1/ansible2/lib64/python3.6/site-packages/ansible
  executable location = /home/user1/ansible2/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
###### Netbox:

v2.10.4
###### Collection:

netbox.netbox          3.1.2
##### SUMMARY

I'm trying to run the following playbook to create or update IPs gathered from each device.
If I disable tenant or manually type the tenant, it works; If I use hostvars it doesn't work.

I'm using the plugin netbox.netbox.nb_inventory to create my inventory from Netbox, that's why I need to access my inventory tenant using the hostvars.

##### STEPS TO REPRODUCE

```yaml
    - name: CREATE IPS ON THE DEVICE
      netbox_ip_address:
        netbox_url: "{{ var_netbox_url }}"
        netbox_token: "{{ var_netbox_token }}"
        validate_certs: no
        data:
          address: "{{ item.1.family.inet.address.0.name|default(omit) }}"
          # interface:
          #   name: "{{item.0.name}}.{{ item.1.name }}"
          #   device: "{{ ansible_net_hostname }}"
          description: "{{ item.1.description|default(omit) }}"
          tenant: hostvars[inventory_hostname].tenants
          assigned_object:
            name: "{{item.0.name}}.{{ item.1.name }}"
            device: "{{ ansible_net_hostname }}"
        state: present
      when: item.0.name == "lo0" or
            item.0.name == "irb"
      loop: "{{ lookup('subelements', test.parsed_output.configuration.interfaces.interface, 'unit', {'skip_missing': True}) }}"
      delegate_to: localhost
```

##### EXPECTED RESULTS

Would be helpful if hostvars will work.

##### ACTUAL RESULTS

WITHOUT BRACKETS tenant: hostvars[inventory_hostname].tenants

```
failed: [mydevice] (item=[{'name': 'irb'}, {'name': 1702, 'description': 'Public', 'family': {'inet': {'address': [{'name': '10.1.1.1/16'}]}}}]) => {"ansible_loop_var": "item", "changed": false, "item": [{"name": "irb"}, {"description": "Public", "family": {"inet": {"address": [{"name": "10.1.1.1/16"}]}}, "name": 1702}], "msg": "Could not resolve id of tenant: hostvarsinventory_hostname-tenants"}
```

WITH BRACKETS tenant: "{{hostvars[inventory_hostname].tenants}}"

```
failed: [mydevice] (item=[{'name': 'irb'}, {'name': 1702, 'description': 'Public', 'family': {'inet': {'address': [{'name': '10.1.1.1/16'}]}}}]) => {"ansible_loop_var": "item", "changed": false, "item": [{"name": "irb"}, {"description": "Public", "family": {"inet": {"address": [{"name": "10.1.1.1/16"}]}}, "name": 1702}], "module_stderr": "/home/user1/ansible2/lib64/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.100'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netbox_ip_address_payload_mze4olw6/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py\", line 389, in <module>\n  File \"/tmp/ansible_netbox_ip_address_payload_mze4olw6/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py\", line 384, in main\n  File \"/tmp/ansible_netbox_ip_address_payload_mze4olw6/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 35, in __init__\n  File \"/tmp/ansible_netbox_ip_address_payload_mze4olw6/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 511, in __init__\n  File \"/tmp/ansible_netbox_ip_address_payload_mze4olw6/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1011, in _normalize_data\n  File \"/tmp/ansible_netbox_ip_address_payload_mze4olw6/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 979, in _to_slug\n  File \"/usr/lib64/python3.6/re.py\", line 191, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\nTypeError: expected string or bytes-like object\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
