### ISSUE TITLE
netbox_site: Not idempotent on v3.0 when using latitude/longitude.

### ISSUE THREAD

**Issue by devon-mar** [netbox-community/ansible_modules#618]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

v2.11.6

###### Netbox:

v3.0.8

###### Collection:

v3.2.0

##### SUMMARY

NetBox v3.0 uses a float instead of a string to store the latitude and longitude. The module uses a string and is no longer idempotent with v3.0.

##### STEPS TO REPRODUCE

```yaml
---
- name: "Test Netbox site module"
  connection: local
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create a site
      netbox_site:
        data:
          name: Test Site
          latitude: 22.123
        state: present
```

##### EXPECTED RESULTS

The site is not changed.

##### ACTUAL RESULTS

The module reports changed.

```
TASK [Create a site] ******************************************************************************************
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "latitude": 22.123
+    "latitude": "22.123"
 }

changed: [localhost]
```
