### ISSUE TITLE
netbox_tenant is broken on v2.11.12 and v3.07

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/ansible_modules#620]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible 2.10.14
  config file = /home/tdavis/gitlab/omni-dcim/ansible.cfg
  configured module search path = ['/home/tdavis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/ansible210/lib64/python3.9/site-packages/ansible
  executable location = /usr/local/ansible210/bin/ansible
  python version = 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]

###### Netbox:

Tested on both v2.11.12 and v3.0.7

###### Collection:

v3.1.1

I know there is a newer version, but I have not seen any changes that would affect this.

##### SUMMARY

netbox_tenant is doing several things, depending on several conditions.

1) if the tenant already exists, it errors out.
2) if the tenant doesn't exist, it creates it.. but the next tenant it creates overwrites the previous tenant.

##### STEPS TO REPRODUCE

1) create 'tenant-2' in your netbox instance, not by the ansible module.

```yaml

---

- name: test tenant module
  hosts:
    - localhost

  gather_facts: False

  connection: local

  collections:
    - netbox.netbox

  vars:
    tenants:
      - name: tenant-1
      - name: tenant-2
      - name: tenant-3

  pre_tasks:
    - name: get netbox url/token from environment
      set_fact:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
      run_once: true
      tags:
        - always

  tasks:
    - name: create the tenants
      netbox.netbox.netbox_tenant:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          tenant_group: "{{ item.group | default(omit) }}"
          description: "{{ item.description | default(omit) }}"
          comments: "{{ item.comments | default(omit) }}"
          slug: "{[ item.slug | default(omit) }}"
          tags: "{{ item.tags | default(omit) }}"
          custom_fields: "{{ item.custom_fields | default(omit) }}"
        state: present
        validate_certs: false
      loop: "{{ tenants }}"
      ignore_errors: true

    - name: get tenant-1 back.
      set_fact:
        tenant1: "{{ query('netbox.netbox.nb_lookup', 'tenants',
          api_endpoint=netbox_url,
          api_filter='name=tenant-1',
          raw_data=true,
          token=netbox_token) }}"

    - name: dump what we get back for tenant-1.
      debug:
        msg: "{{ tenant1 }}"

    - name: get tenant-3 back.
      set_fact:
        tenant3: "{{ query('netbox.netbox.nb_lookup', 'tenants',
          api_endpoint=netbox_url,
          api_filter='name=tenant-3',
          raw_data=true,
          token=netbox_token) }}"

    - name: dump what we get back.
      debug:
        msg: "{{ tenant3 }}"

```

##### EXPECTED RESULTS

tenants being updated or created and not overwritten.

##### ACTUAL RESULTS

tenant exists, error occurs.
tenant does not exists, creation, but tenant is deleted when the next tenant is created.

```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does
not match 'all'

PLAY [test tenant module] ***********************************************************************************

TASK [get netbox url/token from 1password] ******************************************************************
ok: [localhost]

TASK [create the tenants] ***********************************************************************************
changed: [localhost] => (item={'name': 'tenant-1'})
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'name': ['tenant with this name already exists.']}
failed: [localhost] (item={'name': 'tenant-2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "tenant-2"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1634926471.202019-2372613-208353715774876/AnsiballZ_netbox_tenant.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1634926471.202019-2372613-208353715774876/AnsiballZ_netbox_tenant.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1634926471.202019-2372613-208353715774876/AnsiballZ_netbox_tenant.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_tenant', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netbox.netbox.netbox_tenant_payload_h3e7718w/ansible_netbox.netbox.netbox_tenant_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_tenant.py\", line 200, in <module>\n  File \"/tmp/ansible_netbox.netbox.netbox_tenant_payload_h3e7718w/ansible_netbox.netbox.netbox_tenant_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_tenant.py\", line 196, in main\n  File \"/tmp/ansible_netbox.netbox.netbox_tenant_payload_h3e7718w/ansible_netbox.netbox.netbox_tenant_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_tenancy.py\", line 59, in run\n  File \"/tmp/ansible_netbox.netbox.netbox_tenant_payload_h3e7718w/ansible_netbox.netbox.netbox_tenant_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1143, in _ensure_object_exists\n  File \"/tmp/ansible_netbox.netbox.netbox_tenant_payload_h3e7718w/ansible_netbox.netbox.netbox_tenant_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1122, in _update_netbox_object\n  File \"/usr/local/ansible210/lib64/python3.9/site-packages/pynetbox/core/response.py\", line 488, in update\n    return self.save()\n  File \"/usr/local/ansible210/lib64/python3.9/site-packages/pynetbox/core/response.py\", line 460, in save\n    if req.patch({i: serialized[i] for i in diff}):\n  File \"/usr/local/ansible210/lib64/python3.9/site-packages/pynetbox/core/query.py\", line 413, in patch\n    return self._make_call(verb=\"patch\", data=data)\n  File \"/usr/local/ansible210/lib64/python3.9/site-packages/pynetbox/core/query.py\", line 282, in _make_call\n    raise RequestError(req)\npynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'name': ['tenant with this name already exists.']}\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
changed: [localhost] => (item={'name': 'tenant-3'})
...ignoring

TASK [get tenant-1 back.] ***********************************************************************************
ok: [localhost]

TASK [dump what we get back for tenant-1.] ******************************************************************
ok: [localhost] => {
    "msg": []
}

TASK [get tenant-3 back.] ***********************************************************************************
ok: [localhost]

TASK [dump what we get back.] *******************************************************************************
ok: [localhost] => {
    "msg": [
        {
            "circuit_count": 0,
            "comments": "",
            "created": "2021-10-22",
            "custom_fields": {},
            "description": "",
            "device_count": 0,
            "display": "tenant-3",
            "group": null,
            "id": 15,
            "ipaddress_count": 0,
            "last_updated": "2021-10-22T18:14:32.867682Z",
            "name": "tenant-3",
            "prefix_count": 0,
            "rack_count": 0,
            "site_count": 0,
            "slug": "-item-slug-defaultomit-",
            "tags": [],
            "url": "https://netbox-192-168-84-1.nip.io/api/tenancy/tenants/15/",
            "virtualmachine_count": 0,
            "vlan_count": 0,
            "vrf_count": 0
        }
    ]
}

PLAY RECAP **************************************************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   


```
