### ISSUE TITLE
Bug: Invalid query parameters applied to VM API

### ISSUE THREAD

**Issue by loganbest** [netbox-community/ansible_modules#63]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using the `query_filters` option and the `serial` filter, all virtual machines are returned due to `serial` not being a valid query filter (or field) for virtual machines. Netbox ignores invalid query parameters and returns all results matching the other (if any) filters.

The offending line is here: 
https://github.com/netbox-community/ansible_modules/blob/devel/plugins/inventory/netbox.py#L418

Some additional parsing of query parameters is needed to remove anything invalid for virtual-machines.

Original Ansible Core Issues:
https://github.com/ansible/ansible/issues/57376

@tyler-8 was the original reporter.

##### STEPS TO REPRODUCE

- Add device with serial number ABC1234 to Netbox
- Add VM to netbox

```yaml
# netbox_inventory.yml
plugin: netbox
api_endpoint: http://localhost:8000
validate_certs: True
config_context: False
group_by:
  - device_roles
query_filters:
  - serial: ABC1234
```

##### EXPECTED RESULTS
One device returned in inventory

##### ACTUAL RESULTS
One device and one VM returned in inventory
