### ISSUE TITLE
[Bug]: netbox.netbox.netbox_rack Issue while using custom field with type 'Integer'

### ISSUE THREAD

**Issue by rmammadli** [netbox-community/ansible_modules#642]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.10

###### NetBox:

3.0.8

###### Collection:

3.3.0

##### SUMMARY

We are facing an issue while using custom field with data type 'Integer' in module **netbox_rack**

##### STEPS TO REPRODUCE

```
- name: Create rack
  netbox.netbox.netbox_rack:
    netbox_url: "{{ netbox_url }}" 
    netbox_token:  "{{ netbox_token }}"
    data:
      name: TestRack
      site: TestSite
      # please pay attention to API description of pre-defined custom fields
      # for example: curl -X GET "https://netbox-instance.de/api/dcim/racks/
      custom_fields:
        matkatnr: 1234567
      u_height: 19
      width: 47
      status: planned
    state: present
```

Using filter to force converting to integer **'| int'** did not help.

##### EXPECTED RESULTS

Custom field with data type integer will accept the numeric values.

##### ACTUAL RESULTS

Please see the error below:
```
Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1636133868.6521611-257-251271308279819/AnsiballZ_netbox_rack.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1636133868.6521611-257-251271308279819/AnsiballZ_netbox_rack.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1636133868.6521611-257-251271308279819/AnsiballZ_netbox_rack.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_rack', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netbox.netbox.netbox_rack_payload_2sv2f6zx/ansible_netbox.netbox.netbox_rack_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_rack.py\", line 321, in <module>\n  File \"/tmp/ansible_netbox.netbox.netbox_rack_payload_2sv2f6zx/ansible_netbox.netbox.netbox_rack_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_rack.py\", line 317, in main\n  File \"/tmp/ansible_netbox.netbox.netbox_rack_payload_2sv2f6zx/ansible_netbox.netbox.netbox_rack_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_dcim.py\", line 201, in run\n  File \"/tmp/ansible_netbox.netbox.netbox_rack_payload_2sv2f6zx/ansible_netbox.netbox.netbox_rack_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1189, in _ensure_object_exists\n  File \"/tmp/ansible_netbox.netbox.netbox_rack_payload_2sv2f6zx/ansible_netbox.netbox.netbox_rack_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 1168, in _update_netbox_object\n  File \"/usr/lib/python3.9/site-packages/pynetbox/core/response.py\", line 553, in update\n    return self.save()\n  File \"/usr/lib/python3.9/site-packages/pynetbox/core/response.py\", line 526, in save\n    if req.patch(updates):\n  File \"/usr/lib/python3.9/site-packages/pynetbox/core/query.py\", line 415, in patch\n    return self._make_call(verb=\"patch\", data=data)\n  File \"/usr/lib/python3.9/site-packages/pynetbox/core/query.py\", line 282, in _make_call\n    raise RequestError(req)\npynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'__all__': [\"Invalid value for custom field 'matkatnr': Value must be an integer.\"]}\n
```

Sorry if debug message / error output is not as expected, actually just copied from pipeline.

If there is a need for formatted output, please just let me know.
