### ISSUE TITLE
Idempotency is broken if vid is declared as a string

### ISSUE THREAD

**Issue by FurryJulie** [netbox-community/ansible_modules#65]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When a vid is declared with a string as its vid, the vlan is correctly created in netbox but idempotency is broken.
before will be int and after will be string so changed will always be true.

This is also the case for other modules.

##### STEPS TO REPRODUCE

```yaml
- name: "netbox add vlans"
  netbox_community.ansible_modules.netbox_vlan:
    netbox_token: "{{ netbox['token'] }}"
    netbox_url: "{{ netbox['url'] }}"
    validate_certs: "no"
    data:
      status: "Active"
      vid: "{{ item['vlanid'] }}"
      name: "{{ item['name'] }}"
      site: "{{ item['location'] }}"
  connection: local
  delegate_to: localhost
  loop: "{{ subnet|flatten(levels=1) }}"
```

```yaml
 - vlanid: "42"
  name: "vlaname"
  location: "xxx"
```

##### EXPECTED RESULTS
```
    "ansible_loop_var": "item",
    "changed": false,
    "diff": {
        "after": {},
        "before": {}
    },
```

##### ACTUAL RESULTS
```
    "ansible_loop_var": "item",
    "changed": true,
    "diff": {
        "after": {
            "vid": "42"
        },
        "before": {
            "vid": 42
        }
    },
```

**Comment by FurryJulie** [comment]
In fact, the vid is always sent as a sting even with:

```yaml
 - vlanid: 42
  name: "vlaname"
  location: "xxx"
```

In the task, the line `vid: "{{ item['vlanid'] }}"` force the value to be a string.
