### ISSUE TITLE
Some Modules fail if there are duplicate parameters - netbox_region 

### ISSUE THREAD

**Issue by beano38** [netbox-community/ansible_modules#654]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
ansible [core 2.11.6]
  config file = /Users/beelder/Desktop/testing/infrastructure-as-code/ansible.cfg
  configured module search path = ['/Users/beelder/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/beelder/Desktop/testing/infrastructure-as-code/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
  python version = 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) [Clang 6.0 (clang-600.0.57)]
  jinja version = 2.11.2
  libyaml = True

###### NetBox:
3.0.10

###### Collection:
netbox.netbox 3.3.0

##### SUMMARY
netbox.netbox.netbox_region, when going thru a list of hosts, some hosts have the same "region" parameters assigned to them in the group vars. The api creates the first one, then errors out when the duplicate second one is applied.

Similar problems with duplicate parameters fail with netbox_site and netbox_rack.

##### STEPS TO REPRODUCE
I started from scratch with a new netbox-docker setup.  And anytime I delete the regions and try to start over I get the same error.

```yaml
- hosts: cml_nes
  connection: local
  gather_facts: False
  collections:
    - netbox.netbox

  tasks:
    - name: Load netbox variables
      include_vars:
        file: inventories/lab/host_vars/netbox.local.yml
        name: netbox
      tags: [ 'always' ]
      run_once: True

    - name: DEBUGGGGGGGINNNN
      debug:
        msg: "{{ region }}"

    - name: Setup Region
      vars:
        - netbox_state: present
      netbox_region:
        netbox_url: "{{ netbox.url }}"
        netbox_token: "{{ netbox.token }}"
        data:
          name: "{{ region.name }}"
          slug: "{{ region.slug | lower }}"
          parent_region: "{{ region.parent_region | lower }}"
        state: "{{ netbox_state }}"
```
Inventory File, the region parameters are in the "east" and "virtual_lab" group_vars
```yaml
all:
  children:
    core:
      hosts:
        evpn-p0-rtr:
        evpn-p1-rtr:
    abr:
      hosts:
        evpn-pe0-rtr:
        evpn-pe1-rtr:
        evpn-pe2-rtr:
        evpn-pe3-rtr:
    pce:
      hosts:
        evpn-rr0-rtr:
        evpn-rr1-rtr:
    rr:
      hosts:
        evpn-rr0-rtr:
        evpn-rr1-rtr:
    cml:
      hosts:
        ext-conn-1:
        unmanaged-switch-1:

    cml_nes:
      hosts:
        evpn-p[0:1]-rtr:
        evpn-pe[0:3]-rtr:
        evpn-rr[0:1]-rtr:
        ext-conn-1:
        unmanaged-switch-1:
    nes:
      hosts:
        evpn-p[0:1]-rtr:
        evpn-pe[0:3]-rtr:
        evpn-rr[0:1]-rtr:

    servers:
        hosts:
          cml.local:
          nso.local:
          netbox.local:

east:
  children:
    site1:
      hosts:
        evpn-p[0:1]-rtr:
        evpn-pe[0:1]-rtr:
    site2:
      hosts:
        evpn-pe[2:3]-rtr:
    site3:
      hosts:
        evpn-rr[0:1]-rtr:
virtual_lab:
  children:
    virtual:
      hosts:
        ext-conn-1:
        unmanaged-switch-1:


device_types:
  children:
    xrv9000:
      hosts:
        evpn-p[0:1]-rtr:
        evpn-pe[0:3]-rtr:
        evpn-rr[0:1]-rtr:
    unmanaged_switch:
      hosts:
        unmanaged-switch-1:
    ext_conn:
      hosts:
        ext-conn-1:

```

east.yml group_var file
```yaml
---
region:
  name: East
  id: 1
  slug: east
  parent_region: IN
```

##### EXPECTED RESULTS
any duplicate region that it tries to build would be "green" and move on to the next host_var in the hosts list. 

##### ACTUAL RESULTS
The second (or greater) host that has a duplicate region parameter fails, and due to ansible will not continue to do further tasks on that host.  The two unique regions do build successfully in the Netbox UI.

```
 % ansible-playbook -i inventories/lab netbox_bootstrap.yml

PLAY [cml_nes] ***********************************************************************************************************************************************************************************

TASK [Load netbox variables] *********************************************************************************************************************************************************************
ok: [evpn-p0-rtr]

TASK [DEBUGGGGGGGINNNN] **************************************************************************************************************************************************************************
ok: [evpn-p0-rtr] => {
    "msg": {
        "id": 1,
        "name": "East",
        "parent_region": "IN",
        "slug": "east"
    }
}
ok: [evpn-p1-rtr] => {
    "msg": {
        "id": 1,
        "name": "East",
        "parent_region": "IN",
        "slug": "east"
    }
}
ok: [evpn-pe0-rtr] => {
    "msg": {
        "id": 1,
        "name": "East",
        "parent_region": "IN",
        "slug": "east"
    }
}
ok: [evpn-pe1-rtr] => {
    "msg": {
        "id": 1,
        "name": "East",
        "parent_region": "IN",
        "slug": "east"
    }
}
ok: [evpn-pe2-rtr] => {
    "msg": {
        "id": 1,
        "name": "East",
        "parent_region": "IN",
        "slug": "east"
    }
}
ok: [evpn-pe3-rtr] => {
    "msg": {
        "id": 1,
        "name": "East",
        "parent_region": "IN",
        "slug": "east"
    }
}
ok: [evpn-rr0-rtr] => {
    "msg": {
        "id": 1,
        "name": "East",
        "parent_region": "IN",
        "slug": "east"
    }
}
ok: [evpn-rr1-rtr] => {
    "msg": {
        "id": 1,
        "name": "East",
        "parent_region": "IN",
        "slug": "east"
    }
}
ok: [ext-conn-1] => {
    "msg": {
        "id": 99999,
        "name": "Virtual Lab",
        "parent_region": "IN",
        "slug": "virt_lab"
    }
}
ok: [unmanaged-switch-1] => {
    "msg": {
        "id": 99999,
        "name": "Virtual Lab",
        "parent_region": "IN",
        "slug": "virt_lab"
    }
}

TASK [Setup Region] ******************************************************************************************************************************************************************************
changed: [evpn-pe0-rtr]
fatal: [evpn-p1-rtr]: FAILED! => {"changed": false, "msg": "{\"name\":[\"region with this name already exists.\"],\"slug\":[\"region with this slug already exists.\"]}"}
fatal: [evpn-p0-rtr]: FAILED! => {"changed": false, "msg": "{\"error\": \"duplicate key value violates unique constraint \\\"dcim_region_name_key\\\"\\nDETAIL:  Key (name)=(East) already exists.\\n\", \"exception\": \"IntegrityError\", \"netbox_version\": \"3.0.10\", \"python_version\": \"3.9.5\"}"}
fatal: [evpn-pe2-rtr]: FAILED! => {"changed": false, "msg": "{\"name\":[\"region with this name already exists.\"],\"slug\":[\"region with this slug already exists.\"]}"}
ok: [evpn-pe1-rtr]
ok: [evpn-pe3-rtr]
ok: [evpn-rr0-rtr]
ok: [evpn-rr1-rtr]
changed: [ext-conn-1]
ok: [unmanaged-switch-1]

PLAY RECAP ***************************************************************************************************************************************************************************************
evpn-p0-rtr                : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
evpn-p1-rtr                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
evpn-pe0-rtr               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
evpn-pe1-rtr               : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
evpn-pe2-rtr               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
evpn-pe3-rtr               : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
evpn-rr0-rtr               : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
evpn-rr1-rtr               : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
ext-conn-1                 : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
unmanaged-switch-1         : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by rodvand** [comment]
This feels like a race condition to me.. Could you try adding `serial: 1` to your playbook and running it again?

**Comment by beano38** [comment]
Yes, ```serial: 1```  works, although creates a ton of output, and overall will take longer to execute the entire playbook.  My plan was to call many tasks for the one playbook that bootstraps all of the device, rack, site, region and etc.  Was this just a test to see if we're hitting the race condition.  Or is there/will there be a more suitable fix?

**Comment by rodvand** [comment]
Not sure how much we can do about this. The modules check if they find an existing object before updating or creating it. In this case it seems like all the forks checks pretty much at the same time so they all try to create the object. Naturally one of them succeeds while the others fail. I think your best bet is to rethink how to run these modules. Maybe add a random pause in front of each netbox command?

**Comment by beano38** [comment]
Thanks, so I discovered ```serial: 1``` is for the entire play.  There is a similar function to do that per task.  When using ```throttle: 1``` on the task, it prevents the race condition.

Playbook
```yaml
- hosts: cml_nes
  connection: local
  gather_facts: False
  # serial: 1
  collections:
    - netbox.netbox

  tasks:
    - name: Load netbox variables
      include_vars:
        file: inventories/lab/host_vars/netbox.local.yml
        name: netbox
      tags: [ 'always' ]
      run_once: True

    - name: DEBUGGGGGGGINNNN
      debug:
        msg: "{{ region }}"


    - name: Build Topology in Netbox
      vars:
        - netbox_state: present
      block:
        - include: tasks/netbox/region.yml
          throttle: 1
        - include: tasks/netbox/site.yml
          throttle: 1
        - include: tasks/netbox/rack.yml
          throttle: 1
        - include: tasks/netbox/device.yml
      tags: [ 'never', 'build_netbox' ]

    - name: Destroy Topology in Netbox
      vars:
        - netbox_state: absent
      block:
        - include: tasks/netbox/device.yml
        - include: tasks/netbox/rack.yml
          throttle: 1
        - include: tasks/netbox/site.yml
          throttle: 1
        - include: tasks/netbox/region.yml
          throttle: 1
      tags: [ 'never', 'destroy_netbox' ]
```
 The output is much more intuitive, and you only need to "throttle" the tasks that have common creation elements (several devices will be in a site, region, etc ..).

Thanks for the ideas rodvand!  You can close this.  Hopefully it helps someone in the future

output for posterity
```
PLAY [cml_nes] ***********************************************************************************************************************************************************************************

TASK [Load netbox variables] *********************************************************************************************************************************************************************
ok: [evpn-p0-rtr]

TASK [Remove Device from Inventory] **************************************************************************************************************************************************************
ok: [evpn-pe0-rtr]
ok: [evpn-p0-rtr]
ok: [evpn-pe2-rtr]
ok: [evpn-pe1-rtr]
ok: [evpn-p1-rtr]
ok: [evpn-pe3-rtr]
ok: [evpn-rr0-rtr]
ok: [evpn-rr1-rtr]
ok: [ext-conn-1]
ok: [unmanaged-switch-1]

TASK [Remove Racks] ******************************************************************************************************************************************************************************
ok: [evpn-p0-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-02-01', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-02-02', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-02-03', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-02-04', 'width': 19, 'height': 45})
ok: [evpn-p0-rtr] => (item={'name': 'R-01-02-05', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-01', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-02', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-03', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-04', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-05', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-01', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-02', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-03', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-04', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-05', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-01', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-02', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-03', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-04', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-05', 'width': 19, 'height': 45})
ok: [evpn-pe2-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-pe2-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-pe2-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-pe2-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-pe3-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-pe3-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-pe3-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-pe3-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-rr0-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-rr0-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-rr0-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-rr0-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-rr0-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})

TASK [Remove Site] *******************************************************************************************************************************************************************************
ok: [evpn-p0-rtr]
ok: [evpn-p1-rtr]
ok: [evpn-pe0-rtr]
ok: [evpn-pe1-rtr]
ok: [evpn-pe2-rtr]
ok: [evpn-pe3-rtr]
ok: [evpn-rr0-rtr]
ok: [evpn-rr1-rtr]
ok: [ext-conn-1]
ok: [unmanaged-switch-1]

TASK [Remove Region] *****************************************************************************************************************************************************************************
ok: [evpn-p0-rtr]
ok: [evpn-p1-rtr]
ok: [evpn-pe0-rtr]
ok: [evpn-pe1-rtr]
ok: [evpn-pe2-rtr]
ok: [evpn-pe3-rtr]
ok: [evpn-rr0-rtr]
ok: [evpn-rr1-rtr]
ok: [ext-conn-1]
ok: [unmanaged-switch-1]

PLAY RECAP ***************************************************************************************************************************************************************************************
evpn-p0-rtr                : ok=5    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
evpn-p1-rtr                : ok=4    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
evpn-pe0-rtr               : ok=4    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
evpn-pe1-rtr               : ok=4    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
evpn-pe2-rtr               : ok=4    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
evpn-pe3-rtr               : ok=4    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
evpn-rr0-rtr               : ok=4    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
evpn-rr1-rtr               : ok=4    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
ext-conn-1                 : ok=3    changed=0    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0
unmanaged-switch-1         : ok=3    changed=0    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0

beelder@BEELDER-M-3AN1 infrastructure-as-code % ansible-playbook -i inventories/lab netbox_bootstrap.yml -t build_netbox

PLAY [cml_nes] ***********************************************************************************************************************************************************************************

TASK [Load netbox variables] *********************************************************************************************************************************************************************
ok: [evpn-p0-rtr]

TASK [Setup East Region] *************************************************************************************************************************************************************************
changed: [evpn-p0-rtr]
ok: [evpn-p1-rtr]
ok: [evpn-pe0-rtr]
ok: [evpn-pe1-rtr]
ok: [evpn-pe2-rtr]
ok: [evpn-pe3-rtr]
ok: [evpn-rr0-rtr]
ok: [evpn-rr1-rtr]
ok: [ext-conn-1]
ok: [unmanaged-switch-1]

TASK [Setup Site] ********************************************************************************************************************************************************************************
changed: [evpn-p0-rtr]
ok: [evpn-p1-rtr]
ok: [evpn-pe0-rtr]
ok: [evpn-pe1-rtr]
changed: [evpn-pe2-rtr]
ok: [evpn-pe3-rtr]
changed: [evpn-rr0-rtr]
ok: [evpn-rr1-rtr]
ok: [ext-conn-1]
ok: [unmanaged-switch-1]

TASK [Setup Racks] *******************************************************************************************************************************************************************************
changed: [evpn-p0-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-02-01', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-02-02', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-02-03', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-02-04', 'width': 19, 'height': 45})
changed: [evpn-p0-rtr] => (item={'name': 'R-01-02-05', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-01', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-02', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-03', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-04', 'width': 19, 'height': 45})
ok: [evpn-p1-rtr] => (item={'name': 'R-01-02-05', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-01', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-02', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-03', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-04', 'width': 19, 'height': 45})
ok: [evpn-pe0-rtr] => (item={'name': 'R-01-02-05', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-01', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-02', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-03', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-04', 'width': 19, 'height': 45})
ok: [evpn-pe1-rtr] => (item={'name': 'R-01-02-05', 'width': 19, 'height': 45})
changed: [evpn-pe2-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
changed: [evpn-pe2-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
changed: [evpn-pe2-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
changed: [evpn-pe2-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-pe3-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-pe3-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-pe3-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-pe3-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
changed: [evpn-rr0-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
changed: [evpn-rr0-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
changed: [evpn-rr0-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
changed: [evpn-rr0-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
changed: [evpn-rr0-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-01', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-02', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-03', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-04', 'width': 19, 'height': 45})
ok: [evpn-rr1-rtr] => (item={'name': 'R-01-01-05', 'width': 19, 'height': 45})

TASK [Device Inventory] **************************************************************************************************************************************************************************
changed: [evpn-pe1-rtr]
changed: [evpn-p0-rtr]
changed: [evpn-pe0-rtr]
changed: [evpn-pe2-rtr]
changed: [evpn-p1-rtr]
changed: [evpn-rr0-rtr]
changed: [evpn-rr1-rtr]
changed: [ext-conn-1]
changed: [unmanaged-switch-1]
changed: [evpn-pe3-rtr]

TASK [Rack Layout] *******************************************************************************************************************************************************************************
changed: [evpn-pe1-rtr]
changed: [evpn-p1-rtr]
changed: [evpn-pe2-rtr]
changed: [evpn-p0-rtr]
changed: [evpn-pe3-rtr]
changed: [evpn-rr0-rtr]
changed: [evpn-rr1-rtr]
changed: [evpn-pe0-rtr]

PLAY RECAP ***************************************************************************************************************************************************************************************
evpn-p0-rtr                : ok=6    changed=5    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
evpn-p1-rtr                : ok=5    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
evpn-pe0-rtr               : ok=5    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
evpn-pe1-rtr               : ok=5    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
evpn-pe2-rtr               : ok=5    changed=4    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
evpn-pe3-rtr               : ok=5    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
evpn-rr0-rtr               : ok=5    changed=4    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
evpn-rr1-rtr               : ok=5    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
ext-conn-1                 : ok=3    changed=1    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0
unmanaged-switch-1         : ok=3    changed=1    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0
```
