### ISSUE TITLE
Python 2 compatibility issue with FileNotFoundError

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/ansible_modules#661]
##### ISSUE TYPE
 - Bug Report

##### SOFTWARE VERSIONS
- CentOS 7.9
- Python 2.7.5

###### Ansible:
- Ansible 2.9

###### NetBox:
- NetBox 3.0.11

###### Collection:
- 3.1.1

##### SUMMARY
Lookup plugin nb_lookup.py is not compatible with Python 2

##### STEPS TO REPRODUCE
Run any playbook containing a query to the nb_lookup plugin with e.g. the "api_endpoint" parameter missing.

```yaml
- name: Test NetBox DNS lookup
  hosts: localhost
  tasks:

    - name: Look up Devices
      debug:
          msg: "{{ query('netbox.netbox.nb_lookup',
                         'devices',
                         token='<redacted>') }}"
```

##### EXPECTED RESULTS
The lookup returns a proper error message.

##### ACTUAL RESULTS
```
PLAY [Test NetBox DNS lookup] *************************************************************************************

TASK [Gathering Facts] ********************************************************************************************
ok: [localhost]

TASK [Look up Devices] ********************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <type 'exceptions.NameError'>, original message: global name 'FileNotFoundError' is not defined"}

PLAY RECAP ********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

The reason is that PR #52 for issue #49 uses FileNotFoundError to catch the exception. This exception is only supported in Python 3.
