### ISSUE TITLE
nb_lookup fails to process pynetbox RecordSet object

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/ansible_modules#662]
##### ISSUE TYPE
 - Bug Report

##### SOFTWARE VERSIONS
- CentOS 7.9
- Python 2.7.5

###### Ansible:
- Ansible 2.9

###### NetBox:
- NetBox 3.0.11

###### Collection:
- 3.1.1

##### SUMMARY
The current version of the nb_lookup plugin seems to be broken at least with Netbox 3.11

##### STEPS TO REPRODUCE
Use nb_lookup e.g. to return a list of devices from Netbox.

```yaml
- name: Test NetBox DNS lookup
  hosts: localhost
  tasks:

    - name: Look up Devices
      debug:
          msg: "{{ query('netbox.netbox.nb_lookup',
                         'devices',
                         api_endpoint='https://192.168.106.105',
                         validate_certs=False,
                         token='<redacted>') }}"
```

##### EXPECTED RESULTS
A list of devices is returned.

##### ACTUAL RESULTS
```
PLAY [Test NetBox DNS lookup] *************************************************************************************

TASK [Gathering Facts] ********************************************************************************************
ok: [localhost]

TASK [Look up Devices] ********************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <type 'exceptions.TypeError'>, original message: iter() returned non-iterator of type 'RecordSet'"}

PLAY RECAP ********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

The reason is that pynetbox returns a RecordSet as the result of the call to the Netbox API. That is not an iterable, but it has an attribute that is.
