### ISSUE TITLE
netbox.netbox.netbox_platform use wrong slug instead of name for manufacturers variable

### ISSUE THREAD

**Issue by empusas** [netbox-community/ansible_modules#684]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
ansible 2.9.27

###### NetBox:
3.1.4

###### Collection:
3.4.0

##### SUMMARY
For the creating of platform in netbox,  one variable is the manufacturer. The module does not seem to use the name, but instead it´s own conversion to a lower case slug.
In my case the manufacturer was "Palo Alto" that I created with the slug "palo_alto". But the error shows that that the netbox_platfroms module was looking for "palo-alto" to retrieve the ID of the manufacturer.
After changing the slug for the manufacturer to "palo-alto" in netbox the script worked and created the platform.

##### STEPS TO REPRODUCE

Create the manufacturers with those scripts
```yaml
manufacturers:
  - name: Palo Alto
    slug: palo_alto
    description: Palo Alto
```
```yaml
---
- name: Include manufacturers of manufacturers.yml into the 'manufacturers' variable
  include_vars:
    file: dcim/manufacturers.yml

- name: Create NetBox Device Manufacturers
  netbox.netbox.netbox_manufacturer:
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    validate_certs: False
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      description: "{{ item.description | default(omit) }}"
    state: "{{ netbox_state }}"
  loop: "{{ manufacturers }}"
  when: manufacturers is defined
  run_once: yes
  tags: netbox_manufacturers
```

Then try to create the platforms with those scripts:
```yaml
platforms:
  - name: Palo Alto PanOS
    slug: paloalto_panos
    description: Palo Alto PanOS Platform
    manufacturer: Palo Alto
    napalm_driver:
```
```yaml
---
- name: Include Platforms of platforms.yml into the 'platforms' variable
  include_vars:
 
- name: Create NetBox Platforms
  netbox.netbox.netbox_platform:
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    validate_certs: False
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      description: "{{ item.description | default(omit) }}"
      manufacturer: "{{ item.manufacturer | default(omit) }}"
      napalm_args: "{{ item.napalm_args | default(omit) }}"
      napalm_driver: "{{ item.napalm_driver | default(omit) }}"
    state: present
  loop: "{{ platforms }}"
  when: platforms is defined
  run_once: yes
  tags: netbox_platform
```

##### EXPECTED RESULTS
changed: [localhost] => (item={'name': 'Palo Alto PanOS', 'slug': 'paloalto_panos', 'description': 'Palo Alto PanOS Platform', 'manufacturer': 'Palo Alto', 'napalm_driver': None})

##### ACTUAL RESULTS
failed: [localhost] (item={'name': 'Palo Alto PanOS', 'slug': 'paloalto_panos', 'description': 'Palo Alto PanOS Platform', 'manufacturer': 'Palo Alto', 'napalm_driver': None}) => {"ansible_loop_var": "item", "changed": false, "item": {"description": "Palo Alto PanOS Platform", "manufacturer": "Palo Alto", "name": "Palo Alto PanOS", "napalm_driver": null, "slug": "paloalto_panos"}, "msg": "Could not resolve id of manufacturer: **palo-alto**"}

```

```
