### ISSUE TITLE
[Nbinventory]How to get the napalm_driver ?

### ISSUE THREAD

**Issue by Zulzig** [netbox-community/ansible_modules#687]
##### ISSUE TYPE
 - Module question

###### Ansible:

ansible-config [core 2.11.4]

###### NetBox:
v2.11.12
###### Collection:
 3.1.1
##### SUMMARY
I would like to get the napalm driver name with a compose option, knows under the following variable:
platform.napalm_driver

##### STEPS TO REPRODUCE
create dynamic inventory with nbinventory

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.netbox.int
token: 12546adispado124
validate_certs: False
config_context: True
group_by:
- role
compose:
  ansible_napalm_driver_napalm_driver: platform.napalm_driver
  ansible_napalm_driver_id: platform.id
  ansible_platform_slug: platform.slug
query_filters:
- role: example
- status: active
- region: "emea"
device_query_filters:
- has_primary_ip: "true"
```

##### EXPECTED RESULTS
```yaml
           "mycisco-device": {
                "ansible_host": "192.168.100.24",
                "ansible_napalm_driver_id": "1296",
                "ansible_platform_slug": "cisco-16-12-5b",
                "ansible_napalm_driver_napalm_driver": "ios",
                "config_context": [
                    {
                        "device": [],
                        "deviceregion": [],
                        "devicerole": [
                            "dcdi"
                        ],
                        "devicesite": [],
                        "devicetype": [],
                        "features": {
                            "netflow-l2": {
                                "enabled": "True"
                            }
                        },
                        "manufacturer": [],
                       .....
```
##### ACTUAL RESULTS
```yaml
           "mycisco-device": {
                "ansible_host": "192.168.100.24",
                "ansible_napalm_driver_id": "1296",
                "ansible_platform_slug": "cisco-16-12-5b",
                "config_context": [
                    {
                        "device": [],
                        "deviceregion": [],
                        "devicerole": [
                            "dcdi"
                        ],
                        "devicesite": [],
                        "devicetype": [],
                        "features": {
                            "netflow-l2": {
                                "enabled": "True"
                            }
                        },
                        "manufacturer": [],
                       .....
```

**Comment by rodvand** [comment]
The napalm_driver is not available if you go to `/api/dcim/devices/<device-ID>` so it's hard to extract directly. Not sure if it scales to make a separate call fetching this info. I would suggest you raise a FR in the netbox repository to have the napalm_driver included in the platform section when fetching a device.

**Comment by Zulzig** [comment]
Dear rodvand,

Thank for your feedbacks. But with following output from `https://netbox.netbox.int/api/dcim/platforms/`

```yaml

   "results": [
        {
            "id": 1182,
            "url": "https://netbox.netbox.int/api/dcim/platforms/1182/",
            "display": "03.03.02.SE",
            "name": "03.03.02.SE",
            "slug": "cisco-03-03-02-se",
            "manufacturer": {
                "id": 36,
                "url": "https://netbox.netbox.int/api/dcim/manufacturers/36/",
                "display": "Cisco",
                "name": "Cisco",
                "slug": "cisco"
            },
            "napalm_driver": "ios",
            "napalm_args": null,
            "description": "",
            "custom_fields": {
                "airbusblacklisted": null,
                "eosecsupport": null,
                "eosupport": null,
                "manufacturerinfo": null
            },
            "created": "2020-09-01",
            "last_updated": "2020-09-01T13:22:23.898058Z",
            "device_count": 5,
            "virtualmachine_count": 0
        },
```
I don't understand the endpoint seems to be already call on the code.
https://github.com/netbox-community/ansible_modules/blob/cdf5f1aa742cfea3a7067216d8513e7d2c7fe164/plugins/inventory/nb_inventory.py#L784
