### ISSUE TITLE
Module does not flag unreachable netbox URL

### ISSUE THREAD

**Issue by mechanomancy** [netbox-community/ansible_modules#69]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

I mistakenly failed to wrap my netbox URL variable in quotes and curly brackets (e.g. I did ```netbox_url: nb_url``` instead of ```netbox_url: "{{ nb_url }}"```. Instead of failing with an error indicating that it could not reach this URL or could not correctly ping the API, it threw a device-specific error;
```bash
fatal: [lab-VM-host -> localhost]: FAILED! => changed=false
  msg: 'Multiple results found while searching for key: device'
```

Obviously this is a silly mistake on my part but I spent a significant amount of time troubleshooting my devices in my test environment and digging through old issues on this repository. Had it thrown an error indicating that the URL provided was unreachable or not working, I would had spotted it faster.

##### STEPS TO REPRODUCE

Environment:
```bash
$ ansible --version
ansible 2.9.1
  config file =REDACTED/ansible.cfg
  configured module search path = ['/home/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct  9 2019, 14:04:01) [GCC 5.4.0 20160609]

$ python --version
Python 3.6.8

```

```yaml
---
- name: test playbook
  hosts: "{{ host_group }}"
  gather_facts: yes
  collections:
    - netbox_community.ansible_modules
  vars:
     nb_url: http://localhost:8080
     nb_token: token_goes_here
  tasks:
  - name: Remove default interfaces for each system if present
    netbox_interface:
      netbox_url: nb_url #<- Note this is not wrapped in quotes and curly brackets
      netbox_token: nb_token
      data:
        device: "{{ inventory_hostname }}"
        name: "{{ ansible_default_ipv4.interface }}"
      state: absent
      validate_certs: no
    delegate_to: localhost
```

##### EXPECTED RESULTS

```bash
TASK [Remove default interfaces for each system if present] ************************************
fatal: [lab-VM-host -> localhost]: FAILED! => changed=false
  msg: 'Cannot reach URL: nb_url'
```
##### ACTUAL RESULTS

```bash
$ ansible-playbook test_playbook.yaml --extra-vars "host_group=lab-VM-host"
PLAY [test playbook] ************************************

TASK [Remove default interfaces for each system if present]************************************ 
fatal: [lab-VM-host -> localhost]: FAILED! => changed=false
  msg: 'Multiple results found while searching for key: device'

PLAY RECAP ************************************
lab-VM-host : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

```

```

**Comment by FragmentedPacket** [comment]
@mechanomancy Do you mind testing PR #80 and let me know if this fixes your issue?

**Comment by mechanomancy** [comment]
@FragmentedPacket , for sure, I'll have a look when I have a chance and let you know.

**Comment by mechanomancy** [comment]
@FragmentedPacket thanks that, I installed your branch and tested, results are below. It looks to be working as expected now;
Playbook:
```yaml
---
- name: Test playbook
  hosts: "{{ host_group }}"
  remote_user: "{{ login_username | default('test_user') }}"
  gather_facts: yes
  tasks:
    - name: Remove device
      netbox_community.ansible_modules.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ inventory_hostname }}"
        state: absent
        validate_certs: no
      delegate_to: localhost
```
Output:
```bash
# Testing without a URL
$ ansible-playbook test_playbook.yml \
--extra-vars "host_group=test-lab netbox_token=123 netbox_url=nb_url"
PLAY [Test playbook] *******************************************************************************************************

TASK [Remove device] *******************************************************************************************************
fatal: [test-lab -> localhost]: FAILED! => changed=false 
  msg: Failed to establish connection to Netbox API

PLAY RECAP *******************************************************************************************************
test-lab: ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  

# Retrying with a valid URL
$ ansible-playbook test_playbook.yml\
 --extra-vars "host_group=systems-lab netbox_token=123 netbox_url=$REAL_URL"

PLAY [Test playbook] *******************************************************************************************************

TASK [Remove device] *******************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pynetbox.core.query.RequestError: The request failed with code 403 Forbidden: {'detail': 'Invalid token'}
fatal: [systems-lab -> localhost]: FAILED! => changed=false 
   msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *******************************************************************************************************
test-lab: ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
