### ISSUE TITLE
Getting "Failed to establish connection to NetBox API" on 3.4.0 and higher

### ISSUE THREAD

**Issue by m-kratochvil** [netbox-community/ansible_modules#703]
##### ISSUE TYPE
Bug Report

###### Ansible:
ansible 2.10.15
  config file = /home/ccloud/ccloud-net/ansible.cfg
  configured module search path = ['/home/ccloud/ccloud-net/plugins/modules']
  ansible python module location = /home/ccloud/.venv/base210/lib/python3.8/site-packages/ansible
  executable location = /home/ccloud/.venv/base210/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]

###### NetBox:
2.9.3

###### Collection:
netbox.netbox         3.5.1

##### SUMMARY
I have an ansible playbook using the `netbox.netbox.netbox_ip_address` module.
This playbook was working fine with collection version 3.1.1 and pynetbox 6.1.2
After I upgraded the collection to version 3.4.0, I get error `Failed to establish connection to NetBox API`. No changes in the playbook.
Also tested with collection version 3.5.1 and pynetbox version 6.5.0

While I found quite a few references to the same error, none of those helped me resolve the issue.

Diff of the playbook output on collection versions 3.1.1 and 3.4.0 shows only one difference - on version 3.4.0 there is additional line directly under `"module_args":`

`"cert": null,`

I'm out of ideas and will appreciate any help.

##### STEPS TO REPRODUCE
```yaml
    - name: Assure DNS and PTR fields of the IP address are updated in Netbox.
      netbox.netbox.netbox_ip_address:
        netbox_url: https://netbox.fake.url
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ primary_ip4 }}/{{ prefix_length }}"
          vrf: "CC-MGMT"
          tenant: "Converged Cloud"
          custom_fields:
            PTR: "{{ primary_ip4 | ansible.netcommon.ipaddr('revdns') }}"
          dns_name: "{{ inventory_hostname }}.cloud"
        validate_certs: false
        state: "present"
      delegate_to: localhost
```

##### EXPECTED RESULTS
The playbook should complete without any issues, as it did on collection version 3.1.1

##### ACTUAL RESULTS
```
The full traceback is:
  File "/tmp/ansible_netbox.netbox.netbox_ip_address_payload_jqsjvo5t/ansible_netbox.netbox.netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 643, in _connect_netbox_api
    self.full_version = nb.status().get("netbox-version")
  File "/home/ccloud/.venv/base210/lib/python3.8/site-packages/pynetbox/core/api.py", line 183, in status
    status = Request(
  File "/home/ccloud/.venv/base210/lib/python3.8/site-packages/pynetbox/core/query.py", line 240, in get_status
    raise RequestError(req)
fatal: [fakehostname -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cert": null,
            "data": {
                "address": "10.46.100.130/25",
                "assigned_object": null,
                "custom_fields": {
                    "PTR": "130.100.46.10.in-addr.arpa."
                },
                "description": null,
                "dns_name": "fakednsname",
                "family": null,
                "interface": null,
                "nat_inside": null,
                "prefix": null,
                "role": null,
                "status": null,
                "tags": null,
                "tenant": "REDACTED",
                "vrf": "CC-MGMT"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.fake.url",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "Failed to establish connection to NetBox API"
}
```
