### ISSUE TITLE
[Bug]: netbox_config_context doesn't work with clusters..

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/ansible_modules#704]
##### ISSUE TYPE

 - Bug Report

##### SOFTWARE VERSIONS

bash-4.4# ansible-galaxy collection list

 /home/runner/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
omni.yamlmultifile 1.0.0  

 /usr/share/ansible/collections/ansible_collections
Collection          Version
------------------- -------
ansible.netcommon   2.5.0  
ansible.utils       2.4.3  
netbox.netbox       3.5.1  
onepassword.connect 2.2.0  
ovirt.ovirt         1.6.6  
bash-4.4# 

###### Ansible:

bash-4.4# ansible --version
ansible [core 2.12.1.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.8 (default, Aug 25 2021, 16:13:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
bash-4.4# 

##### SUMMARY

module isn't resolving clusters into the correct PK.

```
{
    "clusters": [
        "Incorrect type. Expected pk value, received str."
    ]
}
```

##### STEPS TO REPRODUCE

```yaml
- name: create the config_context for the cluster.
  netbox.netbox.netbox_config_context:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ cluster.name }}"
        #cluster_groups: [ "OMNI" ]
      clusters: [ "{{ cluster.name }}" ]
      data: "{{ cluster.config_context | to_json }}"
  when: cluster.config_context is defined
```

##### EXPECTED RESULTS

works.

##### ACTUAL RESULTS

```
{
    "clusters": [
        "Incorrect type. Expected pk value, received str."
    ]
}
```
