### ISSUE TITLE
More than one result returned for vlan

### ISSUE THREAD

**Issue by el-magneto** [netbox-community/ansible_modules#708]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It's impossible to add prefix do vlan and site when there are the same vlans assigned to different sites.

##### STEPS TO REPRODUCE

Playbook to reproduce problem:
```yaml
    - name: Add two sites
      netbox_site:
        netbox_url: xxx
        netbox_token: xxx
        data:
          name: "{{ item }}"
      with_list: [site_one, site_two]


    - name: Add the same  vlan to sites
      netbox.netbox.netbox_vlan:
        netbox_url: xxx
        netbox_token: xxx
        data:
          name: "vlan_one"
          vid: "1"
          site: "{{ item }}"
        state: present
      with_list: [site_one, site_two]

    - name: Add prefix for vlan in site
      netbox_prefix:
        netbox_url: xxx
        netbox_token: xxx
        data:
          prefix: "2.2.2.0/24"
          site: "site_one"
          vlan: "vlan_one"

```
##### EXPECTED RESULTS
Prefix is added to vlan in site. It works when adding prefix manually via GUI.

##### ACTUAL RESULTS
Prefix is not added. Netbox/plugin/API can't find specific vlan in specivfic site do add prefix.

```yaml
PLAY [test add vprefix] *******************************************************************************************************************************************

TASK [Add two sites] *******************************************************************************************************************************************
changed: [172.16.2.73] => (item=site_one)
changed: [172.16.2.73] => (item=site_two)

TASK [Add same name vlan to sites] *****************************************************************************************************************************
changed: [172.16.2.73] => (item=site_one)
changed: [172.16.2.73] => (item=site_two)

TASK [Add prefix for Interface IP address to Netbox (vlan)] ****************************************************************************************************
fatal: [172.16.2.73]: FAILED! => {"changed": false, "msg": "More than one result returned for vlan"}

PLAY RECAP *****************************************************************************************************************************************************
172.16.2.73                : ok=2    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


```

**Comment by rodvand** [comment]
In the last task try this:
```
- name: Add prefix for vlan in site
      netbox_prefix:
        netbox_url: xxx
        netbox_token: xxx
        data:
          prefix: "2.2.2.0/24"
          site: "site_one"
          vlan:
            name: "vlan one"
            site: "site_one"
```

**Comment by el-magneto** [comment]
It works this way. Also without the first site:

```yml
- name: Add prefix for vlan in site
      netbox_prefix:
        netbox_url: xxx
        netbox_token: xxx
        data:
          prefix: "2.2.2.0/24"
          vlan:
            name: "vlan one"
            site: "site_one"
```
Thank you!
