### ISSUE TITLE
lag in netbox_interface searches through all devices, not just current one

### ISSUE THREAD

**Issue by ignatenkobrain** [netbox-community/ansible_modules#71]
##### SUMMARY
Specifying `lag` for the `netbox_interface` searches through the all devices instead of specific one.

```yaml
netbox_interface:
  data:
    device: foo
    lag: bond0
```

will try to resolve `bond0` into the ID, however it will fail since it searches through all interfaces in Netbox. There is a code in `build_query_params()` to handle this case correctly, but `lag` option is a string and not dictionary. Changing it to dictionary of course helps since it triggers different codepath, but this leads to the duplication of the device information like following:

```yaml
netbox_interface:
  data:
    device: foo
    lag:
      device: foo
      name: bond0
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`netbox_ip_address` or `module_utils/net_tools/netbox/netbox_utils.py`

##### ANSIBLE VERSION
```paste below
ansible 2.9.4
  config file = /home/brain/Projects/gooddata/ansible/ansible.cfg
  configured module search path = ['/home/brain/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Dec 19 2019, 00:00:00) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/brain/Projects/gooddata/ansible/ansible.cfg) = True
DEFAULT_FORKS(/home/brain/Projects/gooddata/ansible/ansible.cfg) = 32
DEFAULT_ROLES_PATH(/home/brain/Projects/gooddata/ansible/ansible.cfg) = ['/home/brain/Projects/gooddata/ansible/roles']
DEFAULT_VAULT_IDENTITY(/home/brain/Projects/gooddata/ansible/ansible.cfg) = cloud
```

##### OS / ENVIRONMENT
Fedora 32 (Rawhide). Ansible from repos.

##### STEPS TO REPRODUCE
```yaml
- hosts: compute
  gather_facts: no
  tasks:
  - netbox_device:
      data:
        name: "{{ inventory_hostname }}"
        device_type: Gen10
        device_role: Compute
    delegate_to: localhost
  - netbox_interface:
      data:
        device: "{{ inventory_hostname }}"
        name: bond0
        form_factor: Link Aggregation Group (LAG)
    delegate_to: localhost
  - netbox_interface:
      data:
        device: "{{ inventory_hostname }}"
        name: eth0
        form_factor: SFP28 (25GE)
        lag: bond0
    delegate_to: localhost
```

##### EXPECTED RESULTS
Code is trying to find `bond0` LAG only for the device the `netbox_interface` operates.

##### ACTUAL RESULTS
```paste below
failed: [cmp0009.int.na1.pcigdc.com -> localhost] (item=p4p1) => {"ansible_job_id": "913767063681.40139", "ansible_loop_var": "item", "changed": false, "finished": 1, "item": "p4p1", "msg": "Multiple results found while searching for key: lag"}
```

---

Originally reported as https://github.com/ansible/ansible/issues/66955, but reproducible with this ansible-galaxy collection.
