### ISSUE TITLE
netbox_ip_address is not idempotent

### ISSUE THREAD

**Issue by ignatenkobrain** [netbox-community/ansible_modules#72]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
```
    - name: Assign the IP address based on inventory
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          interface:
            name: bond0
            device: "{{ device }}"
          address: "{{ item.value }}"
          dns_name: "{{ inventory_hostname_short }}.{{ item.key }}.{{ domain }}"
          description: "DNS zone: {{ item.key }}.{{ domain }}"
          status: Active
        state: present
      loop: "{{ ips | dict2items }}"
      async: 30
      poll: 1
      delegate_to: localhost
```

for some reason is not idempotent, this was not the case with ansible's core `netbox_ip_address`.

##### STEPS TO REPRODUCE

```yaml
# -e netbox_token=<token> -e netbox_url=<url>
---
- hosts: compute
  gather_facts: false
  strategy: free
  collections:
    - netbox_community.ansible_modules
  tasks:
    - name: Set device name to use further
      set_fact: device={{ inventory_hostname_short }}.{{ domain }}
    - name: Create a device
      netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ device }}"
          site: "{{ dc }}"
          status: Active
          device_type: ProLiant DL380 Gen10
          device_role: Compute
        state: present
      delegate_to: localhost
    - name: Create bond0
      netbox_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ device }}"
          name: bond0
          form_factor: Link Aggregation Group (LAG)
          enabled: yes
      delegate_to: localhost
    - name: Create physical interfaces under bond0
      netbox_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ device }}"
          name: "{{ item }}"
          form_factor: SFP28 (25GE)
          # XXX: https://github.com/ansible/ansible/issues/66955
          lag:
            device: "{{ device }}"
            name: bond0
          mode: Tagged
          tagged_vlans:
            - name: ext
              site: "{{ dc }}"
            - name: int
              site: "{{ dc }}"
          enabled: yes
      loop:
        - em5
        - p4p1
      async: 30
      poll: 1
      delegate_to: localhost
    - name: Assign the IP address based on inventory
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          interface:
            name: bond0
            device: "{{ device }}"
          address: "{{ item.value }}"
          dns_name: "{{ inventory_hostname_short }}.{{ item.key }}.{{ domain }}"
          description: "DNS zone: {{ item.key }}.{{ domain }}"
          status: Active
        state: present
      loop: "{{ ips | dict2items }}"
      async: 30
      poll: 1
      delegate_to: localhost
```

```
PLAY [compute] *********************************************************************************************************************************************************************

TASK [Set device name to use further] **********************************************************************************************************************************************
ok: [cmp0037.int.na1.pcigdc.com]

TASK [Create a device] *************************************************************************************************************************************************************
ok: [cmp0037.int.na1.pcigdc.com -> localhost]

TASK [Create bond0] ****************************************************************************************************************************************************************
ok: [cmp0037.int.na1.pcigdc.com -> localhost]

TASK [Create physical interfaces under bond0] **************************************************************************************************************************************
ok: [cmp0037.int.na1.pcigdc.com -> localhost] => (item=em5)
ok: [cmp0037.int.na1.pcigdc.com -> localhost] => (item=p4p1)

TASK [Assign the IP address based on inventory] ************************************************************************************************************************************
changed: [cmp0037.int.na1.pcigdc.com -> localhost] => (item={'key': 'ipmi', 'value': '10.12.0.135'})
changed: [cmp0037.int.na1.pcigdc.com -> localhost] => (item={'key': 'int', 'value': '10.12.48.135'})
changed: [cmp0037.int.na1.pcigdc.com -> localhost] => (item={'key': 'ext', 'value': '10.12.16.135'})

PLAY RECAP *************************************************************************************************************************************************************************
cmp0037.int.na1.pcigdc.com : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### EXPECTED RESULTS
Running playbook multiple times will show ok=6 changed=0

##### ACTUAL RESULTS
Running playbook multiple times shows ok=5 changed=1

---

Sorry for not minimal playbook example, since I had it written already and it was working fine with ansible's core version of netbox_ip_address.
