### ISSUE TITLE
Updating name of manufacturer is not possible

### ISSUE THREAD

**Issue by ignatenkobrain** [netbox-community/ansible_modules#73]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Updating manufacturers does not work, instead of updating name it fails.

##### STEPS TO REPRODUCE
```yaml
- netbox_manufacturers:
    data:
      name: "{{ item }}"
  loop:
    - dell
    - Dell
```

##### EXPECTED RESULTS
Manufacturer `dell` is created and then the name for it is updated to Dell

##### ACTUAL RESULTS
```
{"slug":["manufacturer with this slug already exists."]}
```
