### ISSUE TITLE
[Bug]: Site_data in nb_inventory not repeat for each device (Yaml anchor and alias in the inventory)

### ISSUE THREAD

**Issue by BeArchiTek** [netbox-community/ansible_modules#731]
### Ansible NetBox Collection version

v3.5.1

### Ansible version

```bash
ansible [core 2.12.2]
  config file = /root/ansible/ansible.cfg
  configured module search path = ['/root/ansible/library']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True
```

### Pip env
```bash
# pip freeze
ansible==5.2.0
ansible-core==2.12.2
ansible-lint==5.3.2
argcomplete==2.0.0
attrs==21.4.0
bcrypt==3.2.0
bracex==2.2.1
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.11
colorama==0.4.4
commonmark==0.9.1
cryptography==36.0.1
dbus-python==1.2.16
distro-info==1.0
dnspython==2.2.0
enrich==1.2.7
hvac==0.11.2
idna==3.3
Jinja2==3.0.3
jmespath==0.10.0
jsonschema==4.4.0
junos-eznc==2.6.3
jxmlease==1.0.3
lxml==4.7.1
MarkupSafe==2.0.1
ncclient==0.6.9
netaddr==0.8.0
packaging==21.3
paramiko==2.8.1
pycparser==2.21
pycurl==7.43.0.6
Pygments==2.11.2
PyGObject==3.38.0
PyNaCl==1.5.0
pynetbox==6.6.0
pyparsing==3.0.7
pyrsistent==0.18.1
pyserial==3.5
python-apt==2.2.1
PyYAML==6.0
requests==2.27.1
resolvelib==0.5.4
rich==11.1.0
ruamel.yaml==0.17.20
ruamel.yaml.clib==0.2.6
scp==0.14.2
six==1.16.0
tenacity==8.0.1
toml==0.10.2
transitions==0.8.10
unattended-upgrades==0.1
urllib3==1.26.8
wcmatch==8.3
xmltodict==0.12.0
yamlordereddictloader==0.4.0
yq==2.13.0
```

### NetBox version

v3.1.5

### Python version

3.9

### Steps to Reproduce

1. Create a inventory.yml using the netbox.netbox.nb_inventory plugin
```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox_url
validate_certs: True

site_data: True

compose:
  ansible_network_os: platform.slug
```

2. Use this inventory to fetch device informations

```bash
ansible-inventory -i inventory.ym -y --list --output generated.yml
```

### Expected Behavior

The site_data should be repeated in each device for a given site :

```
all:
  children:
    ungrouped:
      hosts:
        core1:
          ansible_network_os: junos
          custom_fields:
            ansible_connection: netconf
          device_roles:
          - cr
          device_types:
          - qfx10002-36q
          is_virtual: false
          local_context_data:
          - null
          locations:
          - eqx1
          manufacturers:
          - juniper
          platforms:
          - junos
          rack_role: core
          racks:
          - R203
          regions:
          - europe
          services: []
          sites:
          - id: 4
            asn: 4204000000
            asns: []
            circuit_count: 0
            contact_email: ''
            contact_name: ''
            contact_phone: ''
            created: '2022-02-08'
            custom_fields:
              opening_hours: ''
            description: ''
            device_count: 2
            display: site1
            facility: ''
            group: null
            last_updated: '2022-02-08T10:36:17.416553Z'
            latitude: ''
            longitude: ''
            name: site1
            physical_address: ''
            prefix_count: 25
            rack_count: 15
            shipping_address: ''
            slug: site1
            status:
              label: Active
              value: active
            tags:
            - color: 9e9e9e
              display: bar
              id: 26
              name: bar
              slug: bar
              url: https://netbox_url/api/extras/tags/26/
            - color: 2196f3
              display: datacenter
              id: 40
              name: datacenter
              slug: datacenter
              url: https://netbox_url/api/extras/tags/40/
            - color: 9e9e9e
              display: dc1es
              id: 32
              name: dc1es
              slug: dc1es
              url: https://netbox_url/api/extras/tags/32/
            - color: 9e9e9e
              display: es
              id: 25
              name: es
              slug: es
              url: https://netbox_url/api/extras/tags/25/
            tenant:
              display: tenant1
              id: 14
              name: tenant1
              slug: tenant1
              url: https://netbox_url/api/tenancy/tenants/14/
            time_zone: Europe/Madrid
            url: https://netbox_url/api/dcim/sites/4/
            virtualmachine_count: 0
            vlan_count: 0
          status:
            label: Active
            value: active
          tags:
          - staging
        core2:
          ansible_network_os: junos
          custom_fields:
            ansible_connection: netconf
          device_roles:
          - cr
          device_types:
          - qfx10002-36q
          is_virtual: false
          local_context_data:
          - null
          locations:
          - eqx1-r02
          - ba101001154
          manufacturers:
          - juniper
          platforms:
          - junos
          rack_role: core
          racks:
          - R203
          regions:
          - europe
          services: []
          sites:
          - id: 4
            asn: 4204000000
            asns: []
            circuit_count: 0
            contact_email: ''
            contact_name: ''
            contact_phone: ''
            created: '2022-02-08'
            custom_fields:
              opening_hours: ''
            description: ''
            device_count: 2
            display: site1
            facility: ''
            group: null
            last_updated: '2022-02-08T10:36:17.416553Z'
            latitude: ''
            longitude: ''
            name: site1
            physical_address: ''
            prefix_count: 25
            rack_count: 15
            shipping_address: ''
            slug: site1
            status:
              label: Active
              value: active
            tags:
            - color: 9e9e9e
              display: bar
              id: 26
              name: bar
              slug: bar
              url: https://netbox_url/api/extras/tags/26/
            - color: 2196f3
              display: datacenter
              id: 40
              name: datacenter
              slug: datacenter
              url: https://netbox_url/api/extras/tags/40/
            - color: 9e9e9e
              display: dc1es
              id: 32
              name: dc1es
              slug: dc1es
              url: https://netbox_url/api/extras/tags/32/
            - color: 9e9e9e
              display: es
              id: 25
              name: es
              slug: es
              url: https://netbox_url/api/extras/tags/25/
            tenant:
              display: tenant1
              id: 14
              name: tenant1
              slug: tenant1
              url: https://netbox_url/api/tenancy/tenants/14/
            time_zone: Europe/Madrid
            url: https://netbox_url/api/dcim/sites/4/
            virtualmachine_count: 0
            vlan_count: 0
          status:
            label: Active
            value: active
          tags:
          - staging

```

### Observed Behavior

The site_data are indicated on one device only, and all the others device of the same site only get a pointer to the site informations (*id001)

```
all:
  children:
    ungrouped:
      hosts:
        core1:
          ansible_network_os: junos
          custom_fields:
            ansible_connection: netconf
          device_roles:
          - cr
          device_types:
          - qfx10002-36q
          is_virtual: false
          local_context_data:
          - null
          locations:
          - eqx1
          manufacturers:
          - juniper
          platforms:
          - junos
          rack_role: core
          racks:
          - R203
          regions:
          - europe
          services: []
          sites:
          - &id001
            asn: 4204000000
            asns: []
            circuit_count: 0
            contact_email: ''
            contact_name: ''
            contact_phone: ''
            created: '2022-02-08'
            custom_fields:
              opening_hours: ''
            description: ''
            device_count: 2
            display: site1
            facility: ''
            group: null
            id: 4
            last_updated: '2022-02-08T10:36:17.416553Z'
            latitude: ''
            longitude: ''
            name: site1
            physical_address: ''
            prefix_count: 25
            rack_count: 15
            shipping_address: ''
            slug: site1
            status:
              label: Active
              value: active
            tags:
            - color: 9e9e9e
              display: bar
              id: 26
              name: bar
              slug: bar
              url: https://netbox_url/api/extras/tags/26/
            - color: 2196f3
              display: datacenter
              id: 40
              name: datacenter
              slug: datacenter
              url: https://netbox_url/api/extras/tags/40/
            - color: 9e9e9e
              display: dc1es
              id: 32
              name: dc1es
              slug: dc1es
              url: https://netbox_url/api/extras/tags/32/
            - color: 9e9e9e
              display: es
              id: 25
              name: es
              slug: es
              url: https://netbox_url/api/extras/tags/25/
            tenant:
              display: tenant1
              id: 14
              name: tenant1
              slug: tenant1
              url: https://netbox_url/api/tenancy/tenants/14/
            time_zone: Europe/Madrid
            url: https://netbox_url/api/dcim/sites/4/
            virtualmachine_count: 0
            vlan_count: 0
          status:
            label: Active
            value: active
          tags:
          - staging
        core2:
          ansible_network_os: junos
          custom_fields:
            ansible_connection: netconf
          device_roles:
          - cr
          device_types:
          - qfx10002-36q
          is_virtual: false
          local_context_data:
          - null
          locations:
          - eqx1-r02
          - ba101001154
          manufacturers:
          - juniper
          platforms:
          - junos
          rack_role: core
          racks:
          - R203
          regions:
          - europe
          services: []
          sites:
          - *id001
          status:
            label: Active
            value: active
          tags:
          - staging

```
