### ISSUE TITLE
[Bug]: Nested variable from site_data structure not working

### ISSUE THREAD

**Issue by BeArchiTek** [netbox-community/ansible_modules#734]
### Ansible NetBox Collection version

3.5.1

### Ansible version

```bash
ansible [core 2.12.2]
  config file = /root/ansible/ansible.cfg
  configured module search path = ['/root/ansible/library']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True
```

### NetBox version

v3.1.5

### Python version

3.9

### Steps to Reproduce

1. Create a new inventory file using netbox.netbox.nb_inventory plugin as below : 
```
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox-url
validate_certs: True

# Limite what we fetch
services: False
interfaces: False
fetch_all: False

# Fetch extra Data structure
site_data: True
prefixes: False

group_by:
  - role
  - site

compose:
  # Composition using device informations
  ansible_network_os: platform.slug
  # Working Var
  test_id: site.id
  test_nam: site.name
  test_slug: site.slug
  # Debug Var
  test_site: site
  # Not Working Var
  test_lat: site.latitude
  test_lon: site.longitude
  test_time: site.time_zone

query_filters:
  - role: foo
  - role: bar

```
2. Run the inventory file to fetch device information
```
```

### Expected Behavior

Be able to access site data variables (like site.longitude or site.physical_address)

### Observed Behavior

Except the variables already working before the site_data option (netbox.netbox < 3.5) the other variables are not working in the compose.

It's still possible to use it in the playbook later on with site.xx, so I am guessing it's an issue with the compose itself ?

Site data structure under a host :
```
site:
  asn: null
  asns:
  - asn: asn3
    display: asn3
    id: 3
    url: https://netbox-url/api/ipam/asns/3/
  circuit_count: 1
  comments: ''
  contact_email: ''
  contact_name: ''
  contact_phone: ''
  created: '2020-02-27'
  custom_fields:
    opening_hours: Monday to Friday -  08h00 to 20h00
    slack_channel: null
  description: Office1
  device_count: 1
  display: site1
  facility: ''
  group: null
  id: 129
  last_updated: '2022-02-08T19:14:52.044388Z'
  latitude: null
  longitude: null
  name: site1
  physical_address: address1
  prefix_count: 1
  rack_count: 0
  region:
    _depth: 3
    display: region3
    id: 1
    name: region3
    slug: region3
    url: https://netbox-url/api/dcim/regions/1/
  shipping_address: address1
  slug: site1
  status:
    label: Active
    value: active
  tags:
  tenant:
    display: tenant48
    id: 48
    name: tenant48
    slug: tenant48
    url: https://netbox-url/api/tenancy/tenants/48/
  time_zone: Europe/Paris
  url: https://netbox-url/api/dcim/sites/129/
  virtualmachine_count: 0
  vlan_count: 0

```

Duplicate of this site_data structure in test_site :
```
test_site:
  display: site1
  id: 129
  name: site1
  slug: site1
  url: https://netbox-url/api/dcim/sites/129/
```
