### ISSUE TITLE
[Bug]: nb_lookup vlans item.value.role.slug has no attribute slug (the same goes for item.value.role.name, etc)

### ISSUE THREAD

**Issue by ane-ruiz** [netbox-community/ansible_modules#736]
### Ansible NetBox Collection version

3.1.1

### Ansible version

```bash
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ane/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

### NetBox version

3.1.7

### Python version

3.8

### Steps to Reproduce

When I do a debug to show what I get when I do an nb_lookup query of the vlan, I can get the item.value.role.slug and item.value.role.name data, they return a string. When I save the variable like this it is correct.
But when I directly use item.value.role.name or item.value.role.slug in the "when" comparison part of the task to fulfil the condition of being a string or another, the result I get is "Has no attribute 'name' or Has no attribute 'slug'".

### Expected Behavior

What I expect is to be able to compare what I get from item.value.role.name or item.value.role.slug with the desired string in the same task that I perform the nb_lookup of the vlans.

For example: 

```
when: item.value.role.slug == "voip"
or
when: item.value.role.name == "VoIP"
```
Example of task:
```
    - name: Get voice vlan SIS
      set_fact:
        voice_vlan: '{{ item.value.vid }}' 
      loop: "{{ query('netbox.netbox.nb_lookup', 'vlans', api_endpoint=api_endpoint, api_filter=api_filter_site_vlans, validate_certs=False, token='XXXXXXXXXXXXXXXXXXXX') }}"
      when: item.value.role.name == "VoIP" 
      ignore_errors: yes
```

### Observed Behavior

When I run this task:

```
    - name: Get voice vlan SIS
      set_fact:
        voice_vlan: '{{ item.value.vid }}' 
      loop: "{{ query('netbox.netbox.nb_lookup', 'vlans', api_endpoint=api_endpoint, api_filter=api_filter_site_vlans, validate_certs=False, token='XXXXXXXXXXXXXXXXXXXX') }}"
      when: item.value.role.slug == "voip" 
      ignore_errors: yes
```

I obtain:

`"msg": "The conditional check 'item.value.role.name == \"VoIP\"' failed. The error was: error while evaluating conditional (item.value.role.name == \"VoIP\"): 'None' has no attribute 'name'`

But when I run in this way:

```
    - name: Get voice vlan SIS
      set_fact:
        voice_vlan: '{{ item.value.role.slug }}'
      loop: "{{ query('netbox.netbox.nb_lookup', 'vlans', api_endpoint=api_endpoint, api_filter=api_filter_site_vlans, validate_certs=False, token='XXXXXXXXXXXXXXXXXXXX') }}"
      when: item.value.vid == 924
      ignore_errors: yes
```
The result is correct:

```
ok: [device] => {
    "msg": "voip"
}
```
