### ISSUE TITLE
[Bug]: Multiple Racks cannot be added with same name even though location is unique

### ISSUE THREAD

**Issue by allan-silverstein** [netbox-community/ansible_modules#748]
### Ansible NetBox Collection version

v3.5.1

### Ansible version

```s$ ansible --version
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/asilver/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/asilver/pyvenv/conf_bkups/lib/python3.10/site-packages/ansible
  ansible collection location = /home/asilver/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/asilver/pyvenv/conf_bkups/bin/ansible
  python version = 3.10.1 (main, Jan 10 2022, 12:18:42) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True

```

### NetBox version

v3.1.8

### Python version

3.10

### Steps to Reproduce

I'm trying to use netbox.netbox.netbox_rack to add racks to netbox.  According to the Netbox documentation the name of a rack must be unique within a given location.  If the location is unique the rack name can be the same and I've confirmed this by adding multiple racks with the same name as long as the location is unique.  However, when trying to add the same exact racks using Ansible,  the last rack added just overwrites the previous one and only a single rack is added. 

Here is the task:
```

- name: "Populate Netbox Database"
  connection: local
  hosts: localhost
  gather_facts: false

  vars:
    netbox_url: "http://10.1.1.1:8000"
    netbox_token: xxxxxx

  vars_files:
    - racks_test.yaml

  tasks:
    - name: "Task 40. Rack Configuration."
      netbox.netbox.netbox_rack:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data: "{{ rack }}"
        state: present
      loop: "{{ racks }}"
      loop_control:
        loop_var: rack
        label: "{{ rack['name'] }}"
      tags: [ racks]

```

Here is a sample input file (racks_test.yaml)

```
racks:
  - name: BLS01
    site: Franklin
    location: Pod 1
    facility_id: D36
    type: 4-post frame
    u_height: 42
    width: 19
  - name: BLS01
    site: Franklin
    location: Pod 2
    facility_id: D37
    type: 4-post frame
    u_height: 42
    width: 19
  - name: BLS01
    site: Franklin
    location: Pod 3
    facility_id: D31
    type: 4-post frame
    u_height: 42
    width: 19
```

### Expected Behavior

Multiple racks should be able to be added with the same name if the location is unique

### Observed Behavior

when trying to add the same exact racks using Ansible,  the last rack added just overwrites the previous one and only a single rack is added even when the location is unique
