### ISSUE TITLE
[Feature]: Enable lowercase output direct into inventory

### ISSUE THREAD

**Issue by chrisvanmeer** [netbox-community/ansible_modules#760]
### NetBox version

v3.1.10

### Feature type

Change to existing Plugin

### Proposed functionality

Could it be possible to declare a parameter in the inventory YAML file to allow for lowercase output of the device / vm names? And also convert the spaces to dashes (-) so we could safely refer to a inventory name without having to convert it in the play / role.

All the rest of the fields already map to the slug part of the object, which is by default lowercase and eliminates all of the spaces by converting it to dashes.

### Use case

`$ cat netbox-inventory.yml`
```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.external.fqdn
group_names_raw: true
group_by:
  - tags
query_filters:
  - tag: lowercase
```
`$ ansible-inventory --graph -i netbox-inventory.yml`
```
@all:
  |--@lowercase:
  |  |--DeViCE 1
  |  |--Device 2 name
  |--@ungrouped:
```
## Proposed output
```
@all:
  |--@lowercase:
  |  |--device-1
  |  |--device-2-name
  |--@ungrouped:
```
