### ISSUE TITLE
[Housekeeping]: Clean up invocations in release.yml

### ISSUE THREAD

**Issue by artis3n** [netbox-community/ansible_modules#761]
### Proposed Changes

👋 Hi, I'm the maintainer of https://github.com/artis3n/ansible_galaxy_collection exploring some of the dependent uses of my Ansible Collection github action. I noticed the `release.yml` configuration in https://github.com/netbox-community/ansible_modules/blob/devel/.github/workflows/release.yml : 

You shouldn't need to install Python or install `ansible-base`. The action runs self-contained inside a Docker image. I'd recommend:

```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
```

but didn't want to push a PR because that seemed presumptuous.

### Justification

I'm the Action maintainer. Would shave maybe a second or two off your invocation 🤷‍♂️ No _need_ to make this change, but no need for the current 2 extra steps either.
