### ISSUE TITLE
[Feature]: Reset a field to blank

### ISSUE THREAD

**Issue by schmittvictor** [netbox-community/ansible_modules#776]
### NetBox version

v3.2.0

### Feature type

Change to existing Module

### Proposed functionality

Unless I'm mistaken there is no way to reset a field.

So it would be usefull that, for example, when setting a field to _None_ it would reset the field to blank.

### Use case

ex: 
```
- netbox.netbox.netbox_device_interface:
    data:
      device: Router
      name: GigabitEthernet0/0/0
      type: "other"
      mtu: None
    state: present
```

result: 
```
{
    "diff": {
        "after": {
            "mtu": null
        },
        "before": {
            "mtu": 1500
        }
    }
}
```
