### ISSUE TITLE
[Feature]: nb_inventory should have an option to fetch interfaces from all virtual-chassis members

### ISSUE THREAD

**Issue by SteveRodrigue** [netbox-community/ansible_modules#784]
### NetBox version

v2.11.6

### Feature type

Change to existing Module

### Proposed functionality

Setting a boolean to true should have the nb_inventory module to pull all interfaces from a device (master + child chassis from a virtual-chassis member).

At the moment, only direct interfaces are fetched when pulling interfaces information using nb_inventory.

Pseudo-code logic:
`if host is member of a virtual-chassis and virtual_chassis_all_interfaces == true then
  combine interfaces of all virtual-chassis members
return the combined interfaces list`

### Use case

When doing automation of network equipment, we always target the "master/primary" chassis and all members interfaces are configured/checked through this master chassis.

We almost never target a child chassis.

Also, this change in behaviour would reproduce the Web GUI interface. In the web version of Netbox, the master/primary chassis contains all interfaces of the virtual-chassis, so we can easily see and edit information from that single view. When using the Ansible module, we can't do the same (behaviour is not consistent).

### External dependencies

None that I can think of.

**Comment by hoalex** [comment]
Would also love to see this functionality. We have several switch stacks which are modeled as a virtual chassis, and right now there's no easy way to deploy the complete interface configuration in one go, e.g. via the Ansible Cisco IOS roles.

@SteveRodrigue Would you be willing to share the code of your "mini-role"?

**Comment by SteveRodrigue** [comment]
> Would also love to see this functionality. We have several switch stacks which are modeled as a virtual chassis, and right now there's no easy way to deploy the complete interface configuration in one go, e.g. via the Ansible Cisco IOS roles.
> 
> @SteveRodrigue Would you be willing to share the code of your "mini-role"?

@hoalex  Sharing the exact role would be a bit complicated.  But here is the abstracted logic...

**My current not optimal logic is:**
1. Register device information from netbox: `api/dcim/devices/?name={{ inventory_hostname }}`
2. Check if the device is member of a virtual_chassis: when registered_device['virtual_chassis']
3. Get the virtual-chassis members: `api/dcim/devices/?virtual_chassis_id=XXXX`
4. For all chassis members (except the master) I do a loop...,
4a.I query Netbox for their interfaces: `api/dcim/interfaces/?limit=0&device=xxxx`
4b. I simply merge all interfaces together into the master chassis. `interfaces: {{ interfaces + member.interfaces }}`
5. Now, the list of interfaces of Master contains all interfaces.

**To be honest, a streamlined logic would be this:**
1. Find the virtual_chassis ID from the master chassis.
2. Get all interfaces for the virtual chassis: `api/dcim/interfaces/?limit=0&virtual_chassis_id=XXX`
3. Replace the master `interfaces` variable with the list found in step 2.

**Comment by Syl4r-v** [comment]
Any progress with this? This would really make life easier...

**Comment by david-ramsden** [comment]
Using @SteveRodrigue suggestion, you _can_ do the following.

Using `netbox.netbox.nb_inventory` plugin, you need to compose three variables:

```yaml
compose:
  device_id: id
  virtual_chassis_id: virtual_chassis.id
  virtual_chassis_master_id: virtual_chassis.master.id
```

Also set `virtual_chassis_name: true` and of course ensure `interfaces: true`.

In your playbook, use `netbox.netbox.nb_lookup` to fetch member interfaces if the device ID (of the current host) is equal to the virtual chassis master ID. Query the `/api/dcim/interfaces` API endpoint using `netbox.netbox.nb_lookup` and use an `api_filter` to fetch the interfaces for the virtual chassis ID and exclude interfaces belonging to the master device. Why? Because we already have those in the interfaces host var. Then merge the virtual chassis member interfaces fact with the interfaces host var.

Example:

```yaml
  pre_tasks:
    - name: Virtual chassis interfaces
      when:
        - virtual_chassis_id is defined
        - (virtual_chassis_master_id | int ) == device_id
      block:
        - name: Virtual chassis interfaces | Fetch member interfaces
          ansible.builtin.set_fact:
            virtual_chassis_interfaces: "{{ query('netbox.netbox.nb_lookup', 'interfaces', raw_data=True,
                                              api_filter='virtual_chassis_id=' ~ virtual_chassis_id ~ ' device_id__n=' ~ device_id) }}"

        - name: Virtual chassis interfaces | Merge interfaces for master and member devices
          ansible.builtin.set_fact:
            interfaces: "{{ interfaces | union(virtual_chassis_interfaces) }}"
          when: virtual_chassis_interfaces is defined
```

Now you can use the `interfaces` host var as you usually would and it'll contain all the interfaces for the entire virtual chassis. For example in a Jinja2 template for a Cisco configuration:

```jinja2
#jinja2: lstrip_blocks: True
hostname {{ inventory_hostname }}
!
{% for interface in interfaces %}
interface {{ interface.name }}
 ...
!
{% endfor %}
```

This then works universally for both a virtual chassis and a non-virtual chassis.

Based on this, although it could be a feature enhancement, I don't think it's really required to alter `nb_inventory` to implement this functionality. It can be easily implemented as two tasks. And after 3 years, no one has taken on the task of implementing such a change to `nb_inventory`.
