### ISSUE TITLE
[Feature]: Update an object with its ID

### ISSUE THREAD

**Issue by schmittvictor** [netbox-community/ansible_modules#786]
### NetBox version

v3.2.1

### Feature type

Change to existing Module

### Proposed functionality

Possibility to update object data by mentionning its ID instead of its name to select it.

### Use case

Usefull for changing a device name or updating the data of a member of a virtual chassis that has no name.

ex:
```
- netbox.netbox.netbox_device:
    netbox_url: "{{ nb_url }}"
    netbox_token: "{{ nb_token }}"
    data:
      id: 12
      name: "{{ new_name }}"
```
