### ISSUE TITLE
[Bug]: netbox_ip_address prefix parameter does not accept ID

### ISSUE THREAD

**Issue by CaptAintHere** [netbox-community/ansible_modules#787]
### Ansible NetBox Collection version

v3.7.1

### Ansible version

```bash
ansible-playbook [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

### NetBox version

v3.2.3

### Python version

3.8

### Steps to Reproduce

Create a prefix in _IPAM --> Prefixes_ and get the associated ID
Then use the module `netbox_ip_address` to get an available address from this prefix :
```
- netbox.netbox.netbox_ip_address:
  data:
    prefix:
      id: 1
  netbox_token: "{{ netbox_api_token }}"
  netbox_url: "{{ netbox_url }}"
  state: new
```

### Expected Behavior

An available IP address from this prefix should be returned.

### Observed Behavior

We get the following message : `1 does not exist - please create first`
The following request is received by NetBox :
```
GET /api/ipam/prefixes/?prefix=4&limit=0 HTTP/1.1
```
I think it should be `id` instead of `prefix`
