### ISSUE TITLE
[Feature]: Set IP as primary in netbox.netbox.netbox_ip_address

### ISSUE THREAD

**Issue by jchmielniak** [netbox-community/ansible_modules#794]
### NetBox version

v3.2.4

### Feature type

Change to existing Module

### Proposed functionality

Module: netbox.netbox.netbox_ip_address
It should be possible to set IP as primary for VM/Device as it is in GUI. At the moment, you can assign IP address to VM/Device and interface, but you cannot set it as primary IP for this device.

### Use case

Creating IP with prefix and state:new allows to dynamically select IP address. There must be primary IP defined for use with netbox inventory. With this function, one can use netbox inventory imidiatelly.

**Comment by ThomasADavis** [comment]
It's a two step process - you create the IP, then you can assign that IP to the virtual device.

You cannot create the IP and set the primary_ip4/primary_ip6 at the same time.

We do this all the time -

```
    - name: and set as primary for that name.
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ vm.name }}"
          primary_ip4: "{{ interface.address }}"
          primary_ip6: "{{ interface.ipv6 | default(omit) }}"
      when:
        - interface.address is defined
        - interface.tags is defined
        - "'primary' in interface.tags"
      loop: "{{ vm.interfaces }}"
      loop_control:
        label: "{{ vm['name'] }} - {{ interface['address'] | default('unknown') }}"
        loop_var: interface
```
