### ISSUE TITLE
[Bug]: Netbox ansible custom_fields are not idempotent

### ISSUE THREAD

**Issue by DevFinGitGovSecChatOps** [netbox-community/ansible_modules#805]
### Ansible NetBox Collection version

3.7.1

### Ansible version

```bash
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /builds/<redacted-path>/.ve/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /builds/<redacted-path>/.ve/bin/ansible
  python version = 3.8.13 (default, Apr  5 2022, 17:15:15) [GCC 9.1.1 20190605 (Red Hat 9.1.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

- v3.2.0
- v3.2.5

### Python version

3.8

### Steps to Reproduce

```bash
ansible-playbook main.playbook --diff
```

Note:
`cf1` and `cf2` custom_fields are defined in netbox but not used in this run

```yml
- name: "Test SoT stuff"
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Setup prefix"
      netbox.netbox.netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "1.2.3.0/24"
          status: "Active"
          custom_fields:
            cf3: "something"
            cf4: "something_else"
```

### Expected Behavior

When running a playbook with `custom_fields`, I would expect the modules to be idempotent.
In this example I am defining **two** `custom_fields` in a `prefix` that has **four** `custom_fields` defined in netbox.

If nothing changed, I would expect the diff to be unchanged.

```bash
TASK [Setup prefix] ************************************************************
ok: [localhost] => (item={'prefix': '1.2.3.0/24', 'status': 'Active', 'custom_fields': {'cf3': 'something', 'cf4': 'something_else'}})
PLAY RECAP *********************************************************************
```

### Observed Behavior

However, instead of returning an "OK" Status, the run suggests there have been changes.

```bash
TASK [Setup prefix] ************************************************************
--- before
+++ after
@@ -1,5 +1,3 @@
custom_fields:
-  cf1: null
-  cf2: null
   cf3: something
   cf4: something_else
changed: [localhost] => (item={'prefix': '1.2.3.0/24', 'status': 'Active', 'custom_fields': {'cf3': 'something', 'cf4': 'something_else'}})
PLAY RECAP *********************************************************************
```
This is suboptimal, since I want to run a pipeline that checks for changes in netbox. It is hard to focus on what really changed, since the custom_fields suggest a change where none happened.
