### ISSUE TITLE
[Bug]: Automatic name-to-slug feature doesn't remove umlauts like Netbox GUI does

### ISSUE THREAD

**Issue by jantari** [netbox-community/ansible_modules#808]
### Ansible NetBox Collection version

3.7.1

### Ansible version

```bash
ansible [core 2.12.7]
  config file = /builds/it/fortigates/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Apr 30 2022, 16:49:16) [GCC 11.2.1 20220219]
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.2.2

### Python version

3.10

### Steps to Reproduce

```yaml
- name: Reproduce bug
  netbox.netbox.netbox_site:
    netbox_url: '{{ netbox_url }}'
    netbox_token: '{{ netbox_token }}'
    state: present
    data:
      name: '{{ item }}'
      tags: [FortiGate-Sync]
  loop:
    - Königliches Rechenzentrum
    - Skåne
    - Keep an eye on this site 👀
```

### Expected Behavior

The three site names should be "slugified" to:

- knigliches-rechenzentrum
- skne
- keep-an-eye-on-this-site

### Observed Behavior

The task fails all site names with "umlauts" and creates the site with the emoji, but with a different slug than what the Netbox UI would use:

```yaml
TASK [Reproduce slugification bug] ************************************************************************************
failed: [localhost] (item=Königliches Rechenzentrum) => changed=false
  ansible_loop_var: item
  item: Königliches Rechenzentrum
  msg: '{"slug":["Enter a valid \"slug\" consisting of letters, numbers, underscores or hyphens."]}'
failed: [localhost] (item=Skåne) => changed=false
  ansible_loop_var: item
  item: Skåne
  msg: '{"slug":["Enter a valid \"slug\" consisting of letters, numbers, underscores or hyphens."]}'
changed: [localhost] => (item=Keep an eye on this site 👀)
```

Netbox 3.2.2 UI slug for the last site:
![image](https://user-images.githubusercontent.com/25607767/177718294-cdb8c9b4-489b-4bb1-a049-b40b92feae2f.png)

What the netbox_site ansible action created (note the trailing hyphen):
![image](https://user-images.githubusercontent.com/25607767/177719160-ba2a1d23-8a03-4d71-9da0-adfbc3adeff0.png)

----

I've prepared a PR to fix both of these issues (umlauts causing an error and emojis producing a trailing slash)

**Comment by sc68cal** [comment]
I believe this needs to be fixed in netbox. Specifically, `letters` should mean any valid UTF8 character, for a slug

**Comment by jantari** [comment]
Maybe, maybe not. I definitely see the value in only allowing basic ASCII characters for values like the slug that essentially act as a unique identifier. If they'd allow RTL, non-breaking spaces, all the letter-lookalikes and other such Unicode goodness that wouldn't really result in a net usability benefit imo

The _displayname_ of all assets is already fully Unicode capable.

Whether Netbox changes their rules for characters allowed in slugs in the future or not, I think this module should stay aligned with their behavior and currently that is to strip these characters out. Personally I'm from Germany and perfectly OK with that :)

**Comment by sc68cal** [comment]
I see netbox-community/netbox#3741

In fact, https://github.com/netbox-community/netbox/issues/3741#issuecomment-617244630 says that 

> the fix for https://github.com/netbox-community/netbox/issues/3721 now allows general Unicode characters in the slug. Hence the code which generates the slug could be changed to allow everything through (except spaces to dashes)

So, again, I don't think coercing everything into ASCII is the correct approach.

**Comment by jantari** [comment]
1. https://github.com/netbox-community/netbox/issues/3741 is just a UI issue and was closed as being adressed by https://github.com/netbox-community/netbox/issues/3721 which in turn was closed by https://github.com/netbox-community/netbox/commit/606f3dacbb8e228270ae9896bcc4f41874db206d - but from my testing and by this users comment https://github.com/netbox-community/netbox/issues/3741#issuecomment-617244630 it is not actually resolved. The UI still strips all non-ASCII characters from autosuggested slugs and this is easy to verify. So https://github.com/netbox-community/netbox/issues/3741, while only a UI-side issue not relating directly to ansible, is in fact not fixed and may have been closed in error.
2.  If you read the diff and release note of https://github.com/netbox-community/netbox/commit/606f3dacbb8e228270ae9896bcc4f41874db206d, you'll see that it only ever applied to the slugs of tags specifically. The slugification logic of all other objects (e.g. sites) was not changed to allow unicode from what I can see.
3. Even WITH the changes made in https://github.com/netbox-community/netbox/commit/606f3dacbb8e228270ae9896bcc4f41874db206d (shipped in Netbox 2.7.2) and https://github.com/netbox-community/netbox/commit/8d547e99066782393e6725ea512ba71423607821 (shipped in Netbox 2.7.3), the creation of a tag with unicode characters in its slug still fails in the latest Netbox 3.2.2 both through the GUI and through the API / this ansible module:

    ```yaml
    - name: Reproduce slug error with tags that are supposed to allow unicode
      netbox.netbox.netbox_tag:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        state: present
        data:
          name: 'Testing Unicode: 台灣'
          slug: 'testing-unicode-台灣'
    ```

    As you can see I took the _exact_ test case from https://github.com/netbox-community/netbox/commit/606f3dacbb8e228270ae9896bcc4f41874db206d#diff-a3fd33970129d5cb92c21fe1dba39cae6f22ab4b1e0c39d903cdd128f24b1de8 and yet it still didn't work:

    ```
    TASK [Reproduce slugification bug with tags] *********************************************************************
    fatal: [localhost]: FAILED! => changed=false
      msg: '{"slug":["Enter a valid \"slug\" consisting of letters, numbers, underscores or hyphens."]}'
    ```

4. Remember that I'm not arguing for or against allowing unicode in slugs - that is a discussion for the Netbox application and its repository. The problem in this issue, with the ansible collection / modules, is that they will generate and attempt to pass a slug to the Netbox API that is simply not allowed _today_ and therefore results in a hard error. Hard errors due to invalid data **is** a bug, no matter what you personally think of Netbox' present-day behavior. That can be addresses separately in their repository if unicode support in slugs is important to you.
5. The documentation for this ansible collection repeatedly states: "This [referring to the slug] is auto-generated following NetBox rules if not provided" [example](https://github.com/netbox-community/ansible_modules/blob/8ef1932f2a40d1d913429e939d8da0abcd927c9d/plugins/modules/netbox_tag.py#L40) but as is shown and reproducible here, that is not true. The slug is generated differently from NetBox rules, again (imo) fairly clearly making this a bug


---

I am a little sorry for the lengthy response, I am not a native english speaker and I don't mean any of it as an attack.

If Netbox' rules for this ever change, PR #809 can be rolled back to support the new behavior (aka unicode) and everything is going to be fine - but most importantly, no hard errors for the users due to invalid slugs.

**Comment by jantari** [comment]
Ok.

The workaround we'll have to implement until that is addressed is to manually implement the correct slugification logic in ansible/jinja - posting because this may help others who run into this same issue:

```yaml
- name: Properly slugify site or other object names
  debug:
    msg: '{{ item | regex_replace("(?a)[^\-\.\w\s]", "") | trim | regex_replace("[\-\.\s]+", "-") | lower }}'
  loop:
    - Königliches Rechenzentrum
    - Skåne
    - Keep an eye on this site 👀
```

task output:

```
TASK [Properly slugify site or other object names] *******************************************************************
ok: [localhost] => (item=Königliches Rechenzentrum) => {
    "msg": "knigliches-rechenzentrum"
}
ok: [localhost] => (item=Skåne) => {
    "msg": "skne"
}
ok: [localhost] => (item=Keep an eye on this site 👀) => {
    "msg": "keep-an-eye-on-this-site"
}
```

use in a full task to manually pass a valid slug while preserving unicode in the displayname:

```yaml
- name: Reproduce bug
  netbox.netbox.netbox_site:
    netbox_url: '{{ netbox_url }}'
    netbox_token: '{{ netbox_token }}'
    state: present
    data:
      name: '{{ item }}'
      slug: '{{ item | regex_replace("(?a)[^\-\.\w\s]", "") | trim | regex_replace("[\-\.\s]+", "-") | lower }}'
      tags: [FortiGate-Sync]
  loop:
    - Königliches Rechenzentrum
    - Skåne
    - Keep an eye on this site 👀
```
