### ISSUE TITLE
[Bug]: Site in uppercase not found using netbox_cluster

### ISSUE THREAD

**Issue by smutel** [netbox-community/ansible_modules#821]
### Ansible NetBox Collection version

v3.7.1

### Ansible version

```bash
ansible [core 2.11.12]
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

### NetBox version

v3.0.12

### Python version

3.8

### Steps to Reproduce

* Create a site in Netbox in uppercase (name and slug in uppercase). CDC for this example.
* Execute the code below:
```
netbox.netbox.netbox_cluster:
  netbox_url: http://netbox.local
  netbox_token: thisIsMyToken
  data:
    name: "{{ inventory_hostname_short }}"
    cluster_type: "proxmox"
    cluster_group: "test"
    site: "CDC"                           
  state: present
```

### Expected Behavior

Cluster created in Netbox.

### Observed Behavior

Error:
```
msg: 'Could not resolve id of site: cdc'
```
