### ISSUE TITLE
[Bug]: Swapped behaviour for vCPUs on VMs between pre and post 3.0.0

### ISSUE THREAD

**Issue by bvergnaud** [netbox-community/ansible_modules#823]
### Ansible NetBox Collection version

v3.7.1

### Ansible version

```bash
ansible [core 2.13.1]
  config file = /home/bvergnaud/git/scw/platform/vm-containers/iaas-playbooks/ansible.cfg
  configured module search path = ['/home/bvergnaud/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bvergnaud/.local/share/virtualenvs/iaas-playbooks-3YYUb2kg/lib/python3.8/site-packages/ansible
  ansible collection location = /home/bvergnaud/git/scw/platform/vm-containers/iaas-playbooks/.collections
  executable location = /home/bvergnaud/.local/share/virtualenvs/iaas-playbooks-3YYUb2kg/bin/ansible
  python version = 3.8.13 (default, Apr  4 2022, 10:14:53) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v2.10.10

### Python version

3.8

### Steps to Reproduce

Running a simple `netbox.netbox.netbox_virtual_machine` task twice, with the vcpus parameter set:
```yml
- name: "Create/delete VM on NetBox"
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: test-vm
      vcpus: 1
    state: present
  delegate_to: localhost
```

### Expected Behavior

The task should be idempotent and report status=ok with no changes.

### Observed Behavior

On the second run, it produces a diff:
```diff
--- before
+++ after
@@ -1 +1 @@
-vcpus: 1
+vcpus: '1.00'

changed: [lab1dc2-inf-dev-hv16 -> localhost] => changed=true
  msg: virtual_machine test-vm updated
  virtual_machine:
    comments: ''
    config_context: {}
    created: '2022-09-06'
    custom_fields:
      vmid: null
    id: 9094
    last_updated: '2022-09-06T14:00:18.040069Z'
    local_context_data: null
    name: test-vm
    status: active
    url: https://netbox-staging.internal.scaleway.com/api/virtualization/virtual-machines/9094/
    vcpus: 1.0
```

Note:
* Output filtered manually from testing with more parameters, in case anything looks odd.
* The same behaviour holds true if we cast the value of `vcpus` as int or float.
