### ISSUE TITLE
[Bug]: netbox_prefix should ignore vlan parameter if state==absent

### ISSUE THREAD

**Issue by jsalatiel** [netbox-community/ansible_modules#836]
### Ansible NetBox Collection version

v3.8.0

### Ansible version

```bash
2.11.7
```

### NetBox version

3.2.5

### Python version

3.8

### Steps to Reproduce

Create a prefix using the following data:
```
    data:
      prefix: 192.168.0.0/24
      description: description
      vlan:
        name: 'test vlan'
    state: 'present
```
Now manually delete the prefix and vlan on the webui and re-run the playbook using absent instead of present and the playbook will fail.
The module should not try to parse the VLAN if it the prefix state is absent.

### Expected Behavior

The playbook should not fail

### Observed Behavior

The playbook fails if the vlan does not exist even if the required state for the prefix is absent
