### ISSUE TITLE
[Bug]: Partial update of custom fields is not idempotent

### ISSUE THREAD

**Issue by cfiehe** [netbox-community/ansible_modules#943]
### Ansible NetBox Collection version

v3.10.0

### Ansible version

```bash
$ ansible --version
ansible [core 2.14.1]
  config file = /home/ansible/automation/projects/provisioning/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansible/automation/projects/provisioning/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### NetBox version

v3.4.4

### Python version

3.10

### Steps to Reproduce

Define some custom fields e.g. for a virtual machine and set them for a specific object from the API or the UI. Update some of the object's fields via Ansible:
```
- name: Test playbook
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    netbox_url: https://netbox-sre.dev.k8s-svc.mycompany.de
    netbox_token: SECRET
  tasks:
    - name: Partial update of virtual machine's custom fields
      delegate_to: localhost
      netbox.netbox.netbox_virtual_machine:
        netbox_token: "{{ netbox_token }}"
        netbox_url: "{{ netbox_url }}"
        state: present
        data:
          name: test.lx.mycompany.de
          tenant: mycompany
          cluster: TEST_UCS
          platform: Linux Ubuntu
          status: Active
          tenant: mycompany
          cluster: TEST_UCS
          custom_fields:
            VM_platform_version: '22.04'
            VM_folder: LOC.Test
            VM_prodtype: Lab
```

### Expected Behavior

I expect that only those fields are updated and that subsequent runs do not report any changes.

### Observed Behavior

The specified fields are updated, but the module reports that all other custom fields are removed and keeps reporting changes on subsequent runs. The reported diff is incorrect. Those fields that were not specified by the user are not touched at all and keep existing after the module's termination.

First run:
```
TASK [Partial update of virtual machine's custom fields] **********************************************************************************************************************************************
Sunday 12 February 2023  16:28:28 +0100 (0:00:00.052)       0:00:00.052 *******
--- before
+++ after
@@ -1,21 +1,7 @@
 {
     "custom_fields": {
-        "VM_NetworkAdapter_1": "DS-VLAN 59",
-        "VM_NetworkAdapter_1_IP": "10.2.59.80; fe80::250:56ff:fe87:924c",
-        "VM_critical": false,
-        "VM_guestosfullname": "Ubuntu Linux (64-bit)",
-        "VM_id": "VirtualMachine-vm-3574514",
-        "VM_impact": false,
-        "VM_platform_version": "20.04",
-        "VM_priority": "None",
-        "VM_prodtype": "Lab",
-        "VM_sla": "None",
-        "VM_uuid": "50074530-8d2b-3c87-c90d-3e6fd19d1813",
-        "VMupdater_add": "2023-01-09 13:28",
-        "VMupdater_upd": "2023-02-06 09:37",
-        "monitoring_serviceset_os_vm": [
-            "Server OS Ping"
-        ],
-        "monitoring_serviceset_os_vm_priority": "priority-server-os-medium"
+        "VM_folder": "LOC.Test",
+        "VM_platform_version": "22.04",
+        "VM_prodtype": "Lab"
     }
 }

changed: [localhost]
```

Subsequent runs:
```
TASK [Partial update of virtual machine's custom fields] **********************************************************************************************************************************************
Sunday 12 February 2023  16:28:44 +0100 (0:00:00.051)       0:00:00.051 *******
--- before
+++ after
@@ -1,22 +1,7 @@
 {
     "custom_fields": {
-        "VM_NetworkAdapter_1": "DS-VLAN 59",
-        "VM_NetworkAdapter_1_IP": "10.2.59.80; fe80::250:56ff:fe87:924c",
-        "VM_critical": false,
         "VM_folder": "LOC.Test",
-        "VM_guestosfullname": "Ubuntu Linux (64-bit)",
-        "VM_id": "VirtualMachine-vm-3574514",
-        "VM_impact": false,
         "VM_platform_version": "22.04",
-        "VM_priority": "None",
-        "VM_prodtype": "Lab",
-        "VM_sla": "None",
-        "VM_uuid": "50074530-8d2b-3c87-c90d-3e6fd19d1813",
-        "VMupdater_add": "2023-01-09 13:28",
-        "VMupdater_upd": "2023-02-06 09:37",
-        "monitoring_serviceset_os_vm": [
-            "Server OS Ping"
-        ],
-        "monitoring_serviceset_os_vm_priority": "priority-server-os-medium"
+        "VM_prodtype": "Lab"
     }
 }

changed: [localhost]
```
