### ISSUE TITLE
[Feature]: possiblity to add netbox.netbox.netbox_vm_interface using virtual_machine_id 

### ISSUE THREAD

**Issue by f22l2** [netbox-community/ansible_modules#953]
### NetBox version

v3.4.4

### Feature type

Change to existing Module

### Proposed functionality

possiblity to add netbox.netbox.netbox_vm_interface using virtual_machine id (expected int)  as an option besides currently used virtual_machine (expected string) parameter 

```
  - name: Create interface within NetBox with only required information
    netbox.netbox.netbox_vm_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          custom_fields:
            NetworkName: "{{ item.network }}"
          virtual_machine: "{{ vm_id }}" #expected int
          name: "Network adapter {{ network_adapter_index + 1 }}"
          enabled: "{{ item.connected }}"
          mac_address: "{{ item.macAddress }}"
        state: present
        validate_certs: false
    delegate_to:  localhost
    loop: "{{ hostvars[outer_item.name].guest.net }}"
    loop_control:
      index_var: network_adapter_index

```

### Use case

In case if in Netbox 2 or more virtual machines exist with the same name in 2 or more tenants, there is no technical possibility to use  netbox.netbox.netbox_vm_interface module to add interface to one of these machines, as more than 1 result will be presented.
Adding option to add via virtual_machine_id (unique value) will fix this problem.

Technically using API request we are able to filter specic interface using:

GET /api/virtualization/interfaces/?virtual_machine_id=<id of vm>
 

### External dependencies

n/a

**Comment by sc68cal** [comment]
Should we change `virtual_machine` to instead reference the slug of a virtual machine, since that is unique and (mostly) the same value?

**Comment by sc68cal** [comment]
Yes that sounds reasonable to me.

**Comment by sc68cal** [comment]
Are you working on it?

**Comment by rodvand** [comment]
This works for me:
```
---

- hosts: localhost
  connection: local
  gather_facts: false
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: URL
      netbox_token: TOKEN
  vars:
    state: present
  tasks:
    - name: Create an interface and add to vm
      netbox.netbox.netbox_vm_interface:
        data:
          name: eth99
          virtual_machine:
            id: 42
```

Returns:
```
TASK [Create an interface and add to vm] ******************************************************************************************************
changed: [localhost] => changed=true
  interface:
    bridge: null
    count_fhrp_groups: 0
    count_ipaddresses: 0
    created: '2023-03-30T23:03:55.669644+02:00'
    custom_fields: {}
    description: ''
    display: eth99
    enabled: true
    id: 99
    l2vpn_termination: null
    last_updated: '2023-03-30T23:03:55.669665+02:00'
    mac_address: null
    mode: null
    mtu: null
    name: eth99
    parent: null
    tagged_vlans: []
    tags: []
    untagged_vlan: null
    url: URL
    virtual_machine: 42
    vrf: null
  msg: interface eth99 created
```
