### ISSUE TITLE
[Feature]: nb_inventory - return device ID

### ISSUE THREAD

**Issue by mkurjanski** [netbox-community/ansible_modules#954]
### NetBox version

v3.4.4

### Feature type

Change to existing Module

### Proposed functionality

It would be useful to get the netbox ID returned for the inventory devices. 

### Use case

The reason is because the Netbox graphql only allow querying by ID if you need to query a single device. Having the ID returned in the inventory phase would make these graphql much easier.

### External dependencies

none

**Comment by aopdal** [comment]
As a workaround you can use:

compose:
  device_id: id

In your inventory file

**Comment by mkurjanski** [comment]
Thank you for this hint. I never quite understood how to use the compose function.

**Comment by ypid-work** [comment]
nb_inventory also matches against VMs so naming the inventory variable `device_id` can be misleading. Maybe:

```yaml
compose:
  # https://github.com/netbox-community/ansible_modules/issues/954
  netbox_object_id: id
```
