### ISSUE TITLE
[Bug]: Nebox_location module updates existing locations instead of creating new ones in a different site

### ISSUE THREAD

**Issue by artiomello** [netbox-community/ansible_modules#958]
### Ansible NetBox Collection version

v3.11

### Ansible version

Running in AWX. Version is irrelevant to the case.

### NetBox version

3.3.7

### Python version

3.8

### Steps to Reproduce

When trying to create new location in a new site using netbox.netbox.netbox_location module updates existing locations with the same name, even though they are located in a different site, instead of creating new ones with their own separate site.

Locations are created like so:
```yaml
  - name: Creating locations
    netbox.netbox.netbox_location:
      data: "{{ location }}"
      state: present
    loop: "{{ latvia_locations }}"
    loop_control:
      loop_var: location
      label: "{{ location.site, location.name }}"
    tags: LV.locations
```
with looped locations defined in the following way:
```yaml
latvia_locations:
  - name: Marupe
    description: Main location
    site: Marupe
    tenant: xxx
    tags: "{{ latvia_defaults.tags }}"
  - name: Office Data Center
    description: Office building
    parent_location: Marupe
    site: Marupe
    tenant: xxx
    tags: "{{ latvia_defaults.tags }}"

```

### Expected Behavior

Existing locations with the same name but different sites should stay unchanged and previously undefined site/location pairs should be created properly instead.

### Observed Behavior

Because I already have a location named "Office Data Center" within a different site, e.g. "Riga", what actually happens is that the latter location in Riga gets updated (its site is effectively changed from Riga to Marupe) instead of a new one in Marupe being created.

**Comment by sc68cal** [comment]
Can you provide a log of the playbook run with the verbosity increased (`-vvv`) and any sensitive credentials or information sanitized? I am specifically looking for the `invocation` and `module_args` part to see what gets sent

**Comment by artiomello** [comment]
Here you go:
```json
  "invocation": {
    "module_args": {
      "netbox_url": "https://netbox",
      "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "validate_certs": "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt",
      "data": {
        "name": "Office Data Center",
        "description": "Office building",
        "parent_location": "Marupe",
        "site": "Marupe",
        "tenant": "xxx",
        "tags": [
          "Latvia",
          "Marupe"
        ],
        "slug": null,
        "custom_fields": null
      },
      "state": "present",
      "query_params": null,
      "cert": null
    }
  },
  "_ansible_no_log": false,
  "ansible_loop_var": "location",
  "_ansible_item_label": "('Marupe', 'Office Data Center')"
}

```

Not sure how to get the output with -vvv from AWX though.

**Comment by sc68cal** [comment]
OK, don't worry about the `-vvv` but you only posted the one iteration of the loop? I only see the second item in the list, did it do the loop for the first item as well?

**Comment by artiomello** [comment]
And when I have more than one location with the same name already in the system I get this:
```json
{
  "changed": false,
  "msg": "More than one result returned for Office Data Center",
  "invocation": {
    "module_args": {
      "netbox_url": "https://netbox",
      "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "validate_certs": "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt",
      "data": {
        "name": "Office Data Center",
        "description": "Office building",
        "parent_location": "Marupe",
        "site": "Marupe",
        "tenant": "xxx",
        "tags": [
          "Latvia",
          "Marupe"
        ],
        "slug": null,
        "custom_fields": null
      },
      "state": "present",
      "query_params": null,
      "cert": null
    }
```

**Comment by sc68cal** [comment]
Are you able to run your playbook locally instead of the AWX server, so that you can set `ANSIBLE_DEBUG` and increase the verbosity so we can see the HTTP traffic between your Ansible playbook and the NetBox server?

**Comment by sc68cal** [comment]
Great. I'll dig into the logs next week and attempt to replicate the issue locally. Thanks so much for your patience and the information gathering.

**Comment by rodvand** [comment]
Currently our code only does a lookup based on the slug. 

https://github.com/netbox-community/ansible_modules/blob/c6df6be33f1f860262b66360314493128284042d/plugins/module_utils/netbox_utils.py#L438

This means we assume the slug to be unique. In this case it's not. The API call being done is something like this:
`https://YOUR_URL/api/dcim/locations/?slug=test-data-center`. So you'll create your first location, and when you want to create your second location with the same slug it will just lookup the first one and change it.

The fix is pretty simple, we add site as a filter so it will be `"location": set(["slug", "site"]),` instead. This should allow the creation of two locations named the same within different sites.

**Comment by artiomello** [comment]
Thanks for the quick actions, but I still have a few questions:
- I'm not familiar with the release process for these changes. When can I expect this fix to be actually applied? I'm asking because I'm still getting the same behavior.
- Will you also fix the `netbox.netbox.netbox_rack` module based on provided info in this issue or should I create a new one?

Thanks again!

**Comment by rodvand** [comment]
You should create a separate issue for the netbox_rack issue. 

If you want to test you can install the collection from a git repository. See https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html

I think the earliest I can craft a new release will be Monday.

**Comment by artiomello** [comment]
So what's the resulting set of properties for this module then? 
Should it be defined like so or..?
```yaml
  - name: Office Data Center
    description: Office building
    parent_location: Marupe
    site: "{{ latvia_defaults.site }}"
    location: 
      name: Office Data Center
      site: "{{ latvia_defaults.site }}"
    tenant: xxx
    tags: "{{ latvia_defaults.tags }}"
```

**Comment by artiomello** [comment]
@rodvand ?

**Comment by artiomello** [comment]
Guys, how do I use it now? Documentation has not been updated with your changes.

**Comment by sc68cal** [comment]
I believe the example you posted @artiomello with `site` set, and then `location` having two keys of `name` and `site` set will work.

**Comment by sc68cal** [comment]
```yaml
  - name: Office Data Center
    description: Office building
    parent_location: Marupe
    location: 
      name: Office Data Center
      site: "{{ latvia_defaults.site }}"
    tenant: xxx
    tags: "{{ latvia_defaults.tags }}"
```

Might also work although I have not tested it
