### ISSUE TITLE
[Bug]: netbox_rack module doesn't distinguish unique site/locations pairs

### ISSUE THREAD

**Issue by artiomello** [netbox-community/ansible_modules#964]
### Ansible NetBox Collection version

v3.11

### Ansible version

Running in AWX. Version is irrelevant to the case.

### NetBox version

3.3.7

### Python version

3.8

### Steps to Reproduce

Racks are created like so:

```yaml
  - name: Creating racks
    netbox.netbox.netbox_rack:
      data: "{{ rack }}"
      state: present
    loop: "{{ latvia_racks }}"
    loop_control:
      loop_var: rack
      label: "{{ rack.location, rack.name }}"
    tags: LV.racks
```

using looped values defined like so:
```yaml
  - name: Rack 1
    location: LVMA Office Data Center
    tenant: xxx
    site: "{{ latvia_defaults.site }}"
    status: Active
    rack_role: Mixed
    facility_id: Rack 1
    tags: "{{ latvia_defaults.tags + [ 'Marupe Office DC' ] }}"
```

### Expected Behavior

`netbox_rack` module should look at unique site/location pairs, instead of only unique locations, as it is now.

Similar issue has been already discussed and resolved as part of a different module: #958 therefore it should be a quick and easy fix.

### Observed Behavior

`netbox_rack` module fails to create a new rack when there's more than one location with the same name, regardless of them being in different sites:

```json
{
  "changed": false,
  **"msg": "More than one result returned for location",**
  "invocation": {
    "module_args": {
      "netbox_url": "https://netbox",
      "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "validate_certs": "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt",
      "data": {
        "name": "Rack 1",
        "location": "Office Data Center",
        "tenant": "xxx",
        "site": "Marupe",
        "status": "Active",
        "rack_role": "Mixed",
        "facility_id": "Rack 1",
        "tags": [
          "Latvia",
          "Marupe",
          "Marupe Office DC"
        ],
```

**Comment by rodvand** [comment]
I've added filter options to the location parameter. You will need to use it like this:
```
  - name: Creating racks
    netbox.netbox.netbox_rack:
      data:
        name: Rack 1
        site: site name
        location:
          name: location name
          site: site name
```

Will be available in the next collection release.
