### ISSUE TITLE
[Bug]: to many seperators in keyed group (nb_inventory)

### ISSUE THREAD

**Issue by MalfuncEddie** [netbox-community/ansible_modules#979]
### Ansible NetBox Collection version

v3.12.0

### Ansible version

```bash
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/scsn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/scsn/testcase/testcase_venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/scsn/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/scsn/testcase/testcase_venv/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] (/home/scsn/testcase/testcase_venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v3.3.5

### Python version

3.10

### Steps to Reproduce

```
---
plugin: netbox.netbox.nb_inventory
fetch_all: True
validate_certs: True
config_context: True
services: False
site_data: False
racks: False
vm_query_filters:
  - tenant: XXX
  - status: active
device_query_filters:                                                                                                                                           
  - id: -1
leading_separator: ""
separator: ""
keyed_groups:
  - prefix: "blah"
    key: platform.slug,tenant.slug
    seperator: ""
    trailing_separator: false
```

I did get some fixes with
`key: (platform.slug,tenant.slug | split(',')) | replace("[","") | replace("]","") | replace("'","")| replace(" ","")  | replace('"',"") | replace('_',"") | replace('-',"") | replace('}',"") | replace('{',"")  |  trim`

But even with that I get a trailing underscore

What I would like to have is a keyed group with multiple netbox fields.

### Expected Behavior

groups like

"blah__microsoft_windows_server_2008_r2_64_bit__tenantA",

### Observed Behavior

groups like

blah___microsoft_windows_server_2008_r2_64_bit_____tenantA__

output of ansible-inventory 

output (the group part) :

```
"all": {
        "children": [
            "ungrouped",
            "blah___microsoft_windows_server_2008_r2_64_bit_____tenantA__",
            "blah___oracle_linux_6_64_bit_____tenantA__",
            "blah___microsoft_windows_server_2016_or_later_64_bit_____tenantA__",
            "blah___microsoft_windows_server_2019_64_bit_____tenantA__",
        ]
    },
```
