### ISSUE TITLE
[Bug]: unable to update allowed_vlan using netbox_device_interface

### ISSUE THREAD

**Issue by saifvs** [netbox-community/ansible_modules#980]
### Ansible NetBox Collection version

v3.12.0

### Ansible version

```bash
ansible [core 2.13.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/saif/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/saif/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = False

```

### NetBox version

v3.4.5

### Python version

3.8

### Steps to Reproduce

I have interface dictionary with about 48 ports, among this 1 interface configured has trunk with allowed_vlan mentioned, however when we run the play, getting the error "More than one result returned for tagged_vlans"

here is the dictionary 
```
  GigabitEthernet1/0/44:
    access_vlan: '100'
    mode: access
    voice_vlan: '200'
    stp_portfast: enable
  GigabitEthernet1/0/45:
    access_vlan: '100'
    mode: access
    voice_vlan: '200'
    stp_portfast: enable
  GigabitEthernet1/0/46:
    access_vlan: '100'
    mode: access
    voice_vlan: '200'
    stp_portfast: enable
  GigabitEthernet1/0/47:
    allowed_vlan:
      - '3'
      - '22'
      - '32'
      - '121'
      - '130'
      - '133'
      - '134'
      - '200'
      - '231'
      - '232'
      - '233'
      - '510'
      - '511'
      - '512'
      - '513'
    mode: trunk
  GigabitEthernet1/0/48:
    description: '"to _test_sw"'
    access_vlan: '214'
    mode: access
    stp_portfast: enable
```
Here is the task
```
- name: Updating the interface with tagged (untagged and voice vlan)
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: no
    data:
      device: "{{hostname | upper}}"
      name: "{{item.key}}"
      mode: "{{access}}"
      untagged_vlan:
        vid: "{{item.value.access_vlan if item.value.access_vlan is defined else 1}}"
        site: "{{site }}"
      tagged_vlans:
        - vid: "{{(item.value.voice_vlan if item.value.voice_vlan is defined) or (item.value.allowed_vlan if item.value.allowed_vlan is defined and item.value.mode == 'trunk' | default(omit))}}"
          site: "{{site}}"
    state: present
  with_dict: "{{interface}}"
  when: (item.value.mode is defined and item.value.voice_vlan is defined and item.value.mode == 'access') or (item.value.allowed_vlan is defined and item.value.mode == 'trunk') and ansible_facts.net_stacked_serialnums | length == 1
  tags:
    - test
```

In documenation it says, it accept the list, however it doesnt.

### Expected Behavior

it should read the dictionary, and update the interface with allowed_vlans in it.

### Observed Behavior

Getting an error.

Here is the acutal output error.
```
ok: [lab-sw01] => (item={'key': 'GigabitEthernet1/0/44', 'value': {'access_vlan': '100', 'mode': 'access', 'voice_vlan': '200', 'stp_portfast': 'enable'}})
ok: [lab-sw01] => (item={'key': 'GigabitEthernet1/0/45', 'value': {'access_vlan': '100', 'mode': 'access', 'voice_vlan': '200', 'stp_portfast': 'enable'}})
ok: [lab-sw01] => (item={'key': 'GigabitEthernet1/0/46', 'value': {'access_vlan': '100', 'mode': 'access', 'voice_vlan': '200', 'stp_portfast': 'enable'}})
failed: [lab-sw01] (item={'key': 'GigabitEthernet1/0/47', 'value': {'allowed_vlan': ['3', '22', '32', '121', '130', '133', '134', '200', '231', '232', '233', '510', '511', '512', '513'], 'mode': 'trunk'}}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "GigabitEthernet1/0/47", "value": {"allowed_vlan": ["3", "22", "32", "121", "130", "133", "134", "200", "231", "232", "233", "510", "511", "512", "513"], "mode": "trunk"}}, "msg": "More than one result returned for tagged_vlans"}
skipping: [lab-sw01] => (item={'key': 'GigabitEthernet1/0/48', 'value': {'description': '"to _test_sw"', 'access_vlan': '214', 'mode': 'access', 'stp_portfast': 'enable'}})
```
